### PR TITLE
Update dtc/develop from develop and other updates 2020/04/09

### PR DESCRIPTION
**Pull request by climbfuji**
This PR contains:
- Coupled model: IPD-CCPP b4b for coupled model, bugfix for stochastic physics (ufs-community#91)
- Regional BC blending and BCs into GSI (ufs-community#83)
- Switch to Intel 18 on WCOSS Cray. Run full `rt.sh` test on WCOSS Cray (from @dusanjovic-noaa)
- `cmake/configure_macosx.gnu.cmake`: turn OpenMP off for LLVM clang compilers (from public release branch)
- `tests/fv3_conf/ccpp_control_run.IN`: change name of input data for RRTMGP tests
- `tests/rt_gnu.conf`: compile on all platforms, not just on Cheyenne (but don't run anywhere else yet)
- `tests/rt.sh`: align directory structure on Cheyenne with Hera, update date tag of regression test baseline
- `CMakeLists.txt`: require CMake 3.0

Associated PRs:
https://github.com/NCAR/GFDL_atmos_cubed_sphere/pull/11
https://github.com/NCAR/ccpp-framework/pull/281
https://github.com/NCAR/ccpp-physics/pull/432 (contains https://github.com/NCAR/ccpp-physics/pull/424)
https://github.com/NCAR/fv3atm/pull/40
https://github.com/NCAR/ufs-weather-model/pull/38/files

For regression testing information, see below.

### CODE REVIEW

**Comment by climbfuji** [comment]
### Note on regression testing

Note that the regional blending updates from EMC changed the results for the following tests:
```
fv3_regional_control
fv3_regional_control_repro
fv3_regional_control_ccpp
fv3_regional_restart
fv3_regional_restart_repro
fv3_regional_restart_ccpp
```
On hera.intel, these updates baselines were synced from the official EMC baseline to our DTC baseline, in order to run the full regression tests against the DTC baseline and knowing that no results changed from our side.

On cheyenne.intel, the new input files were copied from hera and new baselines generated for just these tests (nothing else) and merged with the existing baseline to create the new baseline. Then, the full regression tests against the updated baseline were run.

On cheyenne.gnu, these tests are not executed and the regression tests were run against an rsync-ed copy of the previous baseline (i.e. just a new date tag). However, the new input files for the regional tests were also copied into the baseline in order to enable those tests in the future.

**Comment by climbfuji** [comment]
Regression testing on cheyenne.gnu against existing baseline (with new date tag): all tests pass.

[rt_cheyenne_gnu.log](https://github.com/NCAR/ufs-weather-model/files/4459521/rt_cheyenne_gnu.log)

**Comment by ligiabernardet** [comment]
I did not inspect the code in detail, but I looked overall at what is involved in this update. All looks good to me, and I am glad to see innovations in CCPP-F and CCPP-P making their way to master.

**Comment by climbfuji** [comment]
Regression testing on hera.intel against new baseline (which is a copy of our old baseline, just the tests with changes as listed above are copied over from the new EMC baseline): all tests pass. I had to rerun two tests because of file system issues on hera.

[rt_hera_intel.log](https://github.com/NCAR/ufs-weather-model/files/4461960/rt_hera_intel.log)
[rt_hera_intel_fail_test.log](https://github.com/NCAR/ufs-weather-model/files/4461962/rt_hera_intel_fail_test.log)
[rt_hera_intel_rerun.log](https://github.com/NCAR/ufs-weather-model/files/4461963/rt_hera_intel_rerun.log)

**Comment by climbfuji** [comment]
Regression testing on cheyenne.intel against new baseline: **tests still running** - however, we do not need to wait for this to finish. Therefore, the PR is ready.

**Comment by climbfuji** [comment]
I merged all these PRs without further approval to prepare our commit to master (after merging in the IN/CCN MG changes in another round of commits).

**Pull request merged**
