### PR TITLE
UFS-dev PR#153

### PR DESCRIPTION
**Pull request by grantfirl**
Identical to https://github.com/ufs-community/ufs-weather-model/pull/2082 (BL change - see below)

Also contains:
https://github.com/ufs-community/ufs-weather-model/pull/2080 (no BL change)
https://github.com/ufs-community/ufs-weather-model/pull/2027 (BL change - see below)
https://github.com/ufs-community/ufs-weather-model/pull/2035 (no BL change)

### CODE REVIEW

**Comment by grantfirl** [comment]
Expected RT failures for 2082:

New baselines are needed for all conus_13km related tests. Namely:
conus13km_2threads conus13km_debug conus13km_debug_decomp conus13km_decomp conus13km_restart
conus13km_control conus13km_debug_2threads conus13km_debug_qr conus13km_radar_tten_debug conus13km_restart_mismatch

**Comment by grantfirl** [comment]
Expected RT failures for 2027:

7378:001 cpld_control_p8_mixedmode_intel failed in check_result
7380:002 cpld_control_gfsv17_intel failed in check_result
7382:005 cpld_mpi_gfsv17_intel failed in check_result
7384:006 cpld_debug_gfsv17_intel failed in check_result
7386:007 cpld_control_p8_intel failed in check_result
7388:009 cpld_control_qr_p8_intel failed in check_result
7390:011 cpld_2threads_p8_intel failed in check_result
7392:012 cpld_decomp_p8_intel failed in check_result
7394:013 cpld_mpi_p8_intel failed in check_result
7396:014 cpld_control_ciceC_p8_intel failed in check_result
7398:015 cpld_control_c192_p8_intel failed in check_result
7400:017 cpld_bmark_p8_intel failed in check_result
7402:019 cpld_control_noaero_p8_intel failed in check_result
7404:020 cpld_control_nowave_noaero_p8_intel failed in check_result
7406:021 cpld_debug_p8_intel failed in check_result
7408:022 cpld_debug_noaero_p8_intel failed in check_result
7410:023 cpld_control_noaero_p8_agrid_intel failed in check_result
7412:024 cpld_control_c48_intel failed in check_result
7414:025 cpld_control_p8_faster_intel failed in check_result
7416:026 cpld_control_pdlib_p8_intel failed in check_result
7418:029 cpld_debug_pdlib_p8_intel failed in check_result
7420:150 datm_cdeps_control_cfsr_intel failed in check_result
7422:152 datm_cdeps_control_gefs_intel failed in check_result
7424:153 datm_cdeps_iau_gefs_intel failed in check_result
7426:154 datm_cdeps_stochy_gefs_intel failed in check_result
7428:155 datm_cdeps_ciceC_cfsr_intel failed in check_result
7430:156 datm_cdeps_bulk_cfsr_intel failed in check_result
7432:157 datm_cdeps_bulk_gefs_intel failed in check_result
7434:158 datm_cdeps_mx025_cfsr_intel failed in check_result
7436:159 datm_cdeps_mx025_gefs_intel failed in check_result
7438:160 datm_cdeps_multiple_files_cfsr_intel failed in check_result
7440:161 datm_cdeps_3072x1536_cfsr_intel failed in check_result
7442:162 datm_cdeps_gfs_intel failed in check_result
7444:163 datm_cdeps_debug_cfsr_intel failed in check_result
7446:164 datm_cdeps_control_cfsr_faster_intel failed in check_result
7448:231 cpld_control_p8_gnu failed in check_result
7450:232 cpld_control_nowave_noaero_p8_gnu failed in check_result
7452:233 cpld_debug_p8_gnu failed in check_result
7454:234 cpld_control_pdlib_p8_gnu failed in check_result
7456:235 cpld_debug_pdlib_p8_gnu failed in check_result
7458:236 datm_cdeps_control_cfsr_gnu failed in check_result

**Comment by mkavulich** [comment]
@grantfirl Since this PR represents a huge code reorganization, maybe it's prudent to run a quick regression test just to sanity check?

**Comment by grantfirl** [comment]
> @grantfirl Since this PR represents a huge code reorganization, maybe it's prudent to run a quick regression test just to sanity check?

Sure. Let's try it.

**Comment by grantfirl** [comment]
> @grantfirl Since this PR represents a huge code reorganization, maybe it's prudent to run a quick regression test just to sanity check?

Darn it. I forgot that one of the previous PRs required new input data to be staged, so there are some run failures.

**Comment by grantfirl** [comment]
> > @grantfirl Since this PR represents a huge code reorganization, maybe it's prudent to run a quick regression test just to sanity check?
> 
> Darn it. I forgot that one of the previous PRs required new input data to be staged, so there are some run failures.

I staged the new file for MOM6 from https://github.com/ufs-community/ufs-weather-model/pull/1979, although it only looks like it should have caused one run failure (cpld_control_c48_intel).

**Comment by mkavulich** [comment]
Okay, sounds good, if you didn't get to it in time and just that one test fails I'd call that fine.

**Comment by mkavulich** [comment]
Oh I see now, there are a bunch of failures. Let me see what's going on there.

**Comment by grantfirl** [comment]
> Oh I see now, there are a bunch of failures. Let me see what's going on there.

Well, I think that most of the failures are expected BL changes. The first failure that came up was the cpld_control_c48_intel test and it died due to lack of the file, which triggered my memory about the input changes, but I'm waiting until the script is finished to see if there are any other run failures. It shouldn't be THAT hard to double check that the rest of the failures correspond to BL changes from previously merged PRs. I think that most were kinda light on changes anyway, changing a few tests at a time.

**Comment by mkavulich** [comment]
Ah right, sorry I'm a bit slow this afternoon. I also saw one failure for a missing baseline, but that should be ok too since we haven't been updating the baselines.

**Comment by mkavulich** [comment]
***Automated RT Failure Notification***
Machine: hera
Job: RT
[RT] Repo location: /scratch1/BMC/gmtb/CCPP_regression_testing/NCAR_ufs-weather-model/beta/run//1714448876/20240312191015/ufs-weather-model
[RT] Error: Test 001 cpld_control_p8_mixedmode_intel FAIL Tries: 2
[RT] Error: Test 002 cpld_control_gfsv17_intel FAIL Tries: 2
[RT] Error: Test 005 cpld_mpi_gfsv17_intel FAIL Tries: 2
[RT] Error: Test 006 cpld_debug_gfsv17_intel FAIL Tries: 2
[RT] Error: Test 007 cpld_control_p8_intel FAIL Tries: 2
[RT] Error: Test 009 cpld_control_qr_p8_intel FAIL Tries: 2
[RT] Error: Test 011 cpld_2threads_p8_intel FAIL Tries: 2
[RT] Error: Test 012 cpld_decomp_p8_intel FAIL Tries: 2
[RT] Error: Test 013 cpld_mpi_p8_intel FAIL Tries: 2
[RT] Error: Test 014 cpld_control_ciceC_p8_intel FAIL Tries: 2
[RT] Error: Test 015 cpld_control_c192_p8_intel FAIL Tries: 2
[RT] Error: Test 017 cpld_bmark_p8_intel FAIL Tries: 2
[RT] Error: Test 019 cpld_s2sa_p8_intel FAIL Tries: 2
[RT] Error: Test 020 cpld_control_noaero_p8_intel FAIL Tries: 2
[RT] Error: Test 021 cpld_control_nowave_noaero_p8_intel FAIL Tries: 2
[RT] Error: Test 022 cpld_debug_p8_intel FAIL Tries: 2
[RT] Error: Test 023 cpld_debug_noaero_p8_intel FAIL Tries: 2
[RT] Error: Test 024 cpld_control_noaero_p8_agrid_intel FAIL Tries: 2
[RT] Error: Test 025 cpld_control_c48_intel FAIL
[RT] Error: Test 025 cpld_control_c48_intel FAIL
[RT] Error: Test 026 cpld_control_p8_faster_intel FAIL Tries: 2
[RT] Error: Test 027 cpld_control_pdlib_p8_intel FAIL Tries: 2
[RT] Error: Test 030 cpld_debug_pdlib_p8_intel FAIL Tries: 2
[RT] Error: Test 060 regional_noquilt_intel FAIL Tries: 2
[RT] Error: Test 064 rap_control_intel FAIL Tries: 2
[RT] Error: Test 065 regional_spp_sppt_shum_skeb_intel FAIL Tries: 2
[RT] Error: Test 066 rap_decomp_intel FAIL Tries: 2
[RT] Error: Test 067 rap_2threads_intel FAIL Tries: 2
[RT] Error: Test 069 rap_sfcdiff_intel FAIL Tries: 2
[RT] Error: Test 070 rap_sfcdiff_decomp_intel FAIL Tries: 2
[RT] Error: Test 072 hrrr_control_intel FAIL Tries: 2
[RT] Error: Test 073 hrrr_control_decomp_intel FAIL Tries: 2
[RT] Error: Test 074 hrrr_control_2threads_intel FAIL Tries: 2
[RT] Error: Test 079 control_csawmg_intel FAIL Tries: 2
[RT] Error: Test 080 control_csawmgt_intel FAIL Tries: 2
[RT] Error: Test 081 control_ras_intel FAIL Tries: 2
[RT] Error: Test 085 control_CubedSphereGrid_debug_intel FAIL Tries: 2
[RT] Error: Test 086 control_wrtGauss_netcdf_parallel_debug_intel FAIL Tries: 2
[RT] Error: Test 087 control_stochy_debug_intel FAIL Tries: 2
[RT] Error: Test 088 control_lndp_debug_intel FAIL Tries: 2
[RT] Error: Test 089 control_csawmg_debug_intel FAIL Tries: 2
[RT] Error: Test 090 control_csawmgt_debug_intel FAIL Tries: 2
[RT] Error: Test 091 control_ras_debug_intel FAIL Tries: 2
[RT] Error: Test 092 control_diag_debug_intel FAIL Tries: 2
[RT] Error: Test 095 rap_control_debug_intel FAIL Tries: 2
[RT] Error: Test 096 hrrr_control_debug_intel FAIL Tries: 2
[RT] Error: Test 097 hrrr_gf_debug_intel FAIL Tries: 2
[RT] Error: Test 098 hrrr_c3_debug_intel FAIL Tries: 2
[RT] Error: Test 099 rap_unified_drag_suite_debug_intel FAIL Tries: 2
[RT] Error: Test 100 rap_diag_debug_intel FAIL Tries: 2
[RT] Error: Test 101 rap_cires_ugwp_debug_intel FAIL Tries: 2
[RT] Error: Test 102 rap_unified_ugwp_debug_intel FAIL Tries: 2
[RT] Error: Test 103 rap_lndp_debug_intel FAIL Tries: 2
[RT] Error: Test 104 rap_progcld_thompson_debug_intel FAIL Tries: 2
[RT] Error: Test 105 rap_noah_debug_intel FAIL Tries: 2
[RT] Error: Test 106 rap_sfcdiff_debug_intel FAIL Tries: 2
[RT] Error: Test 107 rap_noah_sfcdiff_cires_ugwp_debug_intel FAIL Tries: 2
[RT] Error: Test 108 rrfs_v1beta_debug_intel FAIL Tries: 2
[RT] Error: Test 109 rap_clm_lake_debug_intel FAIL Tries: 2
[RT] Error: Test 110 rap_flake_debug_intel FAIL Tries: 2
[RT] Error: Test 111 gnv1_c96_no_nest_debug_intel FAIL Tries: 2
[RT] Error: Test 112 control_wam_debug_intel FAIL Tries: 2
[RT] Error: Test 113 regional_spp_sppt_shum_skeb_dyn32_phy32_intel FAIL Tries: 2
[RT] Error: Test 114 rap_control_dyn32_phy32_intel FAIL Tries: 2
[RT] Error: Test 115 hrrr_control_dyn32_phy32_intel FAIL Tries: 2
[RT] Error: Test 116 rap_2threads_dyn32_phy32_intel FAIL Tries: 2
[RT] Error: Test 117 hrrr_control_2threads_dyn32_phy32_intel FAIL Tries: 2
[RT] Error: Test 118 hrrr_control_decomp_dyn32_phy32_intel FAIL Tries: 2
[RT] Error: Test 121 conus13km_control_intel FAIL Tries: 2
[RT] Error: Test 124 rap_control_dyn64_phy32_intel FAIL Tries: 2
[RT] Error: Test 125 rap_control_debug_dyn32_phy32_intel FAIL Tries: 2
[RT] Error: Test 126 hrrr_control_debug_dyn32_phy32_intel FAIL Tries: 2
[RT] Error: Test 127 conus13km_debug_intel FAIL Tries: 2
[RT] Error: Test 128 conus13km_debug_qr_intel FAIL Tries: 2
[RT] Error: Test 129 conus13km_debug_2threads_intel FAIL Tries: 2
[RT] Error: Test 130 conus13km_radar_tten_debug_intel FAIL Tries: 2
[RT] Error: Test 131 rap_control_dyn64_phy32_debug_intel FAIL Tries: 2
[RT] Error: Test 133 hafs_regional_atm_thompson_gfdlsf_intel FAIL Tries: 2
[RT] Error: Test 148 hafs_regional_docn_intel FAIL Tries: 2
[RT] Error: Test 149 hafs_regional_docn_oisst_intel FAIL Tries: 2
[RT] Error: Test 150 hafs_regional_datm_cdeps_intel FAIL Tries: 2
[RT] Error: Test 151 datm_cdeps_control_cfsr_intel FAIL Tries: 2
[RT] Error: Test 153 datm_cdeps_control_gefs_intel FAIL Tries: 2
[RT] Error: Test 154 datm_cdeps_iau_gefs_intel FAIL Tries: 2
[RT] Error: Test 155 datm_cdeps_stochy_gefs_intel FAIL Tries: 2
[RT] Error: Test 156 datm_cdeps_ciceC_cfsr_intel FAIL Tries: 2
[RT] Error: Test 157 datm_cdeps_bulk_cfsr_intel FAIL Tries: 2
[RT] Error: Test 158 datm_cdeps_bulk_gefs_intel FAIL Tries: 2
[RT] Error: Test 159 datm_cdeps_mx025_cfsr_intel FAIL Tries: 2
[RT] Error: Test 160 datm_cdeps_mx025_gefs_intel FAIL Tries: 2
[RT] Error: Test 161 datm_cdeps_multiple_files_cfsr_intel FAIL Tries: 2
[RT] Error: Test 162 datm_cdeps_3072x1536_cfsr_intel FAIL Tries: 2
[RT] Error: Test 163 datm_cdeps_gfs_intel FAIL Tries: 2
[RT] Error: Test 164 datm_cdeps_debug_cfsr_intel FAIL Tries: 2
[RT] Error: Test 165 datm_cdeps_control_cfsr_faster_intel FAIL Tries: 2
[RT] Error: Test 183 rap_control_gnu FAIL Tries: 2
[RT] Error: Test 184 rap_decomp_gnu FAIL Tries: 2
[RT] Error: Test 185 rap_2threads_gnu FAIL Tries: 2
[RT] Error: Test 187 rap_sfcdiff_gnu FAIL Tries: 2
[RT] Error: Test 188 rap_sfcdiff_decomp_gnu FAIL Tries: 2
[RT] Error: Test 190 hrrr_control_gnu FAIL Tries: 2
[RT] Error: Test 191 hrrr_control_noqr_gnu FAIL Tries: 2
[RT] Error: Test 192 hrrr_control_2threads_gnu FAIL Tries: 2
[RT] Error: Test 193 hrrr_control_decomp_gnu FAIL Tries: 2
[RT] Error: Test 199 rap_control_debug_gnu FAIL Tries: 2
[RT] Error: Test 200 hrrr_control_debug_gnu FAIL Tries: 2
[RT] Error: Test 201 hrrr_gf_debug_gnu FAIL Tries: 2
[RT] Error: Test 202 hrrr_c3_debug_gnu FAIL Tries: 2
[RT] Error: Test 203 rap_diag_debug_gnu FAIL Tries: 2
[RT] Error: Test 205 rap_progcld_thompson_debug_gnu FAIL Tries: 2
[RT] Error: Test 210 rap_flake_debug_gnu FAIL Tries: 2
[RT] Error: Test 211 rap_clm_lake_debug_gnu FAIL Tries: 2
[RT] Error: Test 214 rap_control_dyn32_phy32_gnu FAIL Tries: 2
[RT] Error: Test 215 hrrr_control_dyn32_phy32_gnu FAIL Tries: 2
[RT] Error: Test 216 rap_2threads_dyn32_phy32_gnu FAIL Tries: 2
[RT] Error: Test 217 hrrr_control_2threads_dyn32_phy32_gnu FAIL Tries: 2
[RT] Error: Test 218 hrrr_control_decomp_dyn32_phy32_gnu FAIL Tries: 2
[RT] Error: Test 221 conus13km_control_gnu FAIL Tries: 2
[RT] Error: Test 224 rap_control_dyn64_phy32_gnu FAIL Tries: 2
[RT] Error: Test 225 rap_control_debug_dyn32_phy32_gnu FAIL Tries: 2
[RT] Error: Test 226 hrrr_control_debug_dyn32_phy32_gnu FAIL Tries: 2
[RT] Error: Test 227 conus13km_debug_gnu FAIL Tries: 2
[RT] Error: Test 228 conus13km_debug_qr_gnu FAIL Tries: 2
[RT] Error: Test 229 conus13km_debug_2threads_gnu FAIL Tries: 2
[RT] Error: Test 230 conus13km_radar_tten_debug_gnu FAIL Tries: 2
[RT] Error: Test 231 rap_control_dyn64_phy32_debug_gnu FAIL Tries: 2
[RT] Error: Test 232 cpld_control_p8_gnu FAIL Tries: 2
[RT] Error: Test 233 cpld_control_nowave_noaero_p8_gnu FAIL Tries: 2
[RT] Error: Test 234 cpld_debug_p8_gnu FAIL Tries: 2
[RT] Error: Test 235 cpld_control_pdlib_p8_gnu FAIL Tries: 2
[RT] Error: Test 236 cpld_debug_pdlib_p8_gnu FAIL Tries: 2
[RT] Error: Test 237 datm_cdeps_control_cfsr_gnu FAIL Tries: 2
[RT] Log file shows failures.
[RT] Please obtain logs from /scratch1/BMC/gmtb/CCPP_regression_testing/NCAR_ufs-weather-model/beta/run//1714448876/20240312191015/ufs-weather-model

**Review by mkavulich — APPROVED** [review]
Looks like no unexpected failures, and a surprising number of tests passed given the old baseline and the new spack-stack version.

**Comment by grantfirl** [comment]
> 7378:001 cpld_control_p8_mixedmode_intel failed in check_result
> 7380:002 cpld_control_gfsv17_intel failed in check_result
> 7382:005 cpld_mpi_gfsv17_intel failed in check_result
> 7384:006 cpld_debug_gfsv17_intel failed in check_result
> 7386:007 cpld_control_p8_intel failed in check_result
> 7388:009 cpld_control_qr_p8_intel failed in check_result
> 7390:011 cpld_2threads_p8_intel failed in check_result
> 7392:012 cpld_decomp_p8_intel failed in check_result
> 7394:013 cpld_mpi_p8_intel failed in check_result
> 7396:014 cpld_control_ciceC_p8_intel failed in check_result
> 7398:015 cpld_control_c192_p8_intel failed in check_result
> 7400:017 cpld_bmark_p8_intel failed in check_result
> 7402:019 cpld_control_noaero_p8_intel failed in check_result
> 7404:020 cpld_control_nowave_noaero_p8_intel failed in check_result
> 7406:021 cpld_debug_p8_intel failed in check_result
> 7408:022 cpld_debug_noaero_p8_intel failed in check_result
> 7410:023 cpld_control_noaero_p8_agrid_intel failed in check_result
> 7412:024 cpld_control_c48_intel failed in check_result
> 7414:025 cpld_control_p8_faster_intel failed in check_result
> 7416:026 cpld_control_pdlib_p8_intel failed in check_result
> 7418:029 cpld_debug_pdlib_p8_intel failed in check_result
> 7420:150 datm_cdeps_control_cfsr_intel failed in check_result
> 7422:152 datm_cdeps_control_gefs_intel failed in check_result
> 7424:153 datm_cdeps_iau_gefs_intel failed in check_result
> 7426:154 datm_cdeps_stochy_gefs_intel failed in check_result
> 7428:155 datm_cdeps_ciceC_cfsr_intel failed in check_result
> 7430:156 datm_cdeps_bulk_cfsr_intel failed in check_result
> 7432:157 datm_cdeps_bulk_gefs_intel failed in check_result
> 7434:158 datm_cdeps_mx025_cfsr_intel failed in check_result
> 7436:159 datm_cdeps_mx025_gefs_intel failed in check_result
> 7438:160 datm_cdeps_multiple_files_cfsr_intel failed in check_result
> 7440:161 datm_cdeps_3072x1536_cfsr_intel failed in check_result
> 7442:162 datm_cdeps_gfs_intel failed in check_result
> 7444:163 datm_cdeps_debug_cfsr_intel failed in check_result
> 7446:164 datm_cdeps_control_cfsr_faster_intel failed in check_result
> 7448:231 cpld_control_p8_gnu failed in check_result
> 7450:232 cpld_control_nowave_noaero_p8_gnu failed in check_result
> 7452:233 cpld_debug_p8_gnu failed in check_result
> 7454:234 cpld_control_pdlib_p8_gnu failed in check_result
> 7456:235 cpld_debug_pdlib_p8_gnu failed in check_result
> 7458:236 datm_cdeps_control_cfsr_gnu failed in check_result

Ha, ya. Should we create new baselines since we've gone this far (and I updated the input for that one test)?

**Comment by mkavulich** [comment]
Machine: hera
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/CCPP_regression_testing/NCAR_ufs-weather-model/beta/run//1714448876/20240313151015/ufs-weather-model
***Baseline creation successful on hera***
[RT] Repo location: /scratch1/BMC/gmtb/CCPP_regression_testing/NCAR_ufs-weather-model/beta/run//1714448876/20240313181311/ufs-weather-model
***Regression test successful on hera!***

**Comment by grantfirl** [comment]
@mkavulich FYI, I moved the newly created baselines and updated bl_date.ncar.conf.

**Pull request merged**
