### PR TITLE
UFS-dev PR#28

### PR DESCRIPTION
**Pull request by grantfirl**
Identical to https://github.com/ufs-community/ufs-weather-model/pull/1522

Requires new baselines, but not for the CCPP code changes. The new baselines are required for https://github.com/ufs-community/ufs-weather-model/pull/1527. I think that this should only be for tests with WW3 active?

### CODE REVIEW

**Comment by grantfirl** [comment]
This contains changes from the previous PR until it is merged.

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: RT
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1191546892/20230117200017/ufs-weather-model
[RT] Error: Test cpld_control_p8 046 failed in check_result failed 
[RT] Error: Test cpld_control_p8 046 failed in run_test failed 
[RT] Error: Test cpld_debug_p8 048 failed in check_result failed 
[RT] Error: Test cpld_debug_p8 048 failed in run_test failed 
Please make changes and add the following label back: hera-gnu-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1191546892/20230117201517/ufs-weather-model
[RT] Error: Test cpld_control_p8_mixedmode 001 failed in check_result failed 
[RT] Error: Test cpld_control_p8_mixedmode 001 failed in run_test failed 
[RT] Error: Test cpld_control_gfsv17 002 failed in check_result failed 
[RT] Error: Test cpld_control_gfsv17 002 failed in run_test failed 
[RT] Error: Test cpld_control_p8 003 failed in check_result failed 
[RT] Error: Test cpld_control_p8 003 failed in run_test failed 
[RT] Error: Test cpld_2threads_p8 005 failed in check_result failed 
[RT] Error: Test cpld_2threads_p8 005 failed in run_test failed 
[RT] Error: Test cpld_esmfthreads_p8 006 failed in check_result failed 
[RT] Error: Test cpld_esmfthreads_p8 006 failed in run_test failed 
[RT] Error: Test cpld_decomp_p8 007 failed in check_result failed 
[RT] Error: Test cpld_decomp_p8 007 failed in run_test failed 
[RT] Error: Test cpld_mpi_p8 008 failed in check_result failed 
[RT] Error: Test cpld_mpi_p8 008 failed in run_test failed 
[RT] Error: Test cpld_control_ciceC_p8 009 failed in check_result failed 
[RT] Error: Test cpld_control_ciceC_p8 009 failed in run_test failed 
[RT] Error: Test cpld_control_c192_p8 010 failed in check_result failed 
[RT] Error: Test cpld_control_c192_p8 010 failed in run_test failed 
[RT] Error: Test cpld_bmark_p8 012 failed in check_result failed 
[RT] Error: Test cpld_bmark_p8 012 failed in run_test failed 
[RT] Error: Test cpld_control_noaero_p8 014 failed in check_result failed 
[RT] Error: Test cpld_control_noaero_p8 014 failed in run_test failed 
[RT] Error: Test cpld_debug_p8 016 failed in check_result failed 
[RT] Error: Test cpld_debug_p8 016 failed in run_test failed 
[RT] Error: Test cpld_debug_noaero_p8 017 failed in check_result failed 
[RT] Error: Test cpld_debug_noaero_p8 017 failed in run_test failed 
Please make changes and add the following label back: hera-intel-RT

**Comment by dustinswales** [comment]
@grantfirl Looks like these tests are failing, as expected, when comparing to the mediator restart files:
[Dustin.Swales@hfe07 ufs-weather-model]$ grep "NOT OK" /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1191546892/20230117201517/ufs-weather-model/tests/RegressionTests_hera.intel.log
 Comparing RESTART/ufs.cpld.cpl.r.2021-03-23-21600.nc ............ALT CHECK......NOT OK
 Comparing RESTART/ufs.cpld.cpl.r.2021-03-23-21600.nc ............ALT CHECK......NOT OK
 Comparing RESTART/ufs.cpld.cpl.r.2021-03-23-21600.nc ............ALT CHECK......NOT OK
 Comparing RESTART/ufs.cpld.cpl.r.2021-03-23-21600.nc ............ALT CHECK......NOT OK
 Comparing RESTART/ufs.cpld.cpl.r.2021-03-23-21600.nc ............ALT CHECK......NOT OK
 Comparing RESTART/ufs.cpld.cpl.r.2021-03-23-21600.nc ............ALT CHECK......NOT OK
 Comparing RESTART/ufs.cpld.cpl.r.2021-03-23-21600.nc ............ALT CHECK......NOT OK
 Comparing RESTART/ufs.cpld.cpl.r.2021-03-23-21600.nc ............ALT CHECK......NOT OK
 Comparing RESTART/ufs.cpld.cpl.r.2021-03-23-43200.nc ............ALT CHECK......NOT OK
 Comparing RESTART/ufs.cpld.cpl.r.2013-04-01-21600.nc ............ALT CHECK......NOT OK
 Comparing RESTART/ufs.cpld.cpl.r.2021-03-23-21600.nc ............ALT CHECK......NOT OK
 Comparing RESTART/ufs.cpld.cpl.r.2021-03-22-32400.nc ............ALT CHECK......NOT OK
 Comparing RESTART/ufs.cpld.cpl.r.2021-03-22-32400.nc ............ALT CHECK......NOT OK
 
 Cheyenne is down this week for maintenance, should we wait? or skip?

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1191546892/20230119053014/ufs-weather-model
[BL] ERROR: Baseline location exists before creation:
/scratch1/BMC/gmtb/RT/NCAR/main-20220109/GNU
Please make changes and add the following label back: hera-gnu-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1191546892/20230119053055/ufs-weather-model
Please make changes and add the following label back: hera-intel-BL

**Comment by dustinswales** [comment]
@grantfirl Can you update the BL_DATE? (I see we made the classic mistake with the first BL_DATE of the year. Let's do 2023 for this one)

**Comment by grantfirl** [comment]
> @grantfirl Looks like these tests are failing, as expected, when comparing to the mediator restart files: [Dustin.Swales@hfe07 ufs-weather-model]$ grep "NOT OK" /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1191546892/20230117201517/ufs-weather-model/tests/RegressionTests_hera.intel.log Comparing RESTART/ufs.cpld.cpl.r.2021-03-23-21600.nc ............ALT CHECK......NOT OK Comparing RESTART/ufs.cpld.cpl.r.2021-03-23-21600.nc ............ALT CHECK......NOT OK Comparing RESTART/ufs.cpld.cpl.r.2021-03-23-21600.nc ............ALT CHECK......NOT OK Comparing RESTART/ufs.cpld.cpl.r.2021-03-23-21600.nc ............ALT CHECK......NOT OK Comparing RESTART/ufs.cpld.cpl.r.2021-03-23-21600.nc ............ALT CHECK......NOT OK Comparing RESTART/ufs.cpld.cpl.r.2021-03-23-21600.nc ............ALT CHECK......NOT OK Comparing RESTART/ufs.cpld.cpl.r.2021-03-23-21600.nc ............ALT CHECK......NOT OK Comparing RESTART/ufs.cpld.cpl.r.2021-03-23-21600.nc ............ALT CHECK......NOT OK Comparing RESTART/ufs.cpld.cpl.r.2021-03-23-43200.nc ............ALT CHECK......NOT OK Comparing RESTART/ufs.cpld.cpl.r.2013-04-01-21600.nc ............ALT CHECK......NOT OK Comparing RESTART/ufs.cpld.cpl.r.2021-03-23-21600.nc ............ALT CHECK......NOT OK Comparing RESTART/ufs.cpld.cpl.r.2021-03-22-32400.nc ............ALT CHECK......NOT OK Comparing RESTART/ufs.cpld.cpl.r.2021-03-22-32400.nc ............ALT CHECK......NOT OK
> 
> Cheyenne is down this week for maintenance, should we wait to run? or skip?

I would say skip it because it has already been tested on Cheyenne in the ufs/dev branch. Hera should be good enough for our "verification" RTs for the main branch this time around.

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1191546892/20230119184515/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1191546892/20230119200530/ufs-weather-model
Please make changes and add the following label back: hera-gnu-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1191546892/20230119190013/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1191546892/20230119202728/ufs-weather-model
Please make changes and add the following label back: hera-intel-BL

**Review by dustinswales — APPROVED** [review]

**Pull request merged**
