### PR TITLE
UFS-dev PR#35

### PR DESCRIPTION
**Pull request by dustinswales**
Identical to [ufs-community PR#1582](https://github.com/ufs-community/ufs-weather-model/pull/1582).

### CODE REVIEW

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1235555521/20230209113006/ufs-weather-model
[RT] Error: Test control_p8 004 failed in check_result failed 
[RT] Error: Test control_p8 004 failed in run_test failed 
[RT] Error: Test cpld_control_p8 046 failed in check_result failed 
[RT] Error: Test cpld_control_p8 046 failed in run_test failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 047 failed in check_result failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 047 failed in run_test failed 
[RT] Error: Test cpld_debug_p8 048 failed in check_result failed 
[RT] Error: Test cpld_debug_p8 048 failed in run_test failed 
Please make changes and add the following label back: cheyenne-gnu-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1235555521/20230209184515/ufs-weather-model
[RT] Error: Test cpld_control_p8_mixedmode 001 failed in check_result failed 
[RT] Error: Test cpld_control_p8_mixedmode 001 failed in run_test failed 
[RT] Error: Test cpld_control_gfsv17 002 failed in check_result failed 
[RT] Error: Test cpld_control_gfsv17 002 failed in run_test failed 
[RT] Error: Test cpld_control_p8 003 failed in check_result failed 
[RT] Error: Test cpld_control_p8 003 failed in run_test failed 
[RT] Error: Test cpld_2threads_p8 005 failed in check_result failed 
[RT] Error: Test cpld_2threads_p8 005 failed in run_test failed 
[RT] Error: Test cpld_esmfthreads_p8 006 failed in check_result failed 
[RT] Error: Test cpld_esmfthreads_p8 006 failed in run_test failed 
[RT] Error: Test cpld_decomp_p8 007 failed in check_result failed 
[RT] Error: Test cpld_decomp_p8 007 failed in run_test failed 
[RT] Error: Test cpld_mpi_p8 008 failed in check_result failed 
[RT] Error: Test cpld_mpi_p8 008 failed in run_test failed 
[RT] Error: Test cpld_control_ciceC_p8 009 failed in check_result failed 
[RT] Error: Test cpld_control_ciceC_p8 009 failed in run_test failed 
[RT] Error: Test cpld_control_c192_p8 010 failed in check_result failed 
[RT] Error: Test cpld_control_c192_p8 010 failed in run_test failed 
[RT] Error: Test cpld_bmark_p8 012 failed in check_result failed 
[RT] Error: Test cpld_bmark_p8 012 failed in run_test failed 
[RT] Error: Test cpld_control_noaero_p8 014 failed in check_result failed 
[RT] Error: Test cpld_control_noaero_p8 014 failed in run_test failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 015 failed in check_result failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 015 failed in run_test failed 
[RT] Error: Test cpld_debug_p8 016 failed in check_result failed 
[RT] Error: Test cpld_debug_p8 016 failed in run_test failed 
[RT] Error: Test cpld_debug_noaero_p8 017 failed in check_result failed 
[RT] Error: Test cpld_debug_noaero_p8 017 failed in run_test failed 
[RT] Error: Test cpld_control_noaero_p8_agrid 018 failed in check_result failed 
[RT] Error: Test cpld_control_noaero_p8_agrid 018 failed in run_test failed 
[RT] Error: Test cpld_control_c48 019 failed in check_result failed 
[RT] Error: Test cpld_control_c48 019 failed in run_test failed 
[RT] Error: Test cpld_warmstart_c48 020 failed in check_result failed 
[RT] Error: Test cpld_warmstart_c48 020 failed in run_test failed 
[RT] Error: Test control_p8 035 failed in check_result failed 
[RT] Error: Test control_p8 035 failed in run_test failed 
[RT] Error: Test control_p8_lndp 036 failed in check_result failed 
[RT] Error: Test control_p8_lndp 036 failed in run_test failed 
[RT] Error: Test control_decomp_p8 038 failed in check_result failed 
[RT] Error: Test control_decomp_p8 038 failed in run_test failed 
[RT] Error: Test control_2threads_p8 039 failed in check_result failed 
[RT] Error: Test control_2threads_p8 039 failed in run_test failed 
[RT] Error: Test merra2_thompson 041 failed in check_result failed 
[RT] Error: Test merra2_thompson 041 failed in run_test failed 
[RT] Error: Test rap_rrtmgp 051 failed in check_result failed 
[RT] Error: Test rap_rrtmgp 051 failed in run_test failed 
[RT] Error: Test hafs_regional_atm_thompson_gfdlsf 115 failed in check_result failed 
[RT] Error: Test hafs_regional_atm_thompson_gfdlsf 115 failed in run_test failed 
[RT] Error: Test control_p8_atmlnd_sbs 147 failed in check_result failed 
[RT] Error: Test control_p8_atmlnd_sbs 147 failed in run_test failed 
[RT] Error: Test atmaero_control_p8 149 failed in check_result failed 
[RT] Error: Test atmaero_control_p8 149 failed in run_test failed 
[RT] Error: Test atmaero_control_p8_rad 150 failed in check_result failed 
[RT] Error: Test atmaero_control_p8_rad 150 failed in run_test failed 
[RT] Error: Test atmaero_control_p8_rad_micro 151 failed in check_result failed 
[RT] Error: Test atmaero_control_p8_rad_micro 151 failed in run_test failed 
Please make changes and add the following label back: hera-intel-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: RT
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1235555521/20230209183009/ufs-weather-model
[RT] Error: Test control_p8 004 failed in check_result failed 
[RT] Error: Test control_p8 004 failed in run_test failed 
[RT] Error: Test cpld_control_p8 046 failed in check_result failed 
[RT] Error: Test cpld_control_p8 046 failed in run_test failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 047 failed in check_result failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 047 failed in run_test failed 
[RT] Error: Test cpld_debug_p8 048 failed in check_result failed 
[RT] Error: Test cpld_debug_p8 048 failed in run_test failed 
Please make changes and add the following label back: hera-gnu-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1235555521/20230209114507/ufs-weather-model
[RT] Error: Test cpld_control_p8_mixedmode 001 failed in check_result failed 
[RT] Error: Test cpld_control_p8_mixedmode 001 failed in run_test failed 
[RT] Error: Test cpld_control_gfsv17 002 failed in check_result failed 
[RT] Error: Test cpld_control_gfsv17 002 failed in run_test failed 
[RT] Error: Test cpld_control_p8 003 failed in check_result failed 
[RT] Error: Test cpld_control_p8 003 failed in run_test failed 
[RT] Error: Test cpld_2threads_p8 005 failed in check_result failed 
[RT] Error: Test cpld_2threads_p8 005 failed in run_test failed 
[RT] Error: Test cpld_esmfthreads_p8 006 failed in check_result failed 
[RT] Error: Test cpld_esmfthreads_p8 006 failed in run_test failed 
[RT] Error: Test cpld_decomp_p8 007 failed in check_result failed 
[RT] Error: Test cpld_decomp_p8 007 failed in run_test failed 
[RT] Error: Test cpld_mpi_p8 008 failed in check_result failed 
[RT] Error: Test cpld_mpi_p8 008 failed in run_test failed 
[RT] Error: Test cpld_control_ciceC_p8 009 failed in check_result failed 
[RT] Error: Test cpld_control_ciceC_p8 009 failed in run_test failed 
[RT] Error: Test cpld_control_c192_p8 010 failed in run_test failed 
[RT] Error: Test cpld_control_noaero_p8 012 failed in check_result failed 
[RT] Error: Test cpld_control_noaero_p8 012 failed in run_test failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 013 failed in check_result failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 013 failed in run_test failed 
[RT] Error: Test cpld_debug_p8 014 failed in check_result failed 
[RT] Error: Test cpld_debug_p8 014 failed in run_test failed 
[RT] Error: Test cpld_debug_noaero_p8 015 failed in check_result failed 
[RT] Error: Test cpld_debug_noaero_p8 015 failed in run_test failed 
[RT] Error: Test cpld_control_noaero_p8_agrid 016 failed in check_result failed 
[RT] Error: Test cpld_control_noaero_p8_agrid 016 failed in run_test failed 
[RT] Error: Test cpld_control_c48 017 failed in check_result failed 
[RT] Error: Test cpld_control_c48 017 failed in run_test failed 
[RT] Error: Test cpld_warmstart_c48 018 failed in check_result failed 
[RT] Error: Test cpld_warmstart_c48 018 failed in run_test failed 
[RT] Error: Test control_p8 032 failed in check_result failed 
[RT] Error: Test control_p8 032 failed in run_test failed 
[RT] Error: Test control_p8_lndp 033 failed in check_result failed 
[RT] Error: Test control_p8_lndp 033 failed in run_test failed 
[RT] Error: Test control_decomp_p8 035 failed in check_result failed 
[RT] Error: Test control_decomp_p8 035 failed in run_test failed 
[RT] Error: Test control_2threads_p8 036 failed in check_result failed 
[RT] Error: Test control_2threads_p8 036 failed in run_test failed 
[RT] Error: Test merra2_thompson 038 failed in check_result failed 
[RT] Error: Test merra2_thompson 038 failed in run_test failed 
[RT] Error: Test hafs_regional_atm_thompson_gfdlsf 112 failed in run_test failed 
[RT] Error: Test hafs_regional_atm_ocn_wav 115 failed in run_test failed 
[RT] Error: Test hafs_global_multiple_4nests_atm 119 failed in run_test failed 
[RT] Error: Test hafs_regional_storm_following_1nest_atm_ocn_wav 123 failed in run_test failed 
[RT] Error: Test datm_cdeps_mx025_gefs 137 failed in run_test failed 
[RT] Error: Test control_p8_atmlnd_sbs 144 failed in run_test failed 
[RT] Error: Test atmaero_control_p8 146 failed in run_test failed 
[RT] Error: Test atmaero_control_p8_rad 147 failed in run_test failed 
[RT] Error: Test atmaero_control_p8_rad_micro 148 failed in check_result failed 
[RT] Error: Test atmaero_control_p8_rad_micro 148 failed in run_test failed 
[RT] Error: Test regional_atmaq 149 failed in run_test failed 
[RT] Error: Test regional_atmaq_debug 150 failed in run_test failed 
Please make changes and add the following label back: cheyenne-intel-RT

**Comment by dustinswales** [comment]
@grantfirl Expected tests do not pass. Creating new baselines.

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1235555521/20230209153007/ufs-weather-model
Please make changes and add the following label back: cheyenne-intel-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1235555521/20230209151506/ufs-weather-model
Please make changes and add the following label back: cheyenne-gnu-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1235555521/20230209221511/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1235555521/20230209230155/ufs-weather-model
[RT] Error: Test cpld_control_p8 046 failed in run_test failed 
Please make changes and add the following label back: hera-gnu-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1235555521/20230209223009/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1235555521/20230210005757/ufs-weather-model
Please make changes and add the following label back: hera-intel-BL

**Comment by dustinswales** [comment]
Needed to clean up space on Cheyenne and Hera.

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1235555521/20230223174509/ufs-weather-model
[BL] ERROR: Baseline location exists before creation:
/scratch1/BMC/gmtb/RT/NCAR/main-20230209/GNU
Please make changes and add the following label back: hera-gnu-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1235555521/20230223104508/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1235555521/20230223111503/ufs-weather-model
Please make changes and add the following label back: cheyenne-gnu-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1235555521/20230223180012/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1235555521/20230223184221/ufs-weather-model
Please make changes and add the following label back: hera-gnu-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1235555521/20230223110011/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1235555521/20230223121304/ufs-weather-model
Please make changes and add the following label back: cheyenne-intel-BL

**Comment by dustinswales** [comment]
@grantfirl All tests passed. 
Can you approve this? (and [this](https://github.com/NCAR/fv3atm/pull/83) and [this](https://github.com/NCAR/ccpp-physics/pull/998)

**Review by grantfirl — APPROVED** [review]

**Pull request merged**
