### PR TITLE
dtc/develop: merge emc/develop 2020/03/11 (after Moorthi's commit, before dycore OMP bugfix)

### PR DESCRIPTION
**Pull request by climbfuji**
See original PR https://github.com/ufs-community/ufs-weather-model/pull/72.

Associated PRs:
https://github.com/NCAR/ccpp-physics/pull/406
https://github.com/NCAR/fv3atm/pull/29
https://github.com/NCAR/ufs-weather-model/pull/26

For regression testing info, see below.

### CODE REVIEW

**Comment by climbfuji** [comment]
Regression testing IPD PROD against official EMC baseline on hera.intel: all tests pass

[rt_ipd_prod_only.log](https://github.com/NCAR/ufs-weather-model/files/4324837/rt_ipd_prod_only.log)
[RegressionTests_hera.intel.log](https://github.com/NCAR/ufs-weather-model/files/4324838/RegressionTests_hera.intel.log)
[Compile_hera.intel.log](https://github.com/NCAR/ufs-weather-model/files/4324839/Compile_hera.intel.log)

**Comment by climbfuji** [comment]
Regression testing for IPD and CCPP on hera.intel:

(1) Create new DTC baseline for IPD PROD, IPD REPRO, CCPP PROD: all tests pass

[Compile_hera.intel.log](https://github.com/NCAR/ufs-weather-model/files/4324840/Compile_hera.intel.log)
[RegressionTests_hera.intel.log](https://github.com/NCAR/ufs-weather-model/files/4324842/RegressionTests_hera.intel.log)
[rt_full_create_ecflow_after-moorthi-before-dycore-pr7.log](https://github.com/NCAR/ufs-weather-model/files/4324843/rt_full_create_ecflow_after-moorthi-before-dycore-pr7.log)

(2) Verify against new DTC baseline (after rsync to final destination) for IPD PROD, IPD REPRO, CCPP REPRO, CCPP PROD: all tests pass

[Compile_hera.intel.log](https://github.com/NCAR/ufs-weather-model/files/4324846/Compile_hera.intel.log)
[RegressionTests_hera.intel.log](https://github.com/NCAR/ufs-weather-model/files/4324848/RegressionTests_hera.intel.log)
[rt_full_verify_ecflow_after-moorthi-before-dycore-pr7.log](https://github.com/NCAR/ufs-weather-model/files/4324849/rt_full_verify_ecflow_after-moorthi-before-dycore-pr7.log)

**Comment by climbfuji** [comment]
Regression testing using rt_ccpp_dtc.conf on hera.intel

(1) Create (temporary) baseline: **regression tests still running**

(2) Verify against (temporary) baseline: **not yet started**

**Comment by climbfuji** [comment]
@junwang-noaa @dusanjovic-noaa for your information, step 1 to update dtc/develop from master (CCPP) / develop (EMC). Turning on all previous CCPP regression tests (and adding the coupled wave-atm tests, but not yet Moorthi's new ras tests), all regression tests pass.

Next step will be to merge the dycore PR, Shan's changes and various other tiny PRs. But at least we know that at this stage, all IPD GFSv16 physics updates are correctly implemented in CCPP.

**Comment by junwang-noaa** [comment]
Great! Thanks for the update, it's good to know the  previous CCPP
regression tests pass as expected..

**Pull request merged**
