### PR TITLE
UFS-dev PR#97

### PR DESCRIPTION
**Pull request by grantfirl**
Identical to https://github.com/ufs-community/ufs-weather-model/pull/1891 (no BL changes)

Contains changes from https://github.com/ufs-community/ufs-weather-model/pull/1890 (no BL changes)

### CODE REVIEW

**Comment by grantfirl** [comment]
@mkavulich Can you move
/scratch1/BMC/gmtb/CCPP_regression_testing/NCAR_ufs-weather-model/new to /scratch1/BMC/gmtb/CCPP_regression_testing/NCAR_ufs-weather-model/baselines/main-20140117 before starting the RT label?

**Comment by mkavulich** [comment]
@grantfirl moved baseline to /scratch1/BMC/gmtb/CCPP_regression_testing/NCAR_ufs-weather-model/baselines/main-**20240117**. Looks like the baseline date is correct in this branch so I'll start the test

**Comment by grantfirl** [comment]
@mkavulich This is ready to merge once you approve this and https://github.com/NCAR/fv3atm/pull/106 and https://github.com/NCAR/ccpp-physics/pull/1037.

**Review by mkavulich — APPROVED** [review]
Looks good once submodule is updated

**Pull request merged**
