### PR TITLE
UFS-dev PR#10

### PR DESCRIPTION
**Pull request by grantfirl**
Identical to https://github.com/ufs-community/ufs-weather-model/pull/1443
Also contains https://github.com/ufs-community/ufs-weather-model/pull/1454

### CODE REVIEW

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1109888742/20221103200510/ufs-weather-model
[RT] Error: Test cpld_control_p8 049 failed in check_result failed 
[RT] Error: Test cpld_control_p8 049 failed in run_test failed 
Please make changes and add the following label back: cheyenne-gnu-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: RT
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1109888742/20221104020749/ufs-weather-model
[RT] Error: Test cpld_control_p8 049 failed in check_result failed 
[RT] Error: Test cpld_control_p8 049 failed in run_test failed 
Please make changes and add the following label back: hera-gnu-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1109888742/20221103204330/ufs-weather-model
[RT] Error: Test cpld_control_p8 001 failed in check_result failed 
[RT] Error: Test cpld_control_p8 001 failed in run_test failed 
[RT] Error: Test cpld_2threads_p8 003 failed in check_result failed 
[RT] Error: Test cpld_2threads_p8 003 failed in run_test failed 
[RT] Error: Test cpld_esmfthreads_p8 004 failed in check_result failed 
[RT] Error: Test cpld_esmfthreads_p8 004 failed in run_test failed 
[RT] Error: Test cpld_decomp_p8 005 failed in check_result failed 
[RT] Error: Test cpld_decomp_p8 005 failed in run_test failed 
[RT] Error: Test cpld_mpi_p8 006 failed in check_result failed 
[RT] Error: Test cpld_mpi_p8 006 failed in run_test failed 
[RT] Error: Test cpld_control_ciceC_p8 007 failed in check_result failed 
[RT] Error: Test cpld_control_ciceC_p8 007 failed in run_test failed 
[RT] Error: Test cpld_control_c192_p8 008 failed in check_result failed 
[RT] Error: Test cpld_control_c192_p8 008 failed in run_test failed 
[RT] Error: Test cpld_control_noaero_p8 010 failed in check_result failed 
[RT] Error: Test cpld_control_noaero_p8 010 failed in run_test failed 
[RT] Error: Test datm_cdeps_lnd_gswp3 150 failed in run_test failed 
[RT] Error: Test control_p8_atmlnd_sbs 152 failed in check_result failed 
[RT] Error: Test control_p8_atmlnd_sbs 152 failed in run_test failed 
Please make changes and add the following label back: cheyenne-intel-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1109888742/20221104032116/ufs-weather-model
[RT] Error: Test cpld_control_p8 001 failed in check_result failed 
[RT] Error: Test cpld_control_p8 001 failed in run_test failed 
[RT] Error: Test cpld_2threads_p8 003 failed in check_result failed 
[RT] Error: Test cpld_2threads_p8 003 failed in run_test failed 
[RT] Error: Test cpld_esmfthreads_p8 004 failed in check_result failed 
[RT] Error: Test cpld_esmfthreads_p8 004 failed in run_test failed 
[RT] Error: Test cpld_decomp_p8 005 failed in check_result failed 
[RT] Error: Test cpld_decomp_p8 005 failed in run_test failed 
[RT] Error: Test cpld_mpi_p8 006 failed in check_result failed 
[RT] Error: Test cpld_mpi_p8 006 failed in run_test failed 
[RT] Error: Test cpld_control_ciceC_p8 007 failed in check_result failed 
[RT] Error: Test cpld_control_ciceC_p8 007 failed in run_test failed 
[RT] Error: Test cpld_control_c192_p8 008 failed in check_result failed 
[RT] Error: Test cpld_control_c192_p8 008 failed in run_test failed 
[RT] Error: Test cpld_control_noaero_p8 013 failed in check_result failed 
[RT] Error: Test cpld_control_noaero_p8 013 failed in run_test failed 
[RT] Error: Test datm_cdeps_lnd_gswp3 153 failed in run_test failed 
[RT] Error: Test control_p8_atmlnd_sbs 155 failed in check_result failed 
[RT] Error: Test control_p8_atmlnd_sbs 155 failed in run_test failed 
Please make changes and add the following label back: hera-intel-RT

**Comment by dustinswales** [comment]
@grantfirl Looks like all tests passed except the new tests introduced by [#1443](https://github.com/ufs-community/ufs-weather-model/pull/1443) and the p8 tests expected to fail with [#1454](https://github.com/ufs-community/ufs-weather-model/pull/1454).
Can you update the BL_DATE to 11042022?

**Comment by grantfirl** [comment]
> @grantfirl Looks like all tests passed except the new tests introduced by [#1443](https://github.com/ufs-community/ufs-weather-model/pull/1443) and the p8 tests expected to fail with [#1454](https://github.com/ufs-community/ufs-weather-model/pull/1454). Can you update the BL_DATE to 11042022?

@dustinswales Done

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1109888742/20221104095401/ufs-weather-model
[BL] Error: Test datm_cdeps_lnd_gswp3 110 failed in run_test failed 
Please make changes and add the following label back: cheyenne-intel-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1109888742/20221104164055/ufs-weather-model
[BL] Error: Test datm_cdeps_lnd_gswp3 112 failed in run_test failed 
Please make changes and add the following label back: hera-intel-BL

**Comment by dustinswales** [comment]
@grantfirl I needed to update the input data for this PR. Can you change [the input data date to match baseline date](https://github.com/grantfirl/ufs-weather-model/blob/ufs-dev-PR10/tests/rt.ncar.sh#L451)

**Comment by grantfirl** [comment]
> @grantfirl I needed to update the input data for this PR. Can you change [the input data date to match baseline date](https://github.com/grantfirl/ufs-weather-model/blob/ufs-dev-PR10/tests/rt.ncar.sh#L451)

Done @dustinswales

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1109888742/20221107201426/ufs-weather-model
[BL] Error: Test control_c384gdas 021 failed in run_test failed 
[BL] Error: Test regional_control 031 failed in run_test failed 
[BL] Error: Test regional_noquilt 032 failed in run_test failed 
[BL] Error: Test regional_netcdf_parallel 033 failed in run_test failed 
[BL] Error: Test regional_3km 034 failed in run_test failed 
[BL] Error: Test rrfs_conus13km_hrrr_warm 043 failed in run_test failed 
[BL] Error: Test rrfs_smoke_conus13km_hrrr_warm 044 failed in run_test failed 
[BL] Error: Test rrfs_conus13km_radar_tten_warm 045 failed in run_test failed 
[BL] Error: Test control_wam 049 failed in run_test failed 
[BL] Error: Test rrfs_conus13km_hrrr_warm_debug 050 failed in run_test failed 
[BL] Error: Test rrfs_conus13km_radar_tten_warm_debug 051 failed in run_test failed 
[BL] Error: Test regional_debug 062 failed in run_test failed 
[BL] Error: Test control_wam_debug 075 failed in run_test failed 
Please make changes and add the following label back: hera-intel-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1109888742/20221107231937/ufs-weather-model
[BL] Error: Test datm_cdeps_lnd_gswp3 112 failed in run_test failed 
Please make changes and add the following label back: hera-intel-BL

**Comment by dustinswales** [comment]
@grantfirl All tests are complete. You can go ahead and update the submodules and merge subsequent PRs.

**Review by dustinswales — APPROVED** [review]

**Pull request merged**
