### PR TITLE
dtc/develop: merge gsd/develop, allow environment variable NEMS_MACHINE to overwrite (or set) MACHINE_ID

### PR DESCRIPTION
**Pull request by climbfuji**
This PR merges the GSD physics updates from the NEMSfv3gfs gsd/develop branch into the ufs-weather-model dtc/develop branch. It also contains the code changes from https://github.com/NCAR/ufs-weather-model/pull/4, which allow the user to set `NEMS_MACHINE` to overwrite (or set, if the logic in detect_machine.sh fails) the `MACHINE_ID` in the `rt.sh` regression testing scripts.

### CODE REVIEW

**Comment by climbfuji** [comment]
Associated PRs:

https://github.com/NCAR/ufs-weather-model/pull/8
https://github.com/NCAR/fv3atm/pull/10
https://github.com/NCAR/ccpp-physics/pull/359
https://github.com/NCAR/ccpp-framework/pull/242

For regression testing, see below.

**Comment by climbfuji** [comment]
NEMSCompsetRun against official baseline on hera/intel: all pass.

[NEMSCompsetRun.log](https://github.com/NCAR/ufs-weather-model/files/3893634/NEMSCompsetRun.log)

**Comment by climbfuji** [comment]
CAPS tests (rt_ccpp_caps.conf) against baseline created with current dtc/develop branch on hera/intel: all pass

[rt_ccpp_caps_verify.log](https://github.com/NCAR/ufs-weather-model/files/3893637/rt_ccpp_caps_verify.log)

**Comment by climbfuji** [comment]
DTC tests (rt_ccpp_dtc.conf) against baseline created with current dtc/develop branch on hera/intel: all tests pass except fv3_ccpp_gsd - this is OK, because the gsd/develop physics updates change the answer of the GSD suite.

[rt_ccpp_dtc_verify.log](https://github.com/NCAR/ufs-weather-model/files/3894895/rt_ccpp_dtc_verify.log)

**Comment by climbfuji** [comment]
GSD tests (rt_ccpp_gsd.conf) against **new** baseline created with the code proposed here on hera/intel: create (CCPP static only) all tests pass, verify (CCPP static and dynamic) all tests pass except CCPP dynamic fv3_ccpp_gsd_drag_suite and fv3_ccpp_gsd_sar. This is ok for the PR to go ahead.

[rt_ccpp_gsd_create.log](https://github.com/NCAR/ufs-weather-model/files/3897919/rt_ccpp_gsd_create.log)
[rt_ccpp_gsd_verify.log](https://github.com/NCAR/ufs-weather-model/files/3897920/rt_ccpp_gsd_verify.log)

**Comment by climbfuji** [comment]
Full regression tests (rt.conf) against official baseline on hera/intel: all tests pass except fv3_ccpp_gsd - this is OK, because the gsd/develop physics updates change the answer of the GSD suite.

[rt_full.log](https://github.com/NCAR/ufs-weather-model/files/3897925/rt_full.log)

**Comment by llpcarson** [comment]
Did you need to adjust the wallclock time for any of these tests, with the smaller timestep?  Just curious!

**Comment by climbfuji** [comment]
> Did you need to adjust the wallclock time for any of these tests, with the smaller timestep? Just curious!

Thanks for approving the PRs! No, they still fit within the time window. The only test is the GSD SAR test that may run over the walltime in dynamic mode (it finishes in about 28mins in static mode).

**Pull request merged**
