### PR TITLE
UFS-dev PR#102

### PR DESCRIPTION
**Pull request by grantfirl**
Identical to https://github.com/ufs-community/ufs-weather-model/pull/1893 (BL changes expected in "All FV3 tests.")

Contains:
 - https://github.com/ufs-community/ufs-weather-model/pull/1887 (no BL changes) (transfer changes to machine files and rt.sh)
 - https://github.com/ufs-community/ufs-weather-model/pull/1733 (no BL changes) (add hercules support via machine file)
 - https://github.com/ufs-community/ufs-weather-model/pull/1902 (BL changes expected)
 - https://github.com/ufs-community/ufs-weather-model/pull/1903 (BL changes expected)
 - https://github.com/ufs-community/ufs-weather-model/pull/1910 (no BL changes)

### CODE REVIEW

**Comment by grantfirl** [comment]
Expected failed tests for 1902: 

All coupled and one DATM tests which use CICE fail.

139:Test 001 cpld_control_p8_mixedmode_intel FAIL Tries: 2
210:Test 002 cpld_control_gfsv17_intel FAIL Tries: 2
282:Test 003 cpld_control_p8_intel FAIL Tries: 2
354:Test 005 cpld_control_qr_p8_intel FAIL Tries: 2
414:Test 007 cpld_2threads_p8_intel FAIL Tries: 2
474:Test 008 cpld_decomp_p8_intel FAIL Tries: 2
534:Test 009 cpld_mpi_p8_intel FAIL Tries: 2
606:Test 010 cpld_control_ciceC_p8_intel FAIL Tries: 2
666:Test 011 cpld_control_c192_p8_intel FAIL Tries: 2
721:Test 013 cpld_bmark_p8_intel FAIL Tries: 2
792:Test 015 cpld_control_noaero_p8_intel FAIL Tries: 2
861:Test 016 cpld_control_nowave_noaero_p8_intel FAIL Tries: 2
921:Test 017 cpld_debug_p8_intel FAIL Tries: 2
980:Test 018 cpld_debug_noaero_p8_intel FAIL Tries: 2
1049:Test 019 cpld_control_noaero_p8_agrid_intel FAIL Tries: 2
1106:Test 020 cpld_control_c48_intel FAIL Tries: 2
1178:Test 021 cpld_control_p8_faster_intel FAIL Tries: 2
1249:Test 022 cpld_control_pdlib_p8_intel FAIL Tries: 2
1308:Test 025 cpld_debug_pdlib_p8_intel FAIL Tries: 2
5023:Test 164 datm_cdeps_gfs_intel FAIL Tries: 2
7213:Test 231 cpld_control_p8_gnu FAIL Tries: 2
7282:Test 232 cpld_control_nowave_noaero_p8_gnu FAIL Tries: 2
7342:Test 233 cpld_debug_p8_gnu FAIL Tries: 2
7413:Test 234 cpld_control_pdlib_p8_gnu FAIL Tries: 2
7472:Test 235 cpld_debug_pdlib_p8_gnu FAIL Tries: 2

**Comment by grantfirl** [comment]
Expected failures for 1903:

atmaero_control_p8
atmaero_control_p8_rad
atmaero_control_p8_rad_micro
atmwav_control_noaero_p8
control_atmwav
control_c384gdas
control_c48
control_p8_faster
control_p8
control_p8_mynn
control_p8_rrtmgp
conus13km_control
cpld_bmark_p8
cpld_control_c192_p8
cpld_control_c48
cpld_control_c96_noaero_p8
cpld_control_ciceC_p8
cpld_control_gfsv17
cpld_control_noaero_p8_agrid
cpld_control_noaero_p8
cpld_control_p8_faster
cpld_control_p8
cpld_control_p8_mixedmode
cpld_control_pdlib_p8
cpld_debug_noaero_p8
cpld_debug_p8
cpld_debug_pdlib_p8
hafs_global_1nest_atm
hafs_global_multiple_4nests_atm
hafs_regional_1nest_atm
hafs_regional_storm_following_1nest_atm
hrrr_c3
hrrr_control_dyn32_phy32
hrrr_control
hrrr_gf
merra2_thompson
rap_control_dyn32_phy32
rap_control_dyn64_phy32
rap_control
rap_sfcdiff
regional_atmaq_debug
regional_atmaq_faster
regional_atmaq
rrfs_v1beta

**Comment by grantfirl** [comment]
@mkavulich Ready to run RT labels. Most (all?) RTs should fail.

**Comment by mkavulich** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
[RT] Repo location: /scratch1/BMC/gmtb/CCPP_regression_testing/NCAR_ufs-weather-model//run//1626516739/20240125220515/ufs-weather-model
[RT] Error: Test 001 cpld_control_p8_mixedmode_intel FAIL Tries: 2
[RT] Error: Test 002 cpld_control_gfsv17_intel FAIL Tries: 2
[RT] Error: Test 003 cpld_control_p8_intel FAIL Tries: 2
[RT] Error: Test 005 cpld_control_qr_p8_intel FAIL Tries: 2
[RT] Error: Test 007 cpld_2threads_p8_intel FAIL Tries: 2
[RT] Error: Test 008 cpld_decomp_p8_intel FAIL Tries: 2
[RT] Error: Test 009 cpld_mpi_p8_intel FAIL Tries: 2
[RT] Error: Test 010 cpld_control_ciceC_p8_intel FAIL Tries: 2
[RT] Error: Test 011 cpld_control_c192_p8_intel FAIL Tries: 2
[RT] Error: Test 013 cpld_bmark_p8_intel FAIL Tries: 2
[RT] Error: Test 015 cpld_control_noaero_p8_intel FAIL Tries: 2
[RT] Error: Test 016 cpld_control_nowave_noaero_p8_intel FAIL Tries: 2
[RT] Error: Test 017 cpld_debug_p8_intel FAIL Tries: 2
[RT] Error: Test 018 cpld_debug_noaero_p8_intel FAIL Tries: 2
[RT] Error: Test 019 cpld_control_noaero_p8_agrid_intel FAIL Tries: 2
[RT] Error: Test 020 cpld_control_c48_intel FAIL Tries: 2
[RT] Error: Test 021 cpld_control_p8_faster_intel FAIL Tries: 2
[RT] Error: Test 022 cpld_control_pdlib_p8_intel FAIL Tries: 2
[RT] Error: Test 025 cpld_debug_pdlib_p8_intel FAIL Tries: 2
[RT] Error: Test 026 control_flake_intel FAIL Tries: 2
[RT] Error: Test 027 control_CubedSphereGrid_intel FAIL Tries: 2
[RT] Error: Test 028 control_CubedSphereGrid_parallel_intel FAIL Tries: 2
[RT] Error: Test 029 control_latlon_intel FAIL Tries: 2
[RT] Error: Test 030 control_wrtGauss_netcdf_parallel_intel FAIL Tries: 2
[RT] Error: Test 031 control_c48_intel FAIL Tries: 2
[RT] Error: Test 032 control_c192_intel FAIL Tries: 2
[RT] Error: Test 033 control_c384_intel FAIL Tries: 2
[RT] Error: Test 034 control_c384gdas_intel FAIL Tries: 2
[RT] Error: Test 035 control_stochy_intel FAIL Tries: 2
[RT] Error: Test 037 control_lndp_intel FAIL Tries: 2
[RT] Error: Test 038 control_iovr4_intel FAIL Tries: 2
[RT] Error: Test 039 control_iovr5_intel FAIL Tries: 2
[RT] Error: Test 040 control_p8_intel FAIL Tries: 2
[RT] Error: Test 042 control_qr_p8_intel FAIL Tries: 2
[RT] Error: Test 044 control_decomp_p8_intel FAIL Tries: 2
[RT] Error: Test 045 control_2threads_p8_intel FAIL Tries: 2
[RT] Error: Test 046 control_p8_lndp_intel FAIL Tries: 2
[RT] Error: Test 047 control_p8_rrtmgp_intel FAIL Tries: 2
[RT] Error: Test 048 control_p8_mynn_intel FAIL Tries: 2
[RT] Error: Test 049 merra2_thompson_intel FAIL Tries: 2
[RT] Error: Test 050 regional_control_intel FAIL Tries: 2
[RT] Error: Test 052 regional_control_qr_intel FAIL Tries: 2
[RT] Error: Test 054 regional_decomp_intel FAIL Tries: 2
[RT] Error: Test 055 regional_2threads_intel FAIL Tries: 2
[RT] Error: Test 056 regional_noquilt_intel FAIL Tries: 2
[RT] Error: Test 057 regional_netcdf_parallel_intel FAIL Tries: 2
[RT] Error: Test 058 regional_2dwrtdecomp_intel FAIL Tries: 2
[RT] Error: Test 059 regional_wofs_intel FAIL Tries: 2
[RT] Error: Test 060 rap_control_intel FAIL Tries: 2
[RT] Error: Test 061 regional_spp_sppt_shum_skeb_intel FAIL Tries: 2
[RT] Error: Test 062 rap_decomp_intel FAIL Tries: 2
[RT] Error: Test 063 rap_2threads_intel FAIL Tries: 2
[RT] Error: Test 065 rap_sfcdiff_intel FAIL Tries: 2
[RT] Error: Test 066 rap_sfcdiff_decomp_intel FAIL Tries: 2
[RT] Error: Test 068 hrrr_control_intel FAIL Tries: 2
[RT] Error: Test 069 hrrr_control_qr_intel FAIL Tries: 2
[RT] Error: Test 070 hrrr_control_decomp_intel FAIL Tries: 2
[RT] Error: Test 071 hrrr_control_2threads_intel FAIL Tries: 2
[RT] Error: Test 074 rrfs_v1beta_intel FAIL Tries: 2
[RT] Error: Test 075 rrfs_v1nssl_intel FAIL Tries: 2
[RT] Error: Test 076 rrfs_v1nssl_nohailnoccn_intel FAIL Tries: 2
[RT] Error: Test 077 control_csawmg_intel FAIL Tries: 2
[RT] Error: Test 078 control_csawmgt_intel FAIL Tries: 2
[RT] Error: Test 079 control_ras_intel FAIL Tries: 2
[RT] Error: Test 080 control_wam_intel FAIL Tries: 2
[RT] Error: Test 081 control_p8_faster_intel FAIL Tries: 2
[RT] Error: Test 082 regional_control_faster_intel FAIL Tries: 2
[RT] Error: Test 083 control_CubedSphereGrid_debug_intel FAIL Tries: 2
[RT] Error: Test 084 control_wrtGauss_netcdf_parallel_debug_intel FAIL Tries: 2
[RT] Error: Test 085 control_stochy_debug_intel FAIL Tries: 2
[RT] Error: Test 086 control_lndp_debug_intel FAIL Tries: 2
[RT] Error: Test 087 control_csawmg_debug_intel FAIL Tries: 2
[RT] Error: Test 088 control_csawmgt_debug_intel FAIL Tries: 2
[RT] Error: Test 089 control_ras_debug_intel FAIL Tries: 2
[RT] Error: Test 090 control_diag_debug_intel FAIL Tries: 2
[RT] Error: Test 091 control_debug_p8_intel FAIL Tries: 2
[RT] Error: Test 092 regional_debug_intel FAIL Tries: 2
[RT] Error: Test 093 rap_control_debug_intel FAIL Tries: 2
[RT] Error: Test 094 hrrr_control_debug_intel FAIL Tries: 2
[RT] Error: Test 095 hrrr_gf_debug_intel FAIL Tries: 2
[RT] Error: Test 096 hrrr_c3_debug_intel FAIL Tries: 2
[RT] Error: Test 097 rap_unified_drag_suite_debug_intel FAIL Tries: 2
[RT] Error: Test 098 rap_diag_debug_intel FAIL Tries: 2
[RT] Error: Test 099 rap_cires_ugwp_debug_intel FAIL Tries: 2
[RT] Error: Test 100 rap_unified_ugwp_debug_intel FAIL Tries: 2
[RT] Error: Test 101 rap_lndp_debug_intel FAIL Tries: 2
[RT] Error: Test 102 rap_progcld_thompson_debug_intel FAIL Tries: 2
[RT] Error: Test 103 rap_noah_debug_intel FAIL Tries: 2
[RT] Error: Test 104 rap_sfcdiff_debug_intel FAIL Tries: 2
[RT] Error: Test 105 rap_noah_sfcdiff_cires_ugwp_debug_intel FAIL Tries: 2
[RT] Error: Test 106 rrfs_v1beta_debug_intel FAIL Tries: 2
[RT] Error: Test 107 rap_clm_lake_debug_intel FAIL Tries: 2
[RT] Error: Test 108 rap_flake_debug_intel FAIL Tries: 2
[RT] Error: Test 109 control_wam_debug_intel FAIL Tries: 2
[RT] Error: Test 110 regional_spp_sppt_shum_skeb_dyn32_phy32_intel FAIL Tries: 2
[RT] Error: Test 111 rap_control_dyn32_phy32_intel FAIL Tries: 2
[RT] Error: Test 112 hrrr_control_dyn32_phy32_intel FAIL Tries: 2
[RT] Error: Test 113 hrrr_control_qr_dyn32_phy32_intel FAIL Tries: 2
[RT] Error: Test 114 rap_2threads_dyn32_phy32_intel FAIL Tries: 2
[RT] Error: Test 115 hrrr_control_2threads_dyn32_phy32_intel FAIL Tries: 2
[RT] Error: Test 116 hrrr_control_decomp_dyn32_phy32_intel FAIL Tries: 2
[RT] Error: Test 120 conus13km_control_intel FAIL Tries: 2
[RT] Error: Test 123 rap_control_dyn64_phy32_intel FAIL Tries: 2
[RT] Error: Test 124 rap_control_debug_dyn32_phy32_intel FAIL Tries: 2
[RT] Error: Test 125 hrrr_control_debug_dyn32_phy32_intel FAIL Tries: 2
[RT] Error: Test 126 conus13km_debug_intel FAIL Tries: 2
[RT] Error: Test 127 conus13km_debug_qr_intel FAIL Tries: 2
[RT] Error: Test 128 conus13km_debug_2threads_intel FAIL Tries: 2
[RT] Error: Test 129 conus13km_radar_tten_debug_intel FAIL Tries: 2
[RT] Error: Test 130 rap_control_dyn64_phy32_debug_intel FAIL Tries: 2
[RT] Error: Test 131 hafs_regional_atm_intel FAIL Tries: 2
[RT] Error: Test 132 hafs_regional_atm_thompson_gfdlsf_intel FAIL Tries: 2
[RT] Error: Test 133 hafs_regional_atm_ocn_intel FAIL Tries: 2
[RT] Error: Test 134 hafs_regional_atm_wav_intel FAIL Tries: 2
[RT] Error: Test 135 hafs_regional_atm_ocn_wav_intel FAIL Tries: 2
[RT] Error: Test 136 hafs_regional_1nest_atm_intel FAIL Tries: 2
[RT] Error: Test 137 hafs_regional_1nest_atm_qr_intel FAIL Tries: 2
[RT] Error: Test 138 hafs_regional_telescopic_2nests_atm_intel FAIL Tries: 2
[RT] Error: Test 139 hafs_global_1nest_atm_intel FAIL Tries: 2
[RT] Error: Test 140 hafs_global_1nest_atm_qr_intel FAIL Tries: 2
[RT] Error: Test 141 hafs_global_multiple_4nests_atm_intel FAIL Tries: 2
[RT] Error: Test 142 hafs_global_multiple_4nests_atm_qr_intel FAIL Tries: 2
[RT] Error: Test 143 hafs_regional_specified_moving_1nest_atm_intel FAIL Tries: 2
[RT] Error: Test 144 hafs_regional_storm_following_1nest_atm_intel FAIL Tries: 2
[RT] Error: Test 145 hafs_regional_storm_following_1nest_atm_qr_intel FAIL Tries: 2
[RT] Error: Test 146 hafs_regional_storm_following_1nest_atm_ocn_intel FAIL Tries: 2
[RT] Error: Test 147 hafs_global_storm_following_1nest_atm_intel FAIL Tries: 2
[RT] Error: Test 148 hafs_regional_storm_following_1nest_atm_ocn_debug_intel FAIL Tries: 2
[RT] Error: Test 149 hafs_regional_storm_following_1nest_atm_ocn_wav_intel FAIL Tries: 2
[RT] Error: Test 150 hafs_regional_docn_intel FAIL Tries: 2
[RT] Error: Test 151 hafs_regional_docn_oisst_intel FAIL Tries: 2
[RT] Error: Test 165 datm_cdeps_gfs_intel FAIL Tries: 2
[RT] Error: Test 170 control_p8_atmlnd_sbs_intel FAIL Tries: 2
[RT] Error: Test 171 atmwav_control_noaero_p8_intel FAIL Tries: 2
[RT] Error: Test 172 control_atmwav_intel FAIL Tries: 2
[RT] Error: Test 173 atmaero_control_p8_intel FAIL Tries: 2
[RT] Error: Test 174 atmaero_control_p8_rad_intel FAIL Tries: 2
[RT] Error: Test 175 atmaero_control_p8_rad_micro_intel FAIL Tries: 2
[RT] Error: Test 176 regional_atmaq_intel FAIL Tries: 2
[RT] Error: Test 177 regional_atmaq_debug_intel FAIL Tries: 2
[RT] Error: Test 178 regional_atmaq_faster_intel FAIL Tries: 2
[RT] Error: Test 179 control_c48_gnu FAIL Tries: 2
[RT] Error: Test 180 control_stochy_gnu FAIL Tries: 2
[RT] Error: Test 181 control_ras_gnu FAIL Tries: 2
[RT] Error: Test 182 control_p8_gnu FAIL Tries: 2
[RT] Error: Test 183 control_flake_gnu FAIL Tries: 2
[RT] Error: Test 184 rap_control_gnu FAIL Tries: 2
[RT] Error: Test 185 rap_decomp_gnu FAIL Tries: 2
[RT] Error: Test 186 rap_2threads_gnu FAIL Tries: 2
[RT] Error: Test 188 rap_sfcdiff_gnu FAIL Tries: 2
[RT] Error: Test 189 rap_sfcdiff_decomp_gnu FAIL Tries: 2
[RT] Error: Test 191 hrrr_control_gnu FAIL Tries: 2
[RT] Error: Test 192 hrrr_control_qr_gnu FAIL Tries: 2
[RT] Error: Test 193 hrrr_control_2threads_gnu FAIL Tries: 2
[RT] Error: Test 194 hrrr_control_decomp_gnu FAIL Tries: 2
[RT] Error: Test 197 rrfs_v1beta_gnu FAIL Tries: 2
[RT] Error: Test 198 control_diag_debug_gnu FAIL Tries: 2
[RT] Error: Test 199 regional_debug_gnu FAIL Tries: 2
[RT] Error: Test 200 rap_control_debug_gnu FAIL Tries: 2
[RT] Error: Test 201 hrrr_control_debug_gnu FAIL Tries: 2
[RT] Error: Test 202 hrrr_gf_debug_gnu FAIL Tries: 2
[RT] Error: Test 203 hrrr_c3_debug_gnu FAIL Tries: 2
[RT] Error: Test 204 rap_diag_debug_gnu FAIL Tries: 2
[RT] Error: Test 205 rap_noah_sfcdiff_cires_ugwp_debug_gnu FAIL Tries: 2
[RT] Error: Test 206 rap_progcld_thompson_debug_gnu FAIL Tries: 2
[RT] Error: Test 207 rrfs_v1beta_debug_gnu FAIL Tries: 2
[RT] Error: Test 208 control_ras_debug_gnu FAIL Tries: 2
[RT] Error: Test 209 control_stochy_debug_gnu FAIL Tries: 2
[RT] Error: Test 210 control_debug_p8_gnu FAIL Tries: 2
[RT] Error: Test 211 rap_flake_debug_gnu FAIL Tries: 2
[RT] Error: Test 212 rap_clm_lake_debug_gnu FAIL Tries: 2
[RT] Error: Test 213 control_wam_debug_gnu FAIL Tries: 2
[RT] Error: Test 214 rap_control_dyn32_phy32_gnu FAIL Tries: 2
[RT] Error: Test 215 hrrr_control_dyn32_phy32_gnu FAIL Tries: 2
[RT] Error: Test 216 hrrr_control_qr_dyn32_phy32_gnu FAIL Tries: 2
[RT] Error: Test 217 rap_2threads_dyn32_phy32_gnu FAIL Tries: 2
[RT] Error: Test 218 hrrr_control_2threads_dyn32_phy32_gnu FAIL Tries: 2
[RT] Error: Test 219 hrrr_control_decomp_dyn32_phy32_gnu FAIL Tries: 2
[RT] Error: Test 223 conus13km_control_gnu FAIL Tries: 2
[RT] Error: Test 226 rap_control_dyn64_phy32_gnu FAIL Tries: 2
[RT] Error: Test 227 rap_control_debug_dyn32_phy32_gnu FAIL Tries: 2
[RT] Error: Test 228 hrrr_control_debug_dyn32_phy32_gnu FAIL Tries: 2
[RT] Error: Test 229 conus13km_debug_gnu FAIL Tries: 2
[RT] Error: Test 230 conus13km_debug_qr_gnu FAIL Tries: 2
[RT] Error: Test 231 conus13km_debug_2threads_gnu FAIL Tries: 2
[RT] Error: Test 232 conus13km_radar_tten_debug_gnu FAIL Tries: 2
[RT] Error: Test 233 rap_control_dyn64_phy32_debug_gnu FAIL Tries: 2
[RT] Error: Test 234 cpld_control_p8_gnu FAIL Tries: 2
[RT] Error: Test 235 cpld_control_nowave_noaero_p8_gnu FAIL Tries: 2
[RT] Error: Test 236 cpld_debug_p8_gnu FAIL Tries: 2
[RT] Error: Test 237 cpld_control_pdlib_p8_gnu FAIL Tries: 2
[RT] Error: Test 238 cpld_debug_pdlib_p8_gnu FAIL Tries: 2
[RT] Log file shows failures.
[RT] Please obtain logs from /scratch1/BMC/gmtb/CCPP_regression_testing/NCAR_ufs-weather-model//run//1626516739/20240125220515/ufs-weather-model

**Comment by grantfirl** [comment]
@mkavulich Since the parent PRs were not specific about exactly which RTs are expected to fail, this result is consistent with the description. I think that we're ready to start the BL tag and merging, if successful. If successful, please move the new baselines to main-20240126 so that we can start on the next one.

**Comment by mkavulich** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/CCPP_regression_testing/NCAR_ufs-weather-model//run//1626516739/20240129203511/ufs-weather-model
Please make changes and add the following label back: hera-intel-BL

**Comment by mkavulich** [comment]
@grantfirl The new baselines have been moved (also removed a couple old ones to make sure we're still good on space).

**Review by mkavulich — APPROVED** [review]

**Pull request merged**
