### PR TITLE
UFS-dev PR70+PR71

### PR DESCRIPTION
**Pull request by grantfirl**
Contains both https://github.com/ufs-community/ufs-weather-model/pull/1751 and https://github.com/ufs-community/ufs-weather-model/pull/1754

Also contains changes from https://github.com/ufs-community/ufs-weather-model/pull/1749, https://github.com/ufs-community/ufs-weather-model/pull/1727, https://github.com/ufs-community/ufs-weather-model/pull/1728, https://github.com/ufs-community/ufs-weather-model/pull/1722, https://github.com/ufs-community/ufs-weather-model/pull/1736, https://github.com/ufs-community/ufs-weather-model/pull/1699, https://github.com/ufs-community/ufs-weather-model/pull/1761, https://github.com/ufs-community/ufs-weather-model/pull/1718, https://github.com/ufs-community/ufs-weather-model/pull/1743

Associated PRs: https://github.com/NCAR/ufs-weather-model/pull/100, https://github.com/NCAR/fv3atm/pull/97, https://github.com/NCAR/ccpp-physics/pull/1021, https://github.com/NCAR/ccpp-scm/pull/393

### CODE REVIEW

**Comment by grantfirl** [comment]
1731 RT failures:
INTEL FAILED TESTS:
Test cpld_control_p8_mixedmode 001 failed in run_test failed
Test cpld_control_gfsv17 002 failed in run_test failed
Test cpld_control_p8 003 failed in run_test failed
Test cpld_control_qr_p8 005 failed in run_test failed
Test cpld_2threads_p8 007 failed in run_test failed
Test cpld_decomp_p8 008 failed in run_test failed
Test cpld_mpi_p8 009 failed in run_test failed
Test cpld_control_ciceC_p8 010 failed in run_test failed
Test cpld_control_c192_p8 011 failed in run_test failed
Test cpld_control_noaero_p8 013 failed in run_test failed
Test cpld_debug_p8 015 failed in run_test failed
Test cpld_debug_noaero_p8 016 failed in run_test failed
Test control_flake 021 failed in run_test failed
Test control_latlon 024 failed in run_test failed
Test control_wrtGauss_netcdf_parallel 025 failed in run_test failed
Test control_c192 027 failed in run_test failed
Test control_c384 028 failed in run_test failed
Test control_c384gdas 029 failed in run_test failed
Test control_stochy 030 failed in run_test failed
Test control_lndp 032 failed in run_test failed
Test control_iovr4 033 failed in run_test failed
Test control_iovr5 034 failed in run_test failed
Test control_p8 035 failed in run_test failed
Test control_qr_p8 037 failed in run_test failed
Test control_decomp_p8 039 failed in run_test failed
Test control_2threads_p8 040 failed in run_test failed
Test control_p8_lndp 041 failed in run_test failed
Test control_p8_rrtmgp 042 failed in run_test failed
Test control_p8_mynn 043 failed in run_test failed
Test merra2_thompson 044 failed in run_test failed
Test control_csawmg 075 failed in run_test failed
Test control_csawmgt 076 failed in run_test failed
Test control_ras 077 failed in run_test failed
Test control_p8_faster 079 failed in run_test failed
Test hafs_regional_atm 121 failed in run_test failed
Test hafs_regional_atm_ocn 123 failed in run_test failed
Test hafs_regional_atm_wav 124 failed in run_test failed
Test hafs_regional_atm_ocn_wav 125 failed in run_test failed
Test hafs_global_multiple_4nests_atm 129 failed in run_test failed
Test hafs_regional_specified_moving_1nest_atm 130 failed in run_test failed
Test hafs_regional_storm_following_1nest_atm_ocn 132 failed in run_test failed
Test hafs_regional_storm_following_1nest_atm_ocn_wav 135 failed in run_test failed
Test atmwav_control_noaero_p8 157 failed in run_test failed
Test control_atmwav 158 failed in run_test failed
Test atmaero_control_p8 159 failed in run_test failed
Test atmaero_control_p8_rad 160 failed in run_test failed
Test atmaero_control_p8_rad_micro 161 failed in run_test failed

GNU FAILED TESTS:
Test control_c48 001 failed in run_test failed
Test control_stochy 002 failed in run_test failed
Test control_ras 003 failed in run_test failed
Test control_p8 004 failed in run_test failed
Test control_flake 005 failed in run_test failed
Test control_diag_debug 023 failed in run_test failed
Test control_ras_debug 031 failed in run_test failed
Test control_stochy_debug 032 failed in run_test failed
Test control_debug_p8 033 failed in run_test failed
Test control_wam_debug 039 failed in run_test failed
Test cpld_control_p8 051 failed in run_test failed
Test cpld_control_nowave_noaero_p8 052 failed in run_test failed
Test cpld_debug_p8 053 failed in run_test failed

**Comment by grantfirl** [comment]
1728 failures: cpld_control_gfsv17

**Comment by grantfirl** [comment]
1722 failures:
hafs_global_1nest_atm
hafs_global_multiple_4nests_atm
hafs_regional_1nest_atm
hafs_regional_storm_following_1nest_atm

**Comment by grantfirl** [comment]
1718:
This should not change answers to any test, but the whole regression testing system is getting name changes, so all baselines will need to be regenerated with the new code changes and new baseline-dirs will need to be created.

**Comment by grantfirl** [comment]
1743 failures:
regional_control 041 failed in check_result
regional_control 041 failed in run_test
regional_control_qr 043 failed in check_result
regional_control_qr 043 failed in run_test
regional_decomp 045 failed in check_result
regional_decomp 045 failed in run_test
regional_2threads 046 failed in check_result
regional_2threads 046 failed in run_test
regional_noquilt 047 failed in check_result
regional_noquilt 047 failed in run_test
regional_netcdf_parallel 048 failed in check_result
regional_netcdf_parallel 048 failed in run_test
regional_2dwrtdecomp 049 failed in check_result
regional_2dwrtdecomp 049 failed in run_test
regional_wofs 050 failed in check_result
regional_wofs 050 failed in run_test
regional_spp_sppt_shum_skeb 052 failed in check_result
regional_spp_sppt_shum_skeb 052 failed in run_test
rrfs_smoke_conus13km_hrrr_warm 066 failed in check_result
rrfs_smoke_conus13km_hrrr_warm 066 failed in run_test
rrfs_smoke_conus13km_hrrr_warm_2threads 067 failed in check_result
rrfs_smoke_conus13km_hrrr_warm_2threads 067 failed in run_test
rrfs_conus13km_hrrr_warm 068 failed in check_result
rrfs_conus13km_hrrr_warm 068 failed in run_test
rrfs_smoke_conus13km_radar_tten_warm 069 failed in check_result
rrfs_smoke_conus13km_radar_tten_warm 069 failed in run_test
regional_control_faster 076 failed in check_result
regional_control_faster 076 failed in run_test
regional_spp_sppt_shum_skeb_dyn32_phy32 104 failed in check_result
regional_spp_sppt_shum_skeb_dyn32_phy32 104 failed in run_test
hafs_regional_atm 116 failed in check_result
hafs_regional_atm 116 failed in run_test
hafs_regional_atm_thompson_gfdlsf 117 failed in check_result
hafs_regional_atm_thompson_gfdlsf 117 failed in run_test
hafs_regional_atm_ocn 118 failed in check_result
hafs_regional_atm_ocn 118 failed in run_test
hafs_regional_atm_wav 119 failed in check_result
hafs_regional_atm_wav 119 failed in run_test
hafs_regional_atm_ocn_wav 120 failed in check_result
hafs_regional_atm_ocn_wav 120 failed in run_test
hafs_regional_1nest_atm 121 failed in check_result
hafs_regional_1nest_atm 121 failed in run_test
hafs_regional_telescopic_2nests_atm 122 failed in check_result
hafs_regional_telescopic_2nests_atm 122 failed in run_test
hafs_global_1nest_atm 123 failed in check_result
hafs_global_1nest_atm 123 failed in run_test
hafs_global_multiple_4nests_atm 124 failed in check_result
hafs_global_multiple_4nests_atm 124 failed in run_test
hafs_regional_specified_moving_1nest_atm 125 failed in check_result
hafs_regional_specified_moving_1nest_atm 125 failed in run_test
hafs_regional_storm_following_1nest_atm 126 failed in check_result
hafs_regional_storm_following_1nest_atm 126 failed in run_test
hafs_regional_storm_following_1nest_atm_ocn 127 failed in check_result
hafs_regional_storm_following_1nest_atm_ocn 127 failed in run_test
hafs_global_storm_following_1nest_atm 128 failed in check_result
hafs_global_storm_following_1nest_atm 128 failed in run_test
hafs_regional_storm_following_1nest_atm_ocn_wav 130 failed in check_result
hafs_regional_storm_following_1nest_atm_ocn_wav 130 failed in run_test
atmaero_control_p8 132 failed in run_test

**Comment by mkavulich** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1408697930/20230705205230/ufs-weather-model
Please make changes and add the following label back: hera-intel-RT

**Comment by mkavulich** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1408697930/20230705205822/ufs-weather-model
Please make changes and add the following label back: hera-intel-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
Please make changes and add the following label back: hera-intel-RT

**Comment by grantfirl** [comment]
Note that this PR recreates all baselines due to https://github.com/ufs-community/ufs-weather-model/pull/1718. Also, this requires new input data to be copied on Cheyenne and Hera due to https://github.com/ufs-community/ufs-weather-model/pull/1727.

**Review by mkavulich — APPROVED** [review]

**Pull request merged**
