### PR TITLE
UFS-dev PR#110

### PR DESCRIPTION
**Pull request by grantfirl**
Identical to https://github.com/ufs-community/ufs-weather-model/pull/1924

Expected RT failures: regional_wofs, rrfs_v1nssl, rrfs_v1nssl_nohailnoccn

### CODE REVIEW

**Comment by grantfirl** [comment]
@mkavulich Ready to test

**Comment by mkavulich** [comment]
Failures match expected, starting baseline creation

**Comment by mkavulich** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/CCPP_regression_testing/NCAR_ufs-weather-model//run//1628480558/20240207191015/ufs-weather-model
Please make changes and add the following label back: hera-intel-BL

**Review by mkavulich — APPROVED** [review]
New baselines moved to `baselines/main-20240207`. Looks good to go once baseline date and submodule are updated.

**Pull request merged**
