### PR TITLE
UFS-dev PR#27

### PR DESCRIPTION
**Pull request by grantfirl**
Identical to https://github.com/ufs-community/ufs-weather-model/pull/1518

### CODE REVIEW

**Comment by grantfirl** [comment]
Contains changes from #79 and #80 until those are merged. Also https://github.com/ufs-community/ufs-weather-model/pull/1505, https://github.com/ufs-community/ufs-weather-model/pull/1513, https://github.com/ufs-community/ufs-weather-model/pull/1525, https://github.com/ufs-community/ufs-weather-model/pull/1514 (all not related to CCPP)

**Comment by grantfirl** [comment]
New baselines needed for HAFS-related RTs.

**Comment by grantfirl** [comment]
Baselines also changed in https://github.com/ufs-community/ufs-weather-model/pull/1513

**Comment by grantfirl** [comment]
https://github.com/ufs-community/ufs-weather-model/pull/1514 adds a new RT too

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1172606845/20221226084509/ufs-weather-model
[RT] Error: Test cpld_control_p8_mixedmode 001 failed in check_result failed 
[RT] Error: Test cpld_control_p8_mixedmode 001 failed in run_test failed 
[RT] Error: Test hafs_regional_atm_ocn 114 failed in check_result failed 
[RT] Error: Test hafs_regional_atm_ocn 114 failed in run_test failed 
[RT] Error: Test hafs_regional_atm_ocn_wav 116 failed in check_result failed 
[RT] Error: Test hafs_regional_atm_ocn_wav 116 failed in run_test failed 
[RT] Error: Test hafs_regional_1nest_atm 117 failed in check_result failed 
[RT] Error: Test hafs_regional_1nest_atm 117 failed in run_test failed 
[RT] Error: Test hafs_regional_telescopic_2nests_atm 118 failed in check_result failed 
[RT] Error: Test hafs_regional_telescopic_2nests_atm 118 failed in run_test failed 
[RT] Error: Test hafs_global_1nest_atm 119 failed in check_result failed 
[RT] Error: Test hafs_global_1nest_atm 119 failed in run_test failed 
[RT] Error: Test hafs_global_multiple_4nests_atm 120 failed in check_result failed 
[RT] Error: Test hafs_global_multiple_4nests_atm 120 failed in run_test failed 
[RT] Error: Test hafs_regional_specified_moving_1nest_atm 121 failed in check_result failed 
[RT] Error: Test hafs_regional_specified_moving_1nest_atm 121 failed in run_test failed 
[RT] Error: Test hafs_regional_storm_following_1nest_atm 122 failed in check_result failed 
[RT] Error: Test hafs_regional_storm_following_1nest_atm 122 failed in run_test failed 
[RT] Error: Test hafs_regional_storm_following_1nest_atm_ocn 123 failed in check_result failed 
[RT] Error: Test hafs_regional_storm_following_1nest_atm_ocn 123 failed in run_test failed 
[RT] Error: Test hafs_regional_storm_following_1nest_atm_ocn_wav 124 failed in check_result failed 
[RT] Error: Test hafs_regional_storm_following_1nest_atm_ocn_wav 124 failed in run_test failed 
[RT] Error: Test hafs_global_storm_following_1nest_atm 125 failed in check_result failed 
[RT] Error: Test hafs_global_storm_following_1nest_atm 125 failed in run_test failed 
[RT] Error: Test hafs_regional_datm_cdeps 128 failed in check_result failed 
[RT] Error: Test hafs_regional_datm_cdeps 128 failed in run_test failed 
[RT] Error: Test regional_atmaq 150 failed in check_result failed 
[RT] Error: Test regional_atmaq 150 failed in run_test failed 
[RT] Error: Test regional_atmaq_debug 151 failed in check_result failed 
[RT] Error: Test regional_atmaq_debug 151 failed in run_test failed 
Please make changes and add the following label back: cheyenne-intel-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1172606845/20221226154513/ufs-weather-model
[RT] Error: Test cpld_control_p8_mixedmode 001 failed in check_result failed 
[RT] Error: Test cpld_control_p8_mixedmode 001 failed in run_test failed 
[RT] Error: Test hafs_regional_atm_ocn 116 failed in check_result failed 
[RT] Error: Test hafs_regional_atm_ocn 116 failed in run_test failed 
[RT] Error: Test hafs_regional_atm_ocn_wav 118 failed in check_result failed 
[RT] Error: Test hafs_regional_atm_ocn_wav 118 failed in run_test failed 
[RT] Error: Test hafs_regional_1nest_atm 119 failed in check_result failed 
[RT] Error: Test hafs_regional_1nest_atm 119 failed in run_test failed 
[RT] Error: Test hafs_regional_telescopic_2nests_atm 120 failed in check_result failed 
[RT] Error: Test hafs_regional_telescopic_2nests_atm 120 failed in run_test failed 
[RT] Error: Test hafs_global_1nest_atm 121 failed in check_result failed 
[RT] Error: Test hafs_global_1nest_atm 121 failed in run_test failed 
[RT] Error: Test hafs_global_multiple_4nests_atm 122 failed in check_result failed 
[RT] Error: Test hafs_global_multiple_4nests_atm 122 failed in run_test failed 
[RT] Error: Test hafs_regional_specified_moving_1nest_atm 123 failed in check_result failed 
[RT] Error: Test hafs_regional_specified_moving_1nest_atm 123 failed in run_test failed 
[RT] Error: Test hafs_regional_storm_following_1nest_atm 124 failed in check_result failed 
[RT] Error: Test hafs_regional_storm_following_1nest_atm 124 failed in run_test failed 
[RT] Error: Test hafs_regional_storm_following_1nest_atm_ocn 125 failed in check_result failed 
[RT] Error: Test hafs_regional_storm_following_1nest_atm_ocn 125 failed in run_test failed 
[RT] Error: Test hafs_regional_storm_following_1nest_atm_ocn_wav 126 failed in check_result failed 
[RT] Error: Test hafs_regional_storm_following_1nest_atm_ocn_wav 126 failed in run_test failed 
[RT] Error: Test hafs_global_storm_following_1nest_atm 127 failed in check_result failed 
[RT] Error: Test hafs_global_storm_following_1nest_atm 127 failed in run_test failed 
[RT] Error: Test hafs_regional_datm_cdeps 130 failed in check_result failed 
[RT] Error: Test hafs_regional_datm_cdeps 130 failed in run_test failed 
[RT] Error: Test regional_atmaq 152 failed in check_result failed 
[RT] Error: Test regional_atmaq 152 failed in run_test failed 
[RT] Error: Test regional_atmaq_debug 153 failed in check_result failed 
[RT] Error: Test regional_atmaq_debug 153 failed in run_test failed 
Please make changes and add the following label back: hera-intel-RT

**Comment by grantfirl** [comment]
@dustinswales It looks like the expected RTs fail (HAFS, mixed-mode, and atmaq tests). I'll change BL_DATE in rt.ncar.sh and add the BL labels.

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1172606845/20221230114507/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1172606845/20221230121447/ufs-weather-model
Please make changes and add the following label back: cheyenne-gnu-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1172606845/20221230120008/ufs-weather-model
[BL] Error: Test regional_atmaq_debug 116 failed in run_test failed 
Please make changes and add the following label back: cheyenne-intel-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1172606845/20221230184515/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1172606845/20221230193054/ufs-weather-model
[RT] Error: Test cpld_control_p8 046 failed in run_test failed 
Please make changes and add the following label back: hera-gnu-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1172606845/20221230190011/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1172606845/20221230200146/ufs-weather-model
Please make changes and add the following label back: hera-intel-BL

**Comment by grantfirl** [comment]
FYI, @dustinswales I'm trying something new. To get around the failed BL creation, I changed the BL_DATE in rt.ncar.sh to 20221230a rather than 20221230 so that it will create a different folder and not error about the dir already existing. This is a workaround for me not being able to delete files in your space manually. If this works, you'll just need to manually copy the new BLs from the 20221230a directory to the 20221230 directory and I'll revert the BL_DATE back to 20221230 when I revert the WLCLK changes.

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1172606845/20221230144507/ufs-weather-model
Please make changes and add the following label back: cheyenne-intel-BL

**Comment by dustinswales** [comment]
> FYI, @dustinswales I'm trying something new. To get around the failed BL creation, I changed the BL_DATE in rt.ncar.sh to 20221230a rather than 20221230 so that it will create a different folder and not error about the dir already existing. This is a workaround for me not being able to delete files in your space manually. If this works, you'll just need to manually copy the new BLs from the 20221230a directory to the 20221230 directory and I'll revert the BL_DATE back to 20221230 when I revert the WLCLK changes.

@grantfirl Sorry, I thought I changed the permissions for you to be able to write (I'll check on this) But this seems like a good idea.

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1172606845/20221230214507/ufs-weather-model
Please make changes and add the following label back: hera-gnu-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1172606845/20230102141507/ufs-weather-model
Please make changes and add the following label back: cheyenne-intel-BL

**Comment by dustinswales** [comment]
@grantfirl Looks like that "a" suffix causes problems:
INFO:BL/UPDATE_RT_NCAR_SH:Date 20221230a is not formatted YYYYMMDD
CRITICAL:JOB/RUN:run() FAILED. Exception:<class 'Exception'>

We're almost there... All the tests pass except Cheyenne Intel. I cleaned up that directory (/glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/NCAR/main-20221230/INTEL). Whenever you get a chance revert the BL_DATE change and kick off a new cheyenne-intel-BL.

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1172606845/20230103103011/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1172606845/20230103113701/ufs-weather-model
Please make changes and add the following label back: cheyenne-intel-BL

**Comment by dustinswales** [comment]
@grantfirl It looks like the test worked, but also failed? 
Looking at the log,  /glade/u/home/dswales/Projects/UFS/auto-RT/ufs-weather-model/tests/auto/rt_auto_20230103103009.log, it runs the RTs and pushes the RT logs, but then fails? Looking at the script, rt_auto.py (same dir as above), it seems that it is failing when trying to remove the github label?

**Comment by grantfirl** [comment]
> @grantfirl It looks like the test worked, but also failed? Looking at the log, /glade/u/home/dswales/Projects/UFS/auto-RT/ufs-weather-model/tests/auto/rt_auto_20230103103009.log, it runs the RTs and pushes the RT logs, but then fails? Looking at the script, rt_auto.py (same dir as above), it seems that it is failing when trying to remove the github label?

Ya, it's been spitting out error messages to GitHub even after successful RTs. I don't know how it could detect failure on removing the label, because that was successful too. I think that we should be good to go ahead and merge this and try to figure out the failure messages afterward? If you agree, please approve this and the fv3atm PR so that we can merge.

**Review by dustinswales — APPROVED** [review]

**Pull request merged**
