### PR TITLE
dtc/hwrf-physics: update from HAFS community 

### PR DESCRIPTION
**Pull request by climbfuji**
This PR:
- updates dtc/hwrf-physics with the upstream changes from https://github.com/hafs-community/ufs-weather-model, branch support/HAFS

Associated PRs:
https://github.com/NCAR/ccpp-physics/pull/453
https://github.com/NCAR/fv3atm/pull/50
https://github.com/NCAR/ufs-weather-model/pull/48

For regression testing information, see below.

### CODE REVIEW

**Comment by climbfuji** [comment]
Regression testing on hera.intel using rt.conf against existing EMC baseline. The following tests fail as expected (see previous PRs for explanations):
```
(PROD)
fv3_stretched_nest
fv3_stretched_nest_quilt
fv3_regional_c768
(REPRO)
fv3_ccpp_gfdlmp_hwrfsas
fv3_ccpp_regional_c768_FA
fv3_ccpp_regional_c768_HWRF_PBL
fv3_ccpp_regional_c768_FA_HWRF_RRTMG
(PROD)
fv3_ccpp_stretched_nest
fv3_ccpp_gfdlmp_hwrfsas
fv3_ccpp_regional_c768
fv3_ccpp_regional_c768_HWRF_PBL
fv3_ccpp_regional_c768_FA
fv3_ccpp_regional_c768_FA_HWRF_RRTMG
```

[rt_hera_intel_against_emc_develop_20200424.log](https://github.com/NCAR/ufs-weather-model/files/4637396/rt_hera_intel_against_emc_develop_20200424.log)
[rt_hera_intel_against_emc_develop_20200424_fail_test.log](https://github.com/NCAR/ufs-weather-model/files/4637397/rt_hera_intel_against_emc_develop_20200424_fail_test.log)

**Comment by ligiabernardet** [comment]
Thanks for updating this branch and enable running on Orion. Looks good to me.

**Comment by climbfuji** [comment]
Regression testing on cheyenne.intel using rt_intel.conf: first create new baseline, then copy to final location, then verify. The following tests fail (known issue):
```
(REPRO)
fv3_ccpp_regional_c768_FA
fv3_ccpp_regional_c768_HWRF_PBL
fv3_ccpp_regional_c768_FA_HWRF_RRTMG
(PROD)
fv3_ccpp_regional_c768_FA
fv3_ccpp_regional_c768_HWRF_PBL
fv3_ccpp_regional_c768_FA_HWRF_RRTMG
```
[rt_cheyenne_intel_create.log](https://github.com/NCAR/ufs-weather-model/files/4644468/rt_cheyenne_intel_create.log)
[rt_cheyenne_intel_create_step2.log](https://github.com/NCAR/ufs-weather-model/files/4644470/rt_cheyenne_intel_create_step2.log)
[rt_cheyenne_intel_verify.log](https://github.com/NCAR/ufs-weather-model/files/4644471/rt_cheyenne_intel_verify.log)

**Comment by climbfuji** [comment]
Update @mzhangw @ligiabernardet : there is a weird issue with the GNU tests on Cheyenne, they no longer pass the IPD-CCPP b4b comparison in REPRO mode. I don't know why, this version of the code should still pass. I may just turn the IPD tests and the CCPP repro tests off entirely, as long as the CCPP tests reproduce against the previous HWRF physics baseline and the original EMC baseline. Not today anymore, though.

**Comment by climbfuji** [comment]
Regression testing on cheyenne.gnu `rt_gnu.conf`: first create new baseline, then copy to final location, then verify. After removing the IPD tests and the CCPP REPRO tests, i.e. the IPD-CCPP comparison, all tests pass.

[rt_cheyenne_gnu_create.log](https://github.com/NCAR/ufs-weather-model/files/4657433/rt_cheyenne_gnu_create.log)
[rt_cheyenne_gnu_verify.log](https://github.com/NCAR/ufs-weather-model/files/4657434/rt_cheyenne_gnu_verify.log)

**Comment by climbfuji** [comment]
@ligiabernardet @mzhangw these PRs are finally ready to merge. Will start in a bit.

**Comment by ligiabernardet** [comment]
Thanks!

**Pull request merged**
