### PR TITLE
Add regression test fv3_ccpp_gsd_sar_25km_debug

### PR DESCRIPTION
**Pull request by climbfuji**
This PR updates the submodule pointer for FV3 because of a bug fix for coldstarting models using RUC LSM with RAP/HRRR initial conditions (see https://github.com/NCAR/fv3atm/pull/22). The PR also adds a new regression test fv3_ccpp_gsd_sar_25km_debug which would have detected the error.

### CODE REVIEW

**Comment by climbfuji** [comment]
@JeffBeck-NOAA @gsketefian for your information

**Comment by JeffBeck-NOAA** [comment]
Dom,

Thanks again!  Please let us know when the PR is accepted and we can test the code.

Happy Holidays!

Jeff

**Comment by climbfuji** [comment]
Regression testing on hera/intel using rt.conf against DTC-maintained official baseline: all tests pass.

[rt_full.log](https://github.com/NCAR/ufs-weather-model/files/4000833/rt_full.log)

**Comment by climbfuji** [comment]
Regression testing using NEMSCompsetRun on hera/intel against EMC baseline. All tests pass except fv3_gfdlmprad_noahmp. This is correct, because the dtc/develop branches contain a bugfix for Noah MP that is not yet included in EMC's code.

[NEMSCompsetRun.log](https://github.com/NCAR/ufs-weather-model/files/4000835/NEMSCompsetRun.log)

**Comment by climbfuji** [comment]
Regression testing on hera/intel using rt_ccpp_gsd.conf (first create = CCPP static, then verify = CCPP static and CCPP dynamic). All tests pass, including the newly added fv3_ccpp_gsd_sar_25km_debug test.

[rt_ccpp_gsd_create.log](https://github.com/NCAR/ufs-weather-model/files/4001433/rt_ccpp_gsd_create.log)
[rt_ccpp_gsd_verify.log](https://github.com/NCAR/ufs-weather-model/files/4001434/rt_ccpp_gsd_verify.log)

**Comment by climbfuji** [comment]
@llpcarson @grantfirl @ligiabernardet @tanyasmirnova @JeffBeck-NOAA this PR and https://github.com/NCAR/fv3atm/pull/22 are ready to merge. They need to go into dtc/develop in the morning on Thu Dec 26 so that they will make it into the PR from dtc/develop to EMC's branches. Since the changes are straightforward and all tests passed, I will merge them w/o approval if necessary.

**Pull request merged**
