### PR TITLE
UFS-dev PR#122

### PR DESCRIPTION
**Pull request by grantfirl**
Identical to https://github.com/ufs-community/ufs-weather-model/pull/1941

There are two new tests:

gnv1_c96_no_nest_debug - The standard C96 initial conditions used for most physics suites, configured to run global_nest_v1. This is run in debug mode for both compilers
gnv1_nested - Run off of the HAFS global static nest test initial conditions, this tests the suite in a static nest.

Contains
 - https://github.com/ufs-community/ufs-weather-model/pull/1942
 - https://github.com/ufs-community/ufs-weather-model/pull/1953
 - https://github.com/ufs-community/ufs-weather-model/pull/1946 (no BL change expected)

### CODE REVIEW

**Comment by grantfirl** [comment]
Expected failures for https://github.com/ufs-community/ufs-weather-model/pull/1942:

rt_001_cpld_control_p8_mixedmode_intel.log:71:Test 001 cpld_control_p8_mixedmode_intel FAIL Tries: 2
rt_002_cpld_control_gfsv17_intel.log:70:Test 002 cpld_control_gfsv17_intel FAIL Tries: 2
rt_004_cpld_control_p8_intel.log:71:Test 004 cpld_control_p8_intel FAIL Tries: 2
rt_006_cpld_control_qr_p8_intel.log:71:Test 006 cpld_control_qr_p8_intel FAIL Tries: 2
rt_008_cpld_2threads_p8_intel.log:59:Test 008 cpld_2threads_p8_intel FAIL Tries: 2
rt_009_cpld_decomp_p8_intel.log:59:Test 009 cpld_decomp_p8_intel FAIL Tries: 2
rt_010_cpld_mpi_p8_intel.log:59:Test 010 cpld_mpi_p8_intel FAIL Tries: 2
rt_011_cpld_control_ciceC_p8_intel.log:71:Test 011 cpld_control_ciceC_p8_intel FAIL Tries: 2
rt_012_cpld_control_c192_p8_intel.log:59:Test 012 cpld_control_c192_p8_intel FAIL Tries: 2
rt_014_cpld_bmark_p8_intel.log:54:Test 014 cpld_bmark_p8_intel FAIL Tries: 2
rt_016_cpld_control_noaero_p8_intel.log:70:Test 016 cpld_control_noaero_p8_intel FAIL Tries: 2
rt_017_cpld_control_nowave_noaero_p8_intel.log:68:Test 017 cpld_control_nowave_noaero_p8_intel FAIL Tries: 2
rt_018_cpld_debug_p8_intel.log:59:Test 018 cpld_debug_p8_intel FAIL Tries: 2
rt_019_cpld_debug_noaero_p8_intel.log:58:Test 019 cpld_debug_noaero_p8_intel FAIL Tries: 2
rt_020_cpld_control_noaero_p8_agrid_intel.log:68:Test 020 cpld_control_noaero_p8_agrid_intel FAIL Tries: 2
rt_021_cpld_control_c48_intel.log:56:Test 021 cpld_control_c48_intel FAIL Tries: 2
rt_022_cpld_control_p8_faster_intel.log:71:Test 022 cpld_control_p8_faster_intel FAIL Tries: 2
rt_023_cpld_control_pdlib_p8_intel.log:70:Test 023 cpld_control_pdlib_p8_intel FAIL Tries: 2
rt_026_cpld_debug_pdlib_p8_intel.log:58:Test 026 cpld_debug_pdlib_p8_intel FAIL Tries: 2
rt_134_hafs_regional_atm_ocn_intel.log:15:Test 134 hafs_regional_atm_ocn_intel FAIL Tries: 2
rt_136_hafs_regional_atm_ocn_wav_intel.log:17:Test 136 hafs_regional_atm_ocn_wav_intel FAIL Tries: 2
rt_147_hafs_regional_storm_following_1nest_atm_ocn_intel.log:15:Test 147 hafs_regional_storm_following_1nest_atm_ocn_intel FAIL Tries: 2
rt_149_hafs_regional_storm_following_1nest_atm_ocn_debug_intel.log:13:Test 149 hafs_regional_storm_following_1nest_atm_ocn_debug_intel FAIL Tries: 2
rt_150_hafs_regional_storm_following_1nest_atm_ocn_wav_intel.log:17:Test 150 hafs_regional_storm_following_1nest_atm_ocn_wav_intel FAIL Tries: 2
rt_151_hafs_regional_docn_intel.log:14:Test 151 hafs_regional_docn_intel FAIL Tries: 2
rt_152_hafs_regional_docn_oisst_intel.log:14:Test 152 hafs_regional_docn_oisst_intel FAIL Tries: 2
rt_171_control_p8_atmlnd_sbs_intel.log:91:Test 171 control_p8_atmlnd_sbs_intel FAIL Tries: 2
rt_235_cpld_control_p8_gnu.log:71:Test 235 cpld_control_p8_gnu FAIL Tries: 2
rt_236_cpld_control_nowave_noaero_p8_gnu.log:68:Test 236 cpld_control_nowave_noaero_p8_gnu FAIL Tries: 2
rt_237_cpld_debug_p8_gnu.log:59:Test 237 cpld_debug_p8_gnu FAIL Tries: 2
rt_238_cpld_control_pdlib_p8_gnu.log:70:Test 238 cpld_control_pdlib_p8_gnu FAIL Tries: 2
rt_239_cpld_debug_pdlib_p8_gnu.log:58:Test 239 cpld_debug_pdlib_p8_gnu FAIL Tries: 2

**Comment by grantfirl** [comment]
Expected failure for https://github.com/ufs-community/ufs-weather-model/pull/1953

control_p8_mynn_intel

**Comment by grantfirl** [comment]
@mkavulich FYI, I kicked off tests for this one.

**Comment by grantfirl** [comment]
> @mkavulich FYI, I kicked off tests for this one. I'm including the previous PR to save effort since it was a very minor change and affects different RTs.

**Comment by mkavulich** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
[RT] Repo location: /scratch1/BMC/gmtb/CCPP_regression_testing/NCAR_ufs-weather-model//run//1628610165/20240207231517/ufs-weather-model
[RT] Error: Test 001 cpld_control_p8_mixedmode_intel FAIL Tries: 2
[RT] Error: Test 002 cpld_control_gfsv17_intel FAIL Tries: 2
[RT] Error: Test 005 cpld_mpi_gfsv17_intel FAIL Tries: 2
[RT] Error: Test 006 cpld_debug_gfsv17_intel FAIL Tries: 2
[RT] Error: Test 007 cpld_control_p8_intel FAIL Tries: 2
[RT] Error: Test 009 cpld_control_qr_p8_intel FAIL Tries: 2
[RT] Error: Test 011 cpld_2threads_p8_intel FAIL Tries: 2
[RT] Error: Test 012 cpld_decomp_p8_intel FAIL Tries: 2
[RT] Error: Test 013 cpld_mpi_p8_intel FAIL Tries: 2
[RT] Error: Test 014 cpld_control_ciceC_p8_intel FAIL Tries: 2
[RT] Error: Test 015 cpld_control_c192_p8_intel FAIL Tries: 2
[RT] Error: Test 017 cpld_bmark_p8_intel FAIL Tries: 2
[RT] Error: Test 019 cpld_control_noaero_p8_intel FAIL Tries: 2
[RT] Error: Test 020 cpld_control_nowave_noaero_p8_intel FAIL Tries: 2
[RT] Error: Test 021 cpld_debug_p8_intel FAIL Tries: 2
[RT] Error: Test 022 cpld_debug_noaero_p8_intel FAIL Tries: 2
[RT] Error: Test 023 cpld_control_noaero_p8_agrid_intel FAIL Tries: 2
[RT] Error: Test 024 cpld_control_c48_intel FAIL Tries: 2
[RT] Error: Test 025 cpld_control_p8_faster_intel FAIL Tries: 2
[RT] Error: Test 026 cpld_control_pdlib_p8_intel FAIL Tries: 2
[RT] Error: Test 029 cpld_debug_pdlib_p8_intel FAIL Tries: 2
[RT] Error: Test 053 control_p8_mynn_intel FAIL Tries: 2
[RT] Error: Test 110 gnv1_c96_no_nest_debug_intel FAIL Tries: 2
[RT] Error: Test 133 hafs_regional_atm_ocn_intel FAIL Tries: 2
[RT] Error: Test 135 hafs_regional_atm_ocn_wav_intel FAIL Tries: 2
[RT] Error: Test 142 hafs_regional_storm_following_1nest_atm_ocn_intel FAIL Tries: 2
[RT] Error: Test 144 gnv1_nested_intel FAIL Tries: 2
[RT] Error: Test 145 hafs_regional_storm_following_1nest_atm_ocn_debug_intel FAIL Tries: 2
[RT] Error: Test 146 hafs_regional_storm_following_1nest_atm_ocn_wav_intel FAIL Tries: 2
[RT] Error: Test 147 hafs_regional_docn_intel FAIL Tries: 2
[RT] Error: Test 148 hafs_regional_docn_oisst_intel FAIL Tries: 2
[RT] Error: Test 167 control_p8_atmlnd_sbs_intel FAIL Tries: 2
[RT] Error: Test 189 hrrr_control_gnu FAIL Tries: 2
[RT] Error: Test 211 gnv1_c96_no_nest_debug_gnu FAIL Tries: 2
[RT] Error: Test 231 cpld_control_p8_gnu FAIL Tries: 2
[RT] Error: Test 232 cpld_control_nowave_noaero_p8_gnu FAIL Tries: 2
[RT] Error: Test 233 cpld_debug_p8_gnu FAIL Tries: 2
[RT] Error: Test 234 cpld_control_pdlib_p8_gnu FAIL Tries: 2
[RT] Error: Test 235 cpld_debug_pdlib_p8_gnu FAIL Tries: 2
[RT] Log file shows failures.
[RT] Please obtain logs from /scratch1/BMC/gmtb/CCPP_regression_testing/NCAR_ufs-weather-model//run//1628610165/20240207231517/ufs-weather-model

**Comment by mkavulich** [comment]
@grantfirl It looks like there's a pretty substantial difference between the expected failures and the actual ones. Are you sure this is the correct list?

**Comment by grantfirl** [comment]
> @grantfirl It looks like there's a pretty substantial difference between the expected failures and the actual ones. Are you sure this is the correct list?

I see that the following tests aren't necessarily the same as the expected ones:
cpld_mpi_gfsv17_intel
cpld_debug_gfsv17_intel
gnv1_c96_no_nest_debug_intel 
gnv1_c96_no_nest_debug_gnu
hrrr_control_gnu

I'll investigate these. Since new tests were added, the test numbers are definitely shuffled around.

**Comment by grantfirl** [comment]
The gnv* ones are expected due to https://github.com/ufs-community/ufs-weather-model/pull/1941

**Comment by grantfirl** [comment]
It looks like https://github.com/ufs-community/ufs-weather-model/pull/1941 should change the cpld* tests too. It looks like those got missed in the original PR description.

**Comment by grantfirl** [comment]
https://github.com/ufs-community/ufs-weather-model/pull/1941 is change rap.nml.in which is used by hrrr_control_gnu. I don't know why other hrrr_control tests wouldn't fail though.

**Comment by grantfirl** [comment]
@mkavulich I'm not entirely sure why hrrr_control_gnu changes results. I'm kinda wondering if maybe there was something amiss with a previous PR we merged, e.g. the baseline was corrupted from the last PR or something. Either way, I'm not too concerned about it and I don't want to spend too much more time digging into it. I personally feel comfortable creating new baselines at this point. Do you?

**Comment by mkavulich** [comment]
@grantfirl That sounds good to me. I didn't realize the numbering had changed, so I thought we were dealing with a much larger number of differences. I'll kick off the baseline creation.

**Comment by mkavulich** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/CCPP_regression_testing/NCAR_ufs-weather-model//run//1628610165/20240208170018/ufs-weather-model
Please make changes and add the following label back: hera-intel-BL

**Review by mkavulich — APPROVED** [review]
Looks good once submodule is updated

**Pull request merged**
