### PR TITLE
UFS-dev PR#23

### PR DESCRIPTION
**Pull request by grantfirl**
Identical to https://github.com/ufs-community/ufs-weather-model/pull/1493

Changes baselines for RTs using NoahMP

### CODE REVIEW

**Comment by grantfirl** [comment]
Contains changes from older PRs that will disappear once they're merged into NCAR/main and this branch is updated.

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1143705153/20221214140008/ufs-weather-model
[RT] Error: Test control_p8 006 failed in check_result failed 
[RT] Error: Test control_p8 006 failed in run_test failed 
[RT] Error: Test rrfs_v1beta 018 failed in check_result failed 
[RT] Error: Test rrfs_v1beta 018 failed in run_test failed 
[RT] Error: Test rrfs_v1beta_debug 031 failed in check_result failed 
[RT] Error: Test rrfs_v1beta_debug 031 failed in run_test failed 
[RT] Error: Test control_debug_p8 034 failed in check_result failed 
[RT] Error: Test control_debug_p8 034 failed in run_test failed 
[RT] Error: Test cpld_control_p8 049 failed in check_result failed 
[RT] Error: Test cpld_control_p8 049 failed in run_test failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 050 failed in check_result failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 050 failed in run_test failed 
[RT] Error: Test cpld_debug_p8 051 failed in check_result failed 
[RT] Error: Test cpld_debug_p8 051 failed in run_test failed 
[RT] Error: Test datm_cdeps_control_cfsr 052 failed in check_result failed 
[RT] Error: Test datm_cdeps_control_cfsr 052 failed in run_test failed 
Please make changes and add the following label back: cheyenne-gnu-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: RT
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1143705153/20221214210012/ufs-weather-model
[RT] Error: Test control_p8 006 failed in check_result failed 
[RT] Error: Test control_p8 006 failed in run_test failed 
[RT] Error: Test rrfs_v1beta 018 failed in check_result failed 
[RT] Error: Test rrfs_v1beta 018 failed in run_test failed 
[RT] Error: Test rrfs_v1beta_debug 031 failed in check_result failed 
[RT] Error: Test rrfs_v1beta_debug 031 failed in run_test failed 
[RT] Error: Test control_debug_p8 034 failed in check_result failed 
[RT] Error: Test control_debug_p8 034 failed in run_test failed 
[RT] Error: Test cpld_control_p8 049 failed in check_result failed 
[RT] Error: Test cpld_control_p8 049 failed in run_test failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 050 failed in check_result failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 050 failed in run_test failed 
[RT] Error: Test cpld_debug_p8 051 failed in check_result failed 
[RT] Error: Test cpld_debug_p8 051 failed in run_test failed 
[RT] Error: Test datm_cdeps_control_cfsr 052 failed in check_result failed 
[RT] Error: Test datm_cdeps_control_cfsr 052 failed in run_test failed 
Please make changes and add the following label back: hera-gnu-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1143705153/20221214211509/ufs-weather-model
[RT] Error: Test cpld_control_p8 001 failed in check_result failed 
[RT] Error: Test cpld_control_p8 001 failed in run_test failed 
[RT] Error: Test cpld_2threads_p8 003 failed in check_result failed 
[RT] Error: Test cpld_2threads_p8 003 failed in run_test failed 
[RT] Error: Test cpld_esmfthreads_p8 004 failed in check_result failed 
[RT] Error: Test cpld_esmfthreads_p8 004 failed in run_test failed 
[RT] Error: Test cpld_decomp_p8 005 failed in check_result failed 
[RT] Error: Test cpld_decomp_p8 005 failed in run_test failed 
[RT] Error: Test cpld_mpi_p8 006 failed in check_result failed 
[RT] Error: Test cpld_mpi_p8 006 failed in run_test failed 
[RT] Error: Test cpld_control_ciceC_p8 007 failed in check_result failed 
[RT] Error: Test cpld_control_ciceC_p8 007 failed in run_test failed 
[RT] Error: Test cpld_control_c192_p8 008 failed in check_result failed 
[RT] Error: Test cpld_control_c192_p8 008 failed in run_test failed 
[RT] Error: Test cpld_bmark_p8 010 failed in check_result failed 
[RT] Error: Test cpld_bmark_p8 010 failed in run_test failed 
[RT] Error: Test cpld_control_noaero_p8 012 failed in check_result failed 
[RT] Error: Test cpld_control_noaero_p8 012 failed in run_test failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 013 failed in check_result failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 013 failed in run_test failed 
[RT] Error: Test cpld_debug_p8 014 failed in check_result failed 
[RT] Error: Test cpld_debug_p8 014 failed in run_test failed 
[RT] Error: Test cpld_debug_noaero_p8 015 failed in check_result failed 
[RT] Error: Test cpld_debug_noaero_p8 015 failed in run_test failed 
[RT] Error: Test cpld_control_noaero_p8_agrid 016 failed in check_result failed 
[RT] Error: Test cpld_control_noaero_p8_agrid 016 failed in run_test failed 
[RT] Error: Test cpld_control_c48 017 failed in check_result failed 
[RT] Error: Test cpld_control_c48 017 failed in run_test failed 
[RT] Error: Test cpld_warmstart_c48 018 failed in check_result failed 
[RT] Error: Test cpld_warmstart_c48 018 failed in run_test failed 
[RT] Error: Test control_p8 040 failed in check_result failed 
[RT] Error: Test control_p8 040 failed in run_test failed 
[RT] Error: Test control_p8_lndp 041 failed in check_result failed 
[RT] Error: Test control_p8_lndp 041 failed in run_test failed 
[RT] Error: Test control_decomp_p8 043 failed in check_result failed 
[RT] Error: Test control_decomp_p8 043 failed in run_test failed 
[RT] Error: Test control_2threads_p8 044 failed in check_result failed 
[RT] Error: Test control_2threads_p8 044 failed in run_test failed 
[RT] Error: Test control_p8_rrtmgp 045 failed in check_result failed 
[RT] Error: Test control_p8_rrtmgp 045 failed in run_test failed 
[RT] Error: Test merra2_thompson 046 failed in check_result failed 
[RT] Error: Test merra2_thompson 046 failed in run_test failed 
[RT] Error: Test rrfs_v1beta 068 failed in check_result failed 
[RT] Error: Test rrfs_v1beta 068 failed in run_test failed 
[RT] Error: Test rrfs_v1nssl 069 failed in check_result failed 
[RT] Error: Test rrfs_v1nssl 069 failed in run_test failed 
[RT] Error: Test rrfs_v1nssl_nohailnoccn 070 failed in check_result failed 
[RT] Error: Test rrfs_v1nssl_nohailnoccn 070 failed in run_test failed 
[RT] Error: Test control_debug_p8 092 failed in check_result failed 
[RT] Error: Test control_debug_p8 092 failed in run_test failed 
[RT] Error: Test rrfs_v1beta_debug 107 failed in check_result failed 
[RT] Error: Test rrfs_v1beta_debug 107 failed in run_test failed 
[RT] Error: Test datm_cdeps_control_cfsr 138 failed in check_result failed 
[RT] Error: Test datm_cdeps_control_cfsr 138 failed in run_test failed 
[RT] Error: Test datm_cdeps_control_gefs 140 failed in check_result failed 
[RT] Error: Test datm_cdeps_control_gefs 140 failed in run_test failed 
[RT] Error: Test datm_cdeps_iau_gefs 141 failed in check_result failed 
[RT] Error: Test datm_cdeps_iau_gefs 141 failed in run_test failed 
[RT] Error: Test datm_cdeps_stochy_gefs 142 failed in check_result failed 
[RT] Error: Test datm_cdeps_stochy_gefs 142 failed in run_test failed 
[RT] Error: Test datm_cdeps_ciceC_cfsr 143 failed in check_result failed 
[RT] Error: Test datm_cdeps_ciceC_cfsr 143 failed in run_test failed 
[RT] Error: Test datm_cdeps_bulk_cfsr 144 failed in check_result failed 
[RT] Error: Test datm_cdeps_bulk_cfsr 144 failed in run_test failed 
[RT] Error: Test datm_cdeps_bulk_gefs 145 failed in check_result failed 
[RT] Error: Test datm_cdeps_bulk_gefs 145 failed in run_test failed 
[RT] Error: Test datm_cdeps_mx025_cfsr 146 failed in check_result failed 
[RT] Error: Test datm_cdeps_mx025_cfsr 146 failed in run_test failed 
[RT] Error: Test datm_cdeps_mx025_gefs 147 failed in check_result failed 
[RT] Error: Test datm_cdeps_mx025_gefs 147 failed in run_test failed 
[RT] Error: Test datm_cdeps_multiple_files_cfsr 148 failed in check_result failed 
[RT] Error: Test datm_cdeps_multiple_files_cfsr 148 failed in run_test failed 
[RT] Error: Test datm_cdeps_3072x1536_cfsr 149 failed in check_result failed 
[RT] Error: Test datm_cdeps_3072x1536_cfsr 149 failed in run_test failed 
[RT] Error: Test datm_cdeps_gfs 150 failed in check_result failed 
[RT] Error: Test datm_cdeps_gfs 150 failed in run_test failed 
[RT] Error: Test datm_cdeps_debug_cfsr 151 failed in check_result failed 
[RT] Error: Test datm_cdeps_debug_cfsr 151 failed in run_test failed 
[RT] Error: Test datm_cdeps_lnd_gswp3 152 failed in check_result failed 
[RT] Error: Test datm_cdeps_lnd_gswp3 152 failed in run_test failed 
[RT] Error: Test control_p8_atmlnd_sbs 154 failed in check_result failed 
[RT] Error: Test control_p8_atmlnd_sbs 154 failed in run_test failed 
[RT] Error: Test atmaero_control_p8 156 failed in check_result failed 
[RT] Error: Test atmaero_control_p8 156 failed in run_test failed 
[RT] Error: Test atmaero_control_p8_rad 157 failed in check_result failed 
[RT] Error: Test atmaero_control_p8_rad 157 failed in run_test failed 
[RT] Error: Test atmaero_control_p8_rad_micro 158 failed in check_result failed 
[RT] Error: Test atmaero_control_p8_rad_micro 158 failed in run_test failed 
[RT] Error: Test regional_atmaq 159 failed in check_result failed 
[RT] Error: Test regional_atmaq 159 failed in run_test failed 
Please make changes and add the following label back: hera-intel-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1143705153/20221214141507/ufs-weather-model
[RT] Error: Test cpld_control_p8 001 failed in check_result failed 
[RT] Error: Test cpld_control_p8 001 failed in run_test failed 
[RT] Error: Test cpld_2threads_p8 003 failed in check_result failed 
[RT] Error: Test cpld_2threads_p8 003 failed in run_test failed 
[RT] Error: Test cpld_esmfthreads_p8 004 failed in check_result failed 
[RT] Error: Test cpld_esmfthreads_p8 004 failed in run_test failed 
[RT] Error: Test cpld_decomp_p8 005 failed in check_result failed 
[RT] Error: Test cpld_decomp_p8 005 failed in run_test failed 
[RT] Error: Test cpld_mpi_p8 006 failed in check_result failed 
[RT] Error: Test cpld_mpi_p8 006 failed in run_test failed 
[RT] Error: Test cpld_control_ciceC_p8 007 failed in check_result failed 
[RT] Error: Test cpld_control_ciceC_p8 007 failed in run_test failed 
[RT] Error: Test cpld_control_c192_p8 008 failed in check_result failed 
[RT] Error: Test cpld_control_c192_p8 008 failed in run_test failed 
[RT] Error: Test cpld_control_noaero_p8 010 failed in check_result failed 
[RT] Error: Test cpld_control_noaero_p8 010 failed in run_test failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 011 failed in check_result failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 011 failed in run_test failed 
[RT] Error: Test cpld_debug_p8 012 failed in check_result failed 
[RT] Error: Test cpld_debug_p8 012 failed in run_test failed 
[RT] Error: Test cpld_debug_noaero_p8 013 failed in check_result failed 
[RT] Error: Test cpld_debug_noaero_p8 013 failed in run_test failed 
[RT] Error: Test cpld_control_noaero_p8_agrid 014 failed in check_result failed 
[RT] Error: Test cpld_control_noaero_p8_agrid 014 failed in run_test failed 
[RT] Error: Test cpld_control_c48 015 failed in check_result failed 
[RT] Error: Test cpld_control_c48 015 failed in run_test failed 
[RT] Error: Test cpld_warmstart_c48 016 failed in check_result failed 
[RT] Error: Test cpld_warmstart_c48 016 failed in run_test failed 
[RT] Error: Test control_p8 038 failed in check_result failed 
[RT] Error: Test control_p8 038 failed in run_test failed 
[RT] Error: Test control_p8_lndp 039 failed in check_result failed 
[RT] Error: Test control_p8_lndp 039 failed in run_test failed 
[RT] Error: Test control_decomp_p8 041 failed in check_result failed 
[RT] Error: Test control_decomp_p8 041 failed in run_test failed 
[RT] Error: Test control_2threads_p8 042 failed in check_result failed 
[RT] Error: Test control_2threads_p8 042 failed in run_test failed 
[RT] Error: Test control_p8_rrtmgp 043 failed in check_result failed 
[RT] Error: Test control_p8_rrtmgp 043 failed in run_test failed 
[RT] Error: Test merra2_thompson 044 failed in check_result failed 
[RT] Error: Test merra2_thompson 044 failed in run_test failed 
[RT] Error: Test rrfs_v1beta 066 failed in check_result failed 
[RT] Error: Test rrfs_v1beta 066 failed in run_test failed 
[RT] Error: Test rrfs_v1nssl 067 failed in check_result failed 
[RT] Error: Test rrfs_v1nssl 067 failed in run_test failed 
[RT] Error: Test rrfs_v1nssl_nohailnoccn 068 failed in check_result failed 
[RT] Error: Test rrfs_v1nssl_nohailnoccn 068 failed in run_test failed 
[RT] Error: Test control_debug_p8 090 failed in check_result failed 
[RT] Error: Test control_debug_p8 090 failed in run_test failed 
[RT] Error: Test rrfs_v1beta_debug 105 failed in check_result failed 
[RT] Error: Test rrfs_v1beta_debug 105 failed in run_test failed 
[RT] Error: Test datm_cdeps_control_cfsr 136 failed in check_result failed 
[RT] Error: Test datm_cdeps_control_cfsr 136 failed in run_test failed 
[RT] Error: Test datm_cdeps_control_gefs 138 failed in check_result failed 
[RT] Error: Test datm_cdeps_control_gefs 138 failed in run_test failed 
[RT] Error: Test datm_cdeps_iau_gefs 139 failed in check_result failed 
[RT] Error: Test datm_cdeps_iau_gefs 139 failed in run_test failed 
[RT] Error: Test datm_cdeps_stochy_gefs 140 failed in check_result failed 
[RT] Error: Test datm_cdeps_stochy_gefs 140 failed in run_test failed 
[RT] Error: Test datm_cdeps_ciceC_cfsr 141 failed in check_result failed 
[RT] Error: Test datm_cdeps_ciceC_cfsr 141 failed in run_test failed 
[RT] Error: Test datm_cdeps_bulk_cfsr 142 failed in check_result failed 
[RT] Error: Test datm_cdeps_bulk_cfsr 142 failed in run_test failed 
[RT] Error: Test datm_cdeps_bulk_gefs 143 failed in check_result failed 
[RT] Error: Test datm_cdeps_bulk_gefs 143 failed in run_test failed 
[RT] Error: Test datm_cdeps_mx025_cfsr 144 failed in check_result failed 
[RT] Error: Test datm_cdeps_mx025_cfsr 144 failed in run_test failed 
[RT] Error: Test datm_cdeps_mx025_gefs 145 failed in check_result failed 
[RT] Error: Test datm_cdeps_mx025_gefs 145 failed in run_test failed 
[RT] Error: Test datm_cdeps_multiple_files_cfsr 146 failed in check_result failed 
[RT] Error: Test datm_cdeps_multiple_files_cfsr 146 failed in run_test failed 
[RT] Error: Test datm_cdeps_3072x1536_cfsr 147 failed in check_result failed 
[RT] Error: Test datm_cdeps_3072x1536_cfsr 147 failed in run_test failed 
[RT] Error: Test datm_cdeps_gfs 148 failed in check_result failed 
[RT] Error: Test datm_cdeps_gfs 148 failed in run_test failed 
[RT] Error: Test datm_cdeps_debug_cfsr 149 failed in check_result failed 
[RT] Error: Test datm_cdeps_debug_cfsr 149 failed in run_test failed 
[RT] Error: Test datm_cdeps_lnd_gswp3 150 failed in check_result failed 
[RT] Error: Test datm_cdeps_lnd_gswp3 150 failed in run_test failed 
[RT] Error: Test control_p8_atmlnd_sbs 152 failed in check_result failed 
[RT] Error: Test control_p8_atmlnd_sbs 152 failed in run_test failed 
[RT] Error: Test atmaero_control_p8 154 failed in check_result failed 
[RT] Error: Test atmaero_control_p8 154 failed in run_test failed 
[RT] Error: Test atmaero_control_p8_rad 155 failed in check_result failed 
[RT] Error: Test atmaero_control_p8_rad 155 failed in run_test failed 
[RT] Error: Test atmaero_control_p8_rad_micro 156 failed in check_result failed 
[RT] Error: Test atmaero_control_p8_rad_micro 156 failed in run_test failed 
[RT] Error: Test regional_atmaq 157 failed in check_result failed 
[RT] Error: Test regional_atmaq 157 failed in run_test failed 
Please make changes and add the following label back: cheyenne-intel-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1143705153/20221214173009/ufs-weather-model
[BL] Error: Test hafs_global_multiple_4nests_atm 089 failed in run_test failed 
[BL] Error: Test regional_atmaq 116 failed in run_test failed 
Please make changes and add the following label back: cheyenne-intel-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1143705153/20221214204507/ufs-weather-model
[BL] ERROR: Baseline location exists before creation:
/glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/NCAR/main-20221215/GNU
Please make changes and add the following label back: cheyenne-gnu-BL

**Comment by grantfirl** [comment]
@dustinswales I think that this is ready to merge when you approve this and https://github.com/NCAR/fv3atm/pull/76

**Comment by dustinswales** [comment]
@grantfirl Good to go now. (FYII the hera Intel job sat in queue yesterday for 12 hours, hence the holdup)

**Comment by grantfirl** [comment]
> @grantfirl Good to go now. (FYII the hera Intel job sat in queue yesterday for 12 hours, hence the holdup)

Ya, I was wondering if something weird was going on with Hera. I'll merge now.

**Pull request merged**
