### PR TITLE
UFS-dev PR88

### PR DESCRIPTION
**Pull request by grantfirl**
Identical to https://github.com/ufs-community/ufs-weather-model/pull/1815

Testing new rt_auto.sh...

### CODE REVIEW

**Comment by grantfirl** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
[RT] Repo location: /scratch1/BMC/gmtb/CCPP_regression_testing/NCAR_ufs-weather-model/run_gjf//1579763177/20231030202939/ufs-weather-model
Please make changes and add the following label back: hera-intel-RT

**Comment by grantfirl** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
[RT] Repo location: /scratch1/BMC/gmtb/CCPP_regression_testing/NCAR_ufs-weather-model/run_gjf//1579763177/20231030220228/ufs-weather-model
[RT] Error: Test 049 merra2_thompson_intel FAIL Tries: 2
[RT] Error: Test 180 atmaero_control_p8_rad_micro_intel FAIL Tries: 2
[RT] Log file shows failures.
[RT] Please obtain logs from /scratch1/BMC/gmtb/CCPP_regression_testing/NCAR_ufs-weather-model/run_gjf//1579763177/20231030220228/ufs-weather-model

**Comment by mkavulich** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
[RT] Repo location: /scratch1/BMC/gmtb/CCPP_regression_testing/NCAR_ufs-weather-model//run//1579763177/20231030222514/ufs-weather-model
[RT] Error: Test 049 merra2_thompson_intel FAIL Tries: 2
[RT] Error: Test 180 atmaero_control_p8_rad_micro_intel FAIL Tries: 2
[RT] Log file shows failures.
[RT] Please obtain logs from /scratch1/BMC/gmtb/CCPP_regression_testing/NCAR_ufs-weather-model//run//1579763177/20231030222514/ufs-weather-model

**Comment by mkavulich** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/CCPP_regression_testing/NCAR_ufs-weather-model//run//1579763177/20231031171516/ufs-weather-model
Please make changes and add the following label back: hera-intel-BL

**Comment by mkavulich** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/CCPP_regression_testing/NCAR_ufs-weather-model//run//1579763177/20231101015009/ufs-weather-model
Please make changes and add the following label back: hera-intel-BL

**Comment by mkavulich** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/CCPP_regression_testing/NCAR_ufs-weather-model//run//1579763177/20231101043008/ufs-weather-model
Please make changes and add the following label back: hera-intel-BL

**Comment by mkavulich** [comment]
Last tests failed due to running out of disk space. Re-launching now.

**Comment by grantfirl** [comment]
We should be OK now:

====== Generating the report at Wed Nov  1 15:00:29 UTC 2023 ======

Disk usage on the /scratch1 file system:

Disk usage(GB):         36317.17
Quota(GB):              50000.00
Hard limit(GB):         60000.00
Total files:             5028691
File quota:             10000000
File limit:             12000000

User data last updated at Wed Nov  1 03:03:13 UTC 2023

user             primary_group   gbytes                  files
Dustin.Swales             N       21076.44                972601
Grant.Firl                Y       16059.19                621392
Michael.Kavulich          N        6656.73                831135
Man.Zhang                 N        6288.26               1046392
Xia.Sun                   Y        4682.30                479855
Dom.Heinzeller            Y         797.04                329965
Michelle.Harrold          N         764.71                 51612
Judy.K.Henderson          N         192.62                 70871
Tracy.Hertneky            N         175.73                219679
Ligia.Bernardet           N          78.14                 67224
Weiwei.Li                 N          40.97                 85108
Mrinal.Biswas             N           1.06                  7402
Brianne.Nelson            Y           0.92                    83


Disk usage on the /scratch2 file system:

Disk usage(GB):             0.02
Quota(GB):                  0.00
Hard limit(GB):             0.00
Total files:                   0
File quota:                    0
File limit:                    0


This disk usage report for gmtb group has been generated at Wed Nov  1 15:00:30 UTC 2023

/scratch2/BMC/public/quotas/gmtb (END)

**Comment by mkavulich** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/CCPP_regression_testing/NCAR_ufs-weather-model//run//1579763177/20231101150015/ufs-weather-model
Please make changes and add the following label back: hera-intel-BL

**Comment by mkavulich** [comment]
Note: the above "failure" is false, the run was actually successful and new baselines are stored at /scratch1/BMC/gmtb/CCPP_regression_testing/NCAR_ufs-weather-model/baselines/main-20231031/

**Comment by grantfirl** [comment]
> Note: the above "failure" is false, the run was actually successful and new baselines are stored at /scratch1/BMC/gmtb/CCPP_regression_testing/NCAR_ufs-weather-model/baselines/main-20231031/

I'm actually copying from "new" to that directory right now, but, yes, I did see that it was a false failure.

**Review by mkavulich — APPROVED** [review]

**Pull request merged**
