### PR TITLE
ufs-dev PR#34a

### PR DESCRIPTION
**Pull request by dustinswales**
This is identical to [ufs-community #1571](https://github.com/ufs-community/ufs-weather-model/pull/1571)

### CODE REVIEW

**Review by grantfirl — APPROVED** [review]

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1259529439/20230301161507/ufs-weather-model
[RT] Error: Test compile_001 failed in run_compile failed 
[RT] Error: Test compile_002 failed in run_compile failed 
[RT] Error: Test compile_003 failed in run_compile failed 
[RT] Error: Test compile_004 failed in run_compile failed 
[RT] Error: Test compile_005 failed in run_compile failed 
[RT] Error: Test compile_006 failed in run_compile failed 
[RT] Error: Test compile_007 failed in run_compile failed 
[RT] Error: Test compile_008 failed in run_compile failed 
[RT] Error: Test compile_009 failed in run_compile failed 
[RT] Error: Test compile_010 failed in run_compile failed 
[RT] Error: Test compile_011 failed in run_compile failed 
Please make changes and add the following label back: cheyenne-gnu-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1259529439/20230301163007/ufs-weather-model
[RT] Error: Test datm_cdeps_mx025_cfsr 135 failed in run_test failed 
[RT] Error: Test compile_001 failed in run_compile failed 
[RT] Error: Test compile_002 failed in run_compile failed 
[RT] Error: Test compile_003 failed in run_compile failed 
[RT] Error: Test compile_004 failed in run_compile failed 
[RT] Error: Test compile_005 failed in run_compile failed 
[RT] Error: Test compile_006 failed in run_compile failed 
[RT] Error: Test compile_007 failed in run_compile failed 
[RT] Error: Test compile_008 failed in run_compile failed 
[RT] Error: Test compile_009 failed in run_compile failed 
[RT] Error: Test compile_010 failed in run_compile failed 
[RT] Error: Test compile_011 failed in run_compile failed 
[RT] Error: Test compile_012 failed in run_compile failed 
[RT] Error: Test compile_013 failed in run_compile failed 
[RT] Error: Test compile_014 failed in run_compile failed 
[RT] Error: Test compile_015 failed in run_compile failed 
[RT] Error: Test compile_016 failed in run_compile failed 
[RT] Error: Test compile_017 failed in run_compile failed 
[RT] Error: Test compile_018 failed in run_compile failed 
[RT] Error: Test compile_019 failed in run_compile failed 
[RT] Error: Test compile_020 failed in run_compile failed 
[RT] Error: Test compile_024 failed in run_compile failed 
[RT] Error: Test compile_025 failed in run_compile failed 
[RT] Error: Test compile_026 failed in run_compile failed 
[RT] Error: Test compile_027 failed in run_compile failed 
[RT] Error: Test compile_028 failed in run_compile failed 
Please make changes and add the following label back: cheyenne-intel-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1259529439/20230301221508/ufs-weather-model
[RT] Error: Test control_c384 026 failed in check_result failed 
[RT] Error: Test control_c384 026 failed in run_test failed 
[RT] Error: Test control_p8_rrtmgp 038 failed in check_result failed 
[RT] Error: Test control_p8_rrtmgp 038 failed in run_test failed 
Please make changes and add the following label back: cheyenne-intel-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1259529439/20230302051511/ufs-weather-model
[RT] Error: Test control_p8_rrtmgp 040 failed in check_result failed 
[RT] Error: Test control_p8_rrtmgp 040 failed in run_test failed 
Please make changes and add the following label back: hera-intel-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1259529439/20230302173015/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1259529439/20230302183417/ufs-weather-model
Please make changes and add the following label back: hera-intel-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1259529439/20230302103009/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1259529439/20230302113850/ufs-weather-model
Please make changes and add the following label back: cheyenne-intel-BL

**Pull request merged**
