### PR TITLE
Changes in FV3/ccpp-physics for prognostic cloud closure scheme.

### PR DESCRIPTION
**Pull request by dustinswales**
Opened by @dustinswales on behalf of @lisa-bengtsson

This PR corrects a bug when using the prognostic closure (progsigma = true) to compute the q-tendency due to microphysics even if the diagnostic flags are false. It also optimizes the cloudbase massflux value for shallow and deep convection to work with the overall P8 physics suite.

New baselines are needed for the test: control_c384_progsigma

This update does not change the results in the control tests.

###issues
It addresses the issue: https://github.com/NCAR/ccpp-physics/issues/960

###dependencies
https://github.com/NCAR/ccpp-physics/pull/967

### CODE REVIEW

**Comment by lisa-bengtsson** [comment]
@dustinswales I'm not really following the changes with the new fork and the two parallel UFS/NCAR repositories. My submodule pointers are currently pointing to my fork of ufs-weather-model, fv3atm and ccpp-physics. Those were forked from ufs-community/ufs-weather-model, NOAA-EMC/fv3atm, and NCAR/ccpp-physics. My remotes are set to:

[Lisa.Bengtsson@hfe09 ufs-weather-model-PR]$ git remote -v
origin	https://github.com/lisa-bengtsson/ufs-weather-model (fetch)
origin	https://github.com/lisa-bengtsson/ufs-weather-model (push)
upstream	https://github.com/ufs-community/ufs-weather-model (fetch)
upstream	https://github.com/ufs-community/ufs-weather-model (push)

[Lisa.Bengtsson@hfe09 FV3]$ git remote -v
origin	https://github.com/lisa-bengtsson/fv3atm (fetch)
origin	https://github.com/lisa-bengtsson/fv3atm (push)
upstream	https://github.com/NOAA-EMC/fv3atm (fetch)
upstream	https://github.com/NOAA-EMC/fv3atm (push)

[Lisa.Bengtsson@hfe09 physics]$ git remote -v
origin	https://github.com/lisa-bengtsson/ccpp-physics (fetch)
origin	https://github.com/lisa-bengtsson/ccpp-physics (push)
upstream	https://github.com/NCAR/ccpp-physics (fetch)
upstream	https://github.com/NCAR/ccpp-physics (push)

Do I need to change my upstreams now when things are moved to NCAR? When I merge with the upstream code I usually do:

> git fetch upstream
> git pull upstream develop (or main)

Thanks for your help!
Lisa

**Comment by grantfirl** [comment]
> @lisa-bengtsson Once the PR is merged, you will need to add new upstreams for the NCAR forked repos so that you can update your working code base.
> 
> In FV3, git remote add upstream_ NCAR https://github.com/NCAR/fv3atm In ufs-community, git remote add upstream_NCAR https://github.com/NCAR/ufs-weather-model.git Then git fetch upstream_NCAR, git pull...
> 
> When the ccpp forks are "synced" next week, you can go back to just updating (fetch and pull) from "upstream".
> 
> @grantfirl Did I omit anything?

No, I think that should be sufficient. @lisa-bengtsson, if you do as @dustinswales suggested, that will give you ultimate flexibility to update from either the ufs-community/ufs/dev branch or NCAR/main. Since your work is highly geared toward the UFS, I would think that all future PRs should be targeted toward ufs/dev to avoid the (newly-added) processes of going into NCAR/main first, then ufs/dev like we're doing for this current PR. Unless there is something specific in NCAR/main that you need (that is not also in ufs/dev), future code change branches that you create should begin from the latest ufs/dev branch.

**Comment by lisa-bengtsson** [comment]
yeah, I agree that this should be in ufs/dev, the PR was committed just before the new fork was included. 

I will wait until I hear more from you regarding merge into NCAR/ccpp-physics. 

Thanks

**Comment by dustinswales** [comment]
@lisa-bengtsson I'm running the RT's today. If all the tests pass, with the exception of control_c384_progsigma, I will merge your PR. Then I will need you to update your submodule in fv3atm and we'll be done.
Sorry for any confusion this new process has caused.

**Comment by lisa-bengtsson** [comment]
Not your fault Swales! Poor timing on my end... it should be doable. Thanks!

**Review by grantfirl — APPROVED** [review]
Need to revert .gitmodules, but otherwise OK.

**Pull request merged**
