### PR TITLE
UFS testing for HWRF Noah and GFDL surface layer

### PR DESCRIPTION
**Pull request by grantfirl**
- add UFS RTs for the GFS_v15p2 suite with drop-in HWRF LSM and SL components, add HWRF test for C96
- namelists in parm should be temporary for testing purposes and can be removed before HWRF physics goes to master
- tests in tests/tests should be temporary too
- this PR includes tests for operational + HWRF Noah, operational + GFDL surface layer, operational + both HWRF Noah and GFDL surface layer, and my best attempt at the entire HWRF suite; all but the entire HWRF suite should likely be removed before going to master

- using HWRF Noah requires use of its table files (VEGPARM.TBL, SOILPARM.TBL, GENPARM.TLB) from WRF as fix files (attached in this PR)
- although several namelist options were added, it is important to set:
  - lsm = 4 to match the SDF when using HWRF Noah
  - sfc_z0_type = X (4 was tested and appears to be what is used in HWRF)
  - fhcyc = 0 (likely temporary until this can be tested/checked with surface cycling on)

This supercedes #37

### CODE REVIEW

**Comment by grantfirl** [comment]
Regression testing log:
[rt_full.log](https://github.com/NCAR/ufs-weather-model/files/4645683/rt_full.log)

All tests passed except for the new tests, which have MISSING_BASELINE

**Comment by grantfirl** [comment]
Associated PRs:
https://github.com/NCAR/ccpp-physics/pull/452
https://github.com/NCAR/fv3atm/pull/49
https://github.com/NCAR/ufs-weather-model/pull/47

**Comment by grantfirl** [comment]
Please see https://drive.google.com/open?id=1MTtmb-w8zhq_I_LHADgf03bbrAWQ8uCP for quick/dirty ncview plots displaying surface quantities between the operational GFS suite (control), control + HWRF LSM, control + HWRF SL (surface layer), HWRF complete. All suites look reasonable to me. An issue was noted with 2m diagnostics that can be addressed in a followup PR.

**Comment by climbfuji** [comment]
These PRs look ok to me, noting the follow-up changes that need to be made and the temporary nature of several of the files in `parm`, `tests/fv3_conv`, `tests/tests`, `FV3/ccpp/suites`.

@grantfirl 
(1) I don't see the attached files (`VEGPARM.TBL`, `SOILPARM.TBL`, `GENPARM.TLB`) in this PR. You can also stage them on hera or cheyenne for me.
(2) I would like to run tests on Cheyenne with Intel and GNU as well. I will send you updates for `rt_intel.conf` and `rt_gnu.conf`
(3) I will create new baselines on both Hera and Cheyenne afterwards. Once this is done, you need to update the date tag in `rt.sh` and we rerun all tests (to make sure all pass).

**Comment by climbfuji** [comment]
@grantfirl I just realized that your PRs are not up to date with the head of dtc/hwrf-physics. I can create additional PRs that pull your PRs into the head of dtc/hwrf-physics for each of the repositories, or you can do that and update your PRs. If you do so, please also:

- in fv3atm, change .gitmodules to point ccpp-physics to your fork and branch, and commit together with the submodule pointer update for ccpp-physics
- in ufs-weather-model, change .gitmodules to point fv3atm to your fork and branch, and commit together with the submodule pointer update for fv3atm

Let me know what you prefer, please.

**Comment by grantfirl** [comment]
> @grantfirl I just realized that your PRs are not up to date with the head of dtc/hwrf-physics. I can create additional PRs that pull your PRs into the head of dtc/hwrf-physics for each of the repositories, or you can do that and update your PRs. If you do so, please also:
> 
> * in fv3atm, change .gitmodules to point ccpp-physics to your fork and branch, and commit together with the submodule pointer update for ccpp-physics
> * in ufs-weather-model, change .gitmodules to point fv3atm to your fork and branch, and commit together with the submodule pointer update for fv3atm
> 
> Let me know what you prefer, please.

I will do so.

**Comment by grantfirl** [comment]
Here are the data files for HWRF Noah LSM. When I was poking around some FV3_input directories, I thought that I may have already seen files with these names. I'm not sure if they're identical to the attached ones or not.
[HWRF_NOAH_data.zip](https://github.com/NCAR/ufs-weather-model/files/4698347/HWRF_NOAH_data.zip)

**Comment by grantfirl** [comment]
@climbfuji I just ran the rt.conf tests for a some code changes that were going to be part of a followup PR (also used code from dtc/hwrf-physics that was from May 4). Rather than doing a followup PR, since the regression tests need to be rerun, should I just combine what was going to be the followup changes into this PR? Hopefully, it will simplify regression testing.

**Comment by climbfuji** [comment]
> @climbfuji I just ran the rt.conf tests for a some code changes that were going to be part of a followup PR (also used code from dtc/hwrf-physics that was from May 4). Rather than doing a followup PR, since the regression tests need to be rerun, should I just combine what was going to be the followup changes into this PR? Hopefully, it will simplify regression testing.

Sure, I haven't started running the tests yet. If you do update the ccpp-physics PR, please make sure to also update the submodule pointer in fv3atm (so that it doesn't say "new commits" anymore).

**Comment by climbfuji** [comment]
> HWRF_NOAH_data.zip

For each of these files, a version exists in the `FV3_input_data` directory of the regression test baseline. However, they are all different from the ones in the zip file. What is your suggested name for the additional input data? Should it go into `FV3_input_data_hafs` or into a new directory `FV3_input_data_XYZ` ?

**Comment by grantfirl** [comment]
> > HWRF_NOAH_data.zip
> 
> For each of these files, a version exists in the `FV3_input_data` directory of the regression test baseline. However, they are all different from the ones in the zip file. What is your suggested name for the additional input data? Should it go into `FV3_input_data_hafs` or into a new directory `FV3_input_data_XYZ` ?

Since these files were taken directly from WRFv4, maybe prepend or append WRFv4? IMO, they can go in FV3_input_data_hafs.

**Comment by grantfirl** [comment]
OK, @climbfuji, all PRs have been updated to have the latest dtc/hwrf-physics, the .gitmodules have been changed, and I merged in the followup ccpp-physics changes. This should be ready to test. Should I go ahead and kick off the rt.conf test again on Hera for this?

**Comment by climbfuji** [comment]
> OK, @climbfuji, all PRs have been updated to have the latest dtc/hwrf-physics, the .gitmodules have been changed, and I merged in the followup ccpp-physics changes. This should be ready to test. Should I go ahead and kick off the rt.conf test again on Hera for this?

Thanks, @grantfirl. Since I need to create a new baseline on hera as well, you can also leave those tests to me. I'll put the new TBL files in the `FV3_input_data_hafs` directory.

**Comment by climbfuji** [comment]
@grantfirl I don't see the fv3atm submodule pointer update in this PR.

**Comment by grantfirl** [comment]
> > OK, @climbfuji, all PRs have been updated to have the latest dtc/hwrf-physics, the .gitmodules have been changed, and I merged in the followup ccpp-physics changes. This should be ready to test. Should I go ahead and kick off the rt.conf test again on Hera for this?
> 
> Thanks, @grantfirl. Since I need to create a new baseline on hera as well, you can also leave those tests to me. I'll put the new TBL files in the `FV3_input_data_hafs` directory.

OK, great. I will at least compile it there. I haven't done that since updating to dtc/hwrf-physics.

**Comment by grantfirl** [comment]
It compiles OK, but now I'm getting the following runtime error:

fv3.exe: libccppphys.so.3: cannot open shared object file: No such file or directory
 86:  ERROR: A problem occured loading GFS_time_vary_pre_init from ccppphys
 86:  ERROR: In initializing the CCPP suite
 86:
 86: FATAL from PE    86:  atmosphere_dynamics: error in ccpp_init:

**Comment by climbfuji** [comment]
Hmm. We don't have the dynamic CCPP build anymore. This is weird. Did you try to run the job manually in some "old" run directory, or kick off the regression tests?

**Comment by climbfuji** [comment]
It compiles fine with both Intel and GNU in PROD mode, and I also tried with GNU in DEBUG mode. Will kick off the regression tests and see if I get the same error as you.

**Comment by grantfirl** [comment]
I copied rt.conf and deleted everything except compiling with the new HWRF suites and running. I have no idea what happened.

**Comment by climbfuji** [comment]
It seems to work fine for me on Cheyenne with both Intel and GNU, will test hera later tonight.

**Comment by climbfuji** [comment]
Regression testing on cheyenne.gnu, based on the changes in https://github.com/grantfirl/ufs-weather-model/pull/1 (**NEEDS TO BE MERGED before this PR can be merged**):

1. run regression tests in `tests/rt_gnu.conf` against existing baseline: all existing tests pass, all new tests fail (as expected; missing baseline)

[rt_cheyenne_gnu_verify_against_existing_baseline.log](https://github.com/NCAR/ufs-weather-model/files/4702637/rt_cheyenne_gnu_verify_against_existing_baseline.log)
[rt_cheyenne_gnu_verify_against_existing_baseline_fail_test.log](https://github.com/NCAR/ufs-weather-model/files/4702638/rt_cheyenne_gnu_verify_against_existing_baseline_fail_test.log)


2. create new baseline using `tests/rt_gnu.conf`, including the additional tables in `FV3_input_data_hafs`: all tests pass

[rt_cheyenne_gnu_create_new_baseline.log](https://github.com/NCAR/ufs-weather-model/files/4702636/rt_cheyenne_gnu_create_new_baseline.log)


3. copy this new, temporary baseline to the final location (new date tag 20200528)

4. verify against this baseline using `tests/rt_gnu.conf`: all tests pass

[rt_cheyenne_gnu_verify_against_new_baseline.log](https://github.com/NCAR/ufs-weather-model/files/4702633/rt_cheyenne_gnu_verify_against_new_baseline.log)

**Comment by climbfuji** [comment]
Regression testing on cheyenne.intel, based on the changes in https://github.com/grantfirl/ufs-weather-model/pull/1 (**NEEDS TO BE MERGED before this PR can be merged**):

1. run regression tests in `tests/rt_intel.conf` against existing baseline: all existing tests pass, except for the known issues (see 4.), all new tests fail (as expected; missing baseline)

[rt_cheyenne_intel_verify_against_existing_baseline.log](https://github.com/NCAR/ufs-weather-model/files/4702643/rt_cheyenne_intel_verify_against_existing_baseline.log)
[rt_cheyenne_intel_verify_against_existing_baseline_fail_test.log](https://github.com/NCAR/ufs-weather-model/files/4702644/rt_cheyenne_intel_verify_against_existing_baseline_fail_test.log)

2. create new baseline using `tests/rt_intel.conf`, including the additional tables in `FV3_input_data_hafs`: all tests pass

[rt_cheyenne_intel_create_new_baseline.log](https://github.com/NCAR/ufs-weather-model/files/4702648/rt_cheyenne_intel_create_new_baseline.log)


3. copy this new, temporary baseline to the final location (new date tag 20200528)

4. verify against this baseline using `tests/rt_intel.conf`: all tests pass, except the known issues:

[rt_cheyenne_intel_verify_against_new_baseline.log](https://github.com/NCAR/ufs-weather-model/files/4702652/rt_cheyenne_intel_verify_against_new_baseline.log)
[rt_cheyenne_intel_verify_against_new_baseline_fail_test.log](https://github.com/NCAR/ufs-weather-model/files/4702655/rt_cheyenne_intel_verify_against_new_baseline_fail_test.log)

```
heinzell@cheyenne1:/glade/work/heinzell/fv3/ufs-weather-model/ufs-weather-model-dtc-hwrf-physics-20200527-add-hwrf-noahlsm-and-gfdl-sfclay/intel/tests> grep -e FAIL log_cheyenne.intel/*
log_cheyenne.intel/rt_029_fv3_ccpp_regional_c768_FA_prod.log:Test 029 fv3_ccpp_regional_c768_FA FAIL
log_cheyenne.intel/rt_030_fv3_ccpp_regional_c768_HWRF_PBL_prod.log:Test 030 fv3_ccpp_regional_c768_HWRF_PBL FAIL
log_cheyenne.intel/rt_031_fv3_ccpp_regional_c768_FA_HWRF_RRTMG_prod.log:Test 031 fv3_ccpp_regional_c768_FA_HWRF_RRTMG FAIL
log_cheyenne.intel/rt_043_fv3_ccpp_regional_c768_FA_repro.log:Test 043 fv3_ccpp_regional_c768_FA FAIL
log_cheyenne.intel/rt_044_fv3_ccpp_regional_c768_HWRF_PBL_repro.log:Test 044 fv3_ccpp_regional_c768_HWRF_PBL FAIL
log_cheyenne.intel/rt_045_fv3_ccpp_regional_c768_FA_HWRF_RRTMG_repro.log:Test 045 fv3_ccpp_regional_c768_FA_HWRF_RRTMG FAIL
```

**Comment by climbfuji** [comment]
Regression testing on hera.intel, based on the changes in https://github.com/grantfirl/ufs-weather-model/pull/1 (**NEEDS TO BE MERGED before this PR can be merged**):

1. run regression tests in `tests/rt.conf` against existing baseline: all existing tests pass, all new tests fail (as expected; missing baseline)

[rt_hera_intel_verify_against_existing_baseline.log](https://github.com/NCAR/ufs-weather-model/files/4702663/rt_hera_intel_verify_against_existing_baseline.log)
[rt_hera_intel_verify_against_existing_baseline_fail_test.log](https://github.com/NCAR/ufs-weather-model/files/4702665/rt_hera_intel_verify_against_existing_baseline_fail_test.log)

2. create new baseline using `tests/rt.conf`, including the additional tables in `FV3_input_data_hafs`: all tests pass

[rt_hera_intel_create_new_baseline.log](https://github.com/NCAR/ufs-weather-model/files/4702668/rt_hera_intel_create_new_baseline.log)

3. copy this new, temporary baseline to the final location (new date tag 20200528)

4. verify against this baseline using `tests/rt.conf`: **STILL RUNNING**

**Comment by grantfirl** [comment]
Thanks very much @climbfuji for guiding me through the testing/review/merge process. You're a true pro as always!

**Comment by climbfuji** [comment]
Thanks for these code changes - all clean and straightforward!

**Comment by mzhangw** [comment]
Just to confirm, it looks like that dtc/hwrf-physics is ready for HWRF physics suite test?

**Comment by grantfirl** [comment]
@mzhangw Yes.

**Pull request merged**
