### PR TITLE
UFS-dev PR#40

### PR DESCRIPTION
**Pull request by dustinswales**
Identical to [#1597](https://github.com/ufs-community/ufs-weather-model/pull/1597)

### CODE REVIEW

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1259860451/20230320120014/ufs-weather-model
[RT] Error: Test compile_012 failed in run_compile failed 
Please make changes and add the following label back: cheyenne-gnu-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: RT
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1259860451/20230320180013/ufs-weather-model
[RT] Error: Test compile_012 failed in run_compile failed 
Please make changes and add the following label back: hera-gnu-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1259860451/20230320124109/ufs-weather-model
[RT] Error: Test cpld_control_c192_p8 009 failed in run_test failed 
[RT] Error: Test rap_sfcdiff 052 failed in check_result failed 
[RT] Error: Test rap_sfcdiff 052 failed in run_test failed 
[RT] Error: Test rap_sfcdiff_decomp 053 failed in check_result failed 
[RT] Error: Test rap_sfcdiff_decomp 053 failed in run_test failed 
[RT] Error: Test hafs_regional_atm_wav 112 failed in run_test failed 
[RT] Error: Test hafs_regional_atm_ocn_wav 113 failed in run_test failed 
[RT] Error: Test hafs_global_multiple_4nests_atm 117 failed in run_test failed 
[RT] Error: Test hafs_regional_storm_following_1nest_atm_ocn_debug 122 failed in run_test failed 
[RT] Error: Test hafs_regional_storm_following_1nest_atm_ocn_wav 123 failed in run_test failed 
[RT] Error: Test atmaero_control_p8 145 failed in run_test failed 
[RT] Error: Test atmaero_control_p8_rad 146 failed in run_test failed 
[RT] Error: Test atmaero_control_p8_rad_micro 147 failed in run_test failed 
[RT] Error: Test regional_atmaq 148 failed in run_test failed 
[RT] Error: Test compile_021 failed in run_compile failed 
[RT] Error: Test compile_022 failed in run_compile failed 
[RT] Error: Test compile_023 failed in run_compile failed 
[RT] Error: Test compile_024 failed in run_compile failed 
Please make changes and add the following label back: cheyenne-intel-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1259860451/20230320193344/ufs-weather-model
[RT] Error: Test compile_021 failed in run_compile failed 
[RT] Error: Test compile_022 failed in run_compile failed 
[RT] Error: Test compile_023 failed in run_compile failed 
[RT] Error: Test compile_024 failed in run_compile failed 
Please make changes and add the following label back: hera-intel-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1259860451/20230320212229/ufs-weather-model
[RT] Error: Test rap_sfcdiff 052 failed in check_result failed 
[RT] Error: Test rap_sfcdiff 052 failed in run_test failed 
[RT] Error: Test rap_sfcdiff_decomp 053 failed in check_result failed 
[RT] Error: Test rap_sfcdiff_decomp 053 failed in run_test failed 
Please make changes and add the following label back: cheyenne-intel-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1259860451/20230321143008/ufs-weather-model
[RT] Error: Test rap_sfcdiff 052 failed in check_result failed 
[RT] Error: Test rap_sfcdiff 052 failed in run_test failed 
[RT] Error: Test rap_sfcdiff_decomp 053 failed in check_result failed 
[RT] Error: Test rap_sfcdiff_decomp 053 failed in run_test failed 
Please make changes and add the following label back: cheyenne-intel-RT

**Comment by dustinswales** [comment]
@grantfirl I can't figure this one out. All of the rap_sfcdiff tests pass except for Cheyenne Intel?
GNU and Intel are using the same input data, so it's not that.
Any ideas?

**Comment by dustinswales** [comment]
@grantfirl All tests have passed. Can you approve?

**Review by grantfirl — APPROVED** [review]

**Comment by grantfirl** [comment]
Sorry I didn't have a chance to look at the issue. Since there were no new commits, was it just a machine problem?

**Comment by dustinswales** [comment]
> Sorry I didn't have a chance to look at the issue. Since there were no new commits, was it just a machine problem?

I ran it manually w/o issue. So I'm assuming a machine problem.

**Pull request merged**
