### PR TITLE
UFS-dev PR#26

### PR DESCRIPTION
**Pull request by grantfirl**
Identical to https://github.com/ufs-community/ufs-weather-model/pull/1509
- also contains https://github.com/ufs-community/ufs-weather-model/pull/1702

The following RTs are expected to fail:
control_flake
hrrr_control
hrrr_control_decomp
hrrr_control_2threads
hrrr_control_restart
hrrr_control_debug
rap_clm_lake_debug
rap_flake_debug
hrrr_control_dyn32_phy32
hrrr_control_2threads_dyn32_phy32
hrrr_control_decomp_dyn32_phy32
hrrr_control_restart_dyn32_phy32
hrrr_control_debug_dyn32_phy32

### CODE REVIEW

**Comment by grantfirl** [comment]
@mkavulich This has finished testing. It is ready for merging once approved along with https://github.com/NCAR/fv3atm/pull/95, https://github.com/NCAR/ccpp-physics/pull/1016, and https://github.com/NCAR/ccpp-scm/pull/387.

**Review by mkavulich — APPROVED** [review]
Approving. I have some questions about the specifics of what was changed here but that's more appropriate for discussion in the ufs-community repo.

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
Please make changes and add the following label back: hera-intel-RT

**Comment by mkavulich** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1344127077/20230628231623/ufs-weather-model
Please make changes and add the following label back: hera-intel-RT

**Pull request merged**
