### PR TITLE
UFS-dev PR#173

### PR DESCRIPTION
**Pull request by grantfirl**
Identical to https://github.com/ufs-community/ufs-weather-model/pull/2137 (BL changes)

Also contains:
https://github.com/ufs-community/ufs-weather-model/pull/2028 (new RTs and input data)
https://github.com/ufs-community/ufs-weather-model/pull/2005 (new RTs and input data)
https://github.com/ufs-community/ufs-weather-model/pull/2113 (BL changes)
https://github.com/ufs-community/ufs-weather-model/pull/2115 (no BL changes)
https://github.com/ufs-community/ufs-weather-model/pull/2118 (BL changes)
https://github.com/ufs-community/ufs-weather-model/pull/2062 (BL changes)
https://github.com/ufs-community/ufs-weather-model/pull/2061 (no BL changes)
https://github.com/ufs-community/ufs-weather-model/pull/2066 (no BL changes)

### CODE REVIEW

**Comment by grantfirl** [comment]
2028 info:
Two new subdirs (MOM6_regional_input_data and CDEPS_input_data) were added inside the FV3_hafs_input_data dir. Adding these two subdirs will not affect any existing RTs. They are only used for the newly added two RTs in this PR.

With that, please help to copy over the following dirs:
/scratch1/NCEPDEV/stmp4/Bin.Liu/hafs/NEMSfv3gfs/input-data-20221101/FV3_hafs_input_data/MOM6_regional_input_data
/scratch1/NCEPDEV/stmp4/Bin.Liu/hafs/NEMSfv3gfs/input-data-20221101/FV3_hafs_input_data/CDEPS_input_data
inside the existing NEMSfv3gfs/input-data-20221101/FV3_hafs_input_data/, and then populate them to all supported platforms. Again, no need to change the input-data-20221101 version.

The following two new RTs were added for HAFS regional moving nest coupling through CMEPS with inline CDEPS: hafs_regional_storm_following_1nest_atm_ocn_wav_inline and hafs_regional_storm_following_1nest_atm_ocn_wav_mom6

**Comment by grantfirl** [comment]
2005 info:

new input data:
control_c48.v2.sfc - ./FV3_input_data48/INPUT_L127.v2.sfc
control_p8.v2.sfc - ./FV3_input_data/INPUT_L127.v2.sfc
cpld_control_p8.v2.sfc - ./FV3_input_data/INPUT_L127_mx100.v2.sfc

new RTs:
Three new regression tests based on the existing 'control_c48', 'control_p8' and 'cpld_control_p8' tests

**Comment by grantfirl** [comment]
expected failures for 2113:
regional_wofs_intel 063
rrfs_v1nssl_intel 077
rrfs_v1nssl_nohailnoccn_intel 078

**Comment by grantfirl** [comment]
expected failures for 2118:
cpld_control_gfsv17_iau_intel

**Comment by grantfirl** [comment]
expected failures for 2062:
control_CubedSphereGrid_parallel

**Comment by grantfirl** [comment]
expected failures for 2137:
cpld_control_p8_mixedmode intel
cpld_control_gfsv17 intel
cpld_control_gfsv17_iau intel
cpld_restart_gfsv17 intel
cpld_mpi_gfsv17 intel
cpld_debug_gfsv17 intel
cpld_control_p8 intel
cpld_control_p8.v2.sfc intel
cpld_restart_p8 intel
cpld_control_qr_p8 intel
cpld_restart_qr_p8 intel
cpld_2threads_p8 intel
cpld_decomp_p8 intel
cpld_mpi_p8 intel
cpld_control_ciceC_p8 intel
cpld_control_c192_p8 intel
cpld_restart_c192_p8 intel
cpld_bmark_p8 intel
cpld_restart_bmark_p8 intel
cpld_s2sa_p8 intel
cpld_control_noaero_p8 intel
cpld_control_nowave_noaero_p8 intel
cpld_debug_p8 intel
cpld_debug_noaero_p8 intel
cpld_control_noaero_p8_agrid intel
cpld_control_c48 intel
cpld_control_p8_faster intel
cpld_control_pdlib_p8 intel
cpld_restart_pdlib_p8 intel
cpld_mpi_pdlib_p8 intel
cpld_debug_pdlib_p8 intel
control_flake intel
control_CubedSphereGrid intel
control_CubedSphereGrid_parallel intel
control_latlon intel
control_wrtGauss_netcdf_parallel intel
control_c48 intel
control_c48.v2.sfc intel
control_c192 intel
control_c384 intel
control_c384gdas intel
control_stochy intel
control_stochy_restart intel
control_lndp intel
control_iovr4 intel
control_iovr5 intel
control_p8 intel
control_p8.v2.sfc intel
control_p8_ugwpv1 intel
control_restart_p8 intel
control_noqr_p8 intel
control_restart_noqr_p8 intel
control_decomp_p8 intel
control_2threads_p8 intel
control_p8_lndp intel
control_p8_rrtmgp intel
control_p8_mynn intel
merra2_thompson intel
rap_control intel
rap_decomp intel
rap_2threads intel
rap_restart intel
rap_sfcdiff intel
rap_sfcdiff_decomp intel
rap_sfcdiff_restart intel
hrrr_control intel
hrrr_control_decomp intel
hrrr_control_2threads intel
hrrr_control_restart intel
rrfs_v1beta intel
rrfs_v1nssl intel
rrfs_v1nssl_nohailnoccn intel
control_csawmg intel
control_csawmgt intel
control_ras intel
control_wam intel
control_p8_faster intel
control_CubedSphereGrid_debug intel
control_wrtGauss_netcdf_parallel_debug intel
control_stochy_debug intel
control_lndp_debug intel
control_csawmg_debug intel
control_csawmgt_debug intel
control_ras_debug intel
control_diag_debug intel
control_debug_p8 intel
rap_control_debug intel
hrrr_control_debug intel
hrrr_gf_debug intel
hrrr_c3_debug intel
rap_unified_drag_suite_debug intel
rap_diag_debug intel
rap_cires_ugwp_debug intel
rap_unified_ugwp_debug intel
rap_lndp_debug intel
rap_progcld_thompson_debug intel
rap_noah_debug intel
rap_sfcdiff_debug intel
rap_noah_sfcdiff_cires_ugwp_debug intel
rrfs_v1beta_debug intel
rap_clm_lake_debug intel
rap_flake_debug intel
gnv1_c96_no_nest_debug intel
control_wam_debug intel
rap_control_dyn32_phy32 intel
hrrr_control_dyn32_phy32 intel
rap_2threads_dyn32_phy32 intel
hrrr_control_2threads_dyn32_phy32 intel
hrrr_control_decomp_dyn32_phy32 intel
rap_restart_dyn32_phy32 intel
hrrr_control_restart_dyn32_phy32 intel
conus13km_control intel
conus13km_2threads intel
conus13km_restart_mismatch intel
rap_control_dyn64_phy32 intel
rap_control_debug_dyn32_phy32 intel
hrrr_control_debug_dyn32_phy32 intel
conus13km_debug intel
conus13km_debug_qr intel
conus13km_debug_2threads intel
conus13km_radar_tten_debug intel
rap_control_dyn64_phy32_debug intel
hafs_global_1nest_atm intel
hafs_global_multiple_4nests_atm intel
hafs_global_storm_following_1nest_atm intel
gnv1_nested intel
control_p8_atmlnd_sbs intel
control_p8_atmlnd intel
control_restart_p8_atmlnd intel
atmwav_control_noaero_p8 intel
control_atmwav intel
atmaero_control_p8 intel
atmaero_control_p8_rad intel
atmaero_control_p8_rad_micro intel
control_c48 gnu
control_stochy gnu
control_ras gnu
control_p8 gnu
control_p8_ugwpv1 gnu
control_flake gnu
rap_control gnu
rap_decomp gnu
rap_2threads gnu
rap_restart gnu
rap_sfcdiff gnu
rap_sfcdiff_decomp gnu
rap_sfcdiff_restart gnu
hrrr_control gnu
hrrr_control_noqr gnu
hrrr_control_2threads gnu
hrrr_control_decomp gnu
hrrr_control_restart gnu
hrrr_control_restart_noqr gnu
rrfs_v1beta gnu
control_diag_debug gnu
rap_control_debug gnu
hrrr_control_debug gnu
hrrr_gf_debug gnu
hrrr_c3_debug gnu
rap_diag_debug gnu
rap_noah_sfcdiff_cires_ugwp_debug gnu
rap_progcld_thompson_debug gnu
rrfs_v1beta_debug gnu
control_ras_debug gnu
control_stochy_debug gnu
control_debug_p8 gnu
rap_flake_debug gnu
rap_clm_lake_debug gnu
gnv1_c96_no_nest_debug gnu
control_wam_debug gnu
rap_control_dyn32_phy32 gnu
hrrr_control_dyn32_phy32 gnu
rap_2threads_dyn32_phy32 gnu
hrrr_control_2threads_dyn32_phy32 gnu
hrrr_control_decomp_dyn32_phy32 gnu
rap_restart_dyn32_phy32 gnu
hrrr_control_restart_dyn32_phy32 gnu
conus13km_control gnu
conus13km_2threads gnu
conus13km_restart_mismatch gnu
rap_control_dyn64_phy32 gnu
rap_control_debug_dyn32_phy32 gnu
hrrr_control_debug_dyn32_phy32 gnu
conus13km_debug gnu
conus13km_debug_qr gnu
conus13km_debug_2threads gnu
conus13km_radar_tten_debug gnu
rap_control_dyn64_phy32_debug gnu
cpld_control_p8 gnu
cpld_control_nowave_noaero_p8 gnu
cpld_debug_p8 gnu
cpld_control_pdlib_p8 gnu
cpld_debug_pdlib_p8 gnu

**Comment by grantfirl** [comment]
@mkavulich The new input data was copied into /scratch1/BMC/gmtb/CCPP_regression_testing/NCAR_ufs-weather-model/input_data/20230920

**Review by mkavulich — APPROVED** [review]
I notice that the FV3 submodule isn't pointing to your fork/branch for https://github.com/NCAR/fv3atm/pull/126. I suppose it doesn't matter since we aren't running the regression testing, but I thought I'd point it out in case it was unintentional.

**Pull request merged**
