### PR TITLE
UFS-dev PR#75

### PR DESCRIPTION
**Pull request by grantfirl**
Identical to https://github.com/ufs-community/ufs-weather-model/pull/1851 (no BL change)

Also contains
 - https://github.com/ufs-community/ufs-weather-model/pull/1932 (no BL change)
 - https://github.com/ufs-community/ufs-weather-model/pull/1920 (no BL change)
 - https://github.com/ufs-community/ufs-weather-model/pull/1907 (BL change)
 - https://github.com/ufs-community/ufs-weather-model/pull/1922 (BL change)
 - https://github.com/ufs-community/ufs-weather-model/pull/1923 (BL change)

### CODE REVIEW

**Comment by grantfirl** [comment]
Remember to edit the files in tests/machine to correspond to the changes in rt.sh in this PR!

**Comment by grantfirl** [comment]
https://github.com/ufs-community/ufs-weather-model/pull/1907 RT changes:

regional_atmaq_faster will be added on both Acorn and WCOSS2 bring back baselines for: - hafs_regional_docn - hafs_regional_docs_oisst - hafs_regional_datm_cdeps

**Comment by grantfirl** [comment]
https://github.com/ufs-community/ufs-weather-model/pull/1922 RT changes:

001 cpld_control_p8_mixedmode_intel failed in check_result
007 cpld_control_p8_intel failed in check_result
009 cpld_control_qr_p8_intel failed in check_result
011 cpld_2threads_p8_intel failed in check_result
012 cpld_decomp_p8_intel failed in check_result
013 cpld_mpi_p8_intel failed in check_result
014 cpld_control_ciceC_p8_intel failed in check_result
015 cpld_control_c192_p8_intel failed in check_result
017 cpld_bmark_p8_intel failed in check_result
021 cpld_debug_p8_intel failed in check_result
025 cpld_control_p8_faster_intel failed in check_result
178 atmaero_control_p8_intel failed in check_result
179 atmaero_control_p8_rad_intel failed in check_result
180 atmaero_control_p8_rad_micro_intel failed in check_result
240 cpld_control_p8_gnu failed in check_result
242 cpld_debug_p8_gnu failed in check_result

**Comment by grantfirl** [comment]
https://github.com/ufs-community/ufs-weather-model/pull/1923 RT changes:

cpld_control_p8_mixedmode_intel 001 failed in run_test
cpld_control_gfsv17_intel 002 failed in run_test
cpld_mpi_gfsv17_intel 005 failed in run_test
cpld_debug_gfsv17_intel 006 failed in run_test
cpld_control_p8_intel 007 failed in run_test
cpld_control_qr_p8_intel 009 failed in run_test
cpld_2threads_p8_intel 011 failed in run_test
cpld_decomp_p8_intel 012 failed in run_test
cpld_mpi_p8_intel 013 failed in run_test
cpld_control_ciceC_p8_intel 014 failed in run_test
cpld_control_c192_p8_intel 015 failed in run_test
cpld_bmark_p8_intel 017 failed in run_test
cpld_control_noaero_p8_intel 019 failed in run_test
cpld_control_nowave_noaero_p8_intel 020 failed in run_test
cpld_debug_p8_intel 021 failed in run_test
cpld_debug_noaero_p8_intel 022 failed in run_test
cpld_control_noaero_p8_agrid_intel 023 failed in run_test
cpld_control_c48_intel 024 failed in run_test
cpld_control_p8_faster_intel 025 failed in run_test
cpld_control_pdlib_p8_intel 026 failed in run_test
cpld_debug_pdlib_p8_intel 029 failed in run_test
control_p8_intel 044 failed in run_test
control_p8_ugwpv1_intel 045 failed in run_test
control_qr_p8_intel 047 failed in run_test
control_decomp_p8_intel 049 failed in run_test
control_2threads_p8_intel 050 failed in run_test
control_p8_lndp_intel 051 failed in run_test
control_p8_rrtmgp_intel 052 failed in run_test
control_p8_mynn_intel 053 failed in run_test
merra2_thompson_intel 054 failed in run_test
rap_control_intel 065 failed in run_test
rap_decomp_intel 067 failed in run_test
rap_2threads_intel 068 failed in run_test
rap_sfcdiff_intel 070 failed in run_test
rap_sfcdiff_decomp_intel 071 failed in run_test
hrrr_control_intel 073 failed in run_test
hrrr_control_qr_intel 074 failed in run_test
hrrr_control_decomp_intel 075 failed in run_test
hrrr_control_2threads_intel 076 failed in run_test
rrfs_v1beta_intel 079 failed in run_test
rrfs_v1nssl_intel 080 failed in run_test
rrfs_v1nssl_nohailnoccn_intel 081 failed in run_test
control_p8_faster_intel 086 failed in run_test
control_debug_p8_intel 096 failed in run_test
rap_control_debug_intel 098 failed in run_test
hrrr_control_debug_intel 099 failed in run_test
hrrr_gf_debug_intel 100 failed in run_test
hrrr_c3_debug_intel 101 failed in run_test
rap_unified_drag_suite_debug_intel 102 failed in run_test
rap_diag_debug_intel 103 failed in run_test
rap_lndp_debug_intel 106 failed in run_test
rap_progcld_thompson_debug_intel 107 failed in run_test
rap_noah_debug_intel 108 failed in run_test
rap_sfcdiff_debug_intel 109 failed in run_test
rrfs_v1beta_debug_intel 111 failed in run_test
rap_clm_lake_debug_intel 112 failed in run_test
rap_flake_debug_intel 113 failed in run_test
rap_control_dyn32_phy32_intel 116 failed in run_test
hrrr_control_dyn32_phy32_intel 117 failed in run_test
hrrr_control_qr_dyn32_phy32_intel 118 failed in ru_test
rap_2threads_dyn32_phy32_intel 119 failed in run_test
hrrr_control_2threads_dyn32_phy32_intel 120 failed in run_test
hrrr_control_decomp_dyn32_phy32_intel 121 failed in run_test
conus13km_control_intel 125 failed in run_test
rap_control_dyn64_phy32_intel 128 failed in run_test
rap_control_debug_dyn32_phy32_intel 129 failed in run_test
hrrr_control_debug_dyn32_phy32_intel 130 failed in run_test
conus13km_debug_intel 131 failed in run_test
conus13km_debug_qr_intel 132 failed in run_test
conus13km_debug_2threads_intel 133 failed in run_test
conus13km_radar_tten_debug_intel 134 failed in run_test
rap_control_dyn64_phy32_debug_intel 135 failed in run_test
hafs_regional_atm_intel 136 failed in run_test
hafs_regional_atm_thompson_gfdlsf_intel 137 failed in run_test
hafs_regional_atm_ocn_intel 138 failed in run_test
hafs_regional_atm_wav_intel 139 failed in run_test
hafs_regional_atm_ocn_wav_intel 140 failed in run_test
hafs_regional_1nest_atm_intel 141 failed in run_test
hafs_regional_1nest_atm_qr_intel 142 failed in run_test
hafs_regional_telescopic_2nests_atm_intel 143 failed in run_test
hafs_global_1nest_atm_intel 144 failed in run_test
hafs_global_1nest_atm_qr_intel 145 failed in run_test
hafs_global_multiple_4nests_atm_intel 146 failed in run_test
hafs_global_multiple_4nests_atm_qr_intel 147 failed in run_test
hafs_regional_specified_moving_1nest_atm_intel 148 failed in run_test
hafs_regional_storm_following_1nest_atm_intel 149 failed in run_test
hafs_regional_storm_following_1nest_atm_qr_intel 150 failed in run_test
hafs_regional_storm_following_1nest_atm_ocn_intel 151 failed in run_test
hafs_regional_storm_following_1nest_atm_ocn_debug_intel 153 failed in
hafs_regional_storm_following_1nest_atm_ocn_wav_intel 154 failed in run_test
hafs_regional_docn_intel 155 failed in run_test
hafs_regional_docn_oisst_intel 156 failed in run_test
control_p8_atmlnd_sbs_intel 175 failed in run_test
atmwav_control_noaero_p8_intel 176 failed in run_test
atmaero_control_p8_intel 178 failed in run_test
atmaero_control_p8_rad_intel 179 failed in run_test
atmaero_control_p8_rad_micro_intel 180 failed in run_test
control_p8_gnu 187 failed in run_test
control_p8_ugwpv1_gnu 188 failed in run_test
rap_control_gnu 190 failed in run_test
rap_decomp_gnu 191 failed in run_test
rap_2threads_gnu 192 failed in run_test
rap_sfcdiff_gnu 194 failed in run_test
rap_sfcdiff_decomp_gnu 195 failed in run_test
hrrr_control_gnu 197 failed in run_test
hrrr_control_qr_gnu 198 failed in run_test
hrrr_control_2threads_gnu 199 failed in run_test
hrrr_control_decomp_gnu 200 failed in run_test
rrfs_v1beta_gnu 203 failed in run_test
rap_control_debug_gnu 206 failed in run_test
hrrr_control_debug_gnu 207 failed in run_test
hrrr_gf_debug_gnu 208 failed in run_test
hrrr_c3_debug_gnu 209 failed in run_test
rap_diag_debug_gnu 210 failed in run_test
rap_progcld_thompson_debug_gnu 212 failed in run_test
rrfs_v1beta_debug_gnu 213 failed in run_test
control_debug_p8_gnu 216 failed in run_test
rap_flake_debug_gnu 217 failed in run_test
rap_clm_lake_debug_gnu 218 failed in run_test
rap_control_dyn32_phy32_gnu 220 failed in run_test
hrrr_control_dyn32_phy32_gnu 221 failed in run_test
hrrr_control_qr_dyn32_phy32_gnu 222 failed in run_test
rap_2threads_dyn32_phy32_gnu 223 failed in run_test
hrrr_control_2threads_dyn32_phy32_gnu 224 failed in run_test
hrrr_control_decomp_dyn32_phy32_gnu 225 failed in run_test
conus13km_control_gnu 229 failed in run_test
rap_control_dyn64_phy32_gnu 232 failed in run_test
rap_control_debug_dyn32_phy32_gnu 233 failed in run_test
hrrr_control_debug_dyn32_phy32_gnu 234 failed in run_test
conus13km_debug_gnu 235 failed in run_test
conus13km_debug_qr_gnu 236 failed in run_test
conus13km_debug_2threads_gnu 237 failed in run_test
conus13km_radar_tten_debug_gnu 238 failed in run_test
rap_control_dyn64_phy32_debug_gnu 239 failed in run_test
cpld_control_p8_gnu 240 failed in run_test
cpld_control_nowave_noaero_p8_gnu 241 failed in run_test
cpld_debug_p8_gnu 242 failed in run_test
cpld_control_pdlib_p8_gnu 243 failed in run_test
cpld_debug_pdlib_p8_gnu 244 failed in run_test

**Comment by mkavulich** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
[RT] Repo location: /scratch1/BMC/gmtb/CCPP_regression_testing/NCAR_ufs-weather-model//run//1627414637/20240202231011/ufs-weather-model
[RT] Log file shows failures.
[RT] Please obtain logs from /scratch1/BMC/gmtb/CCPP_regression_testing/NCAR_ufs-weather-model//run//1627414637/20240202231011/ufs-weather-model

**Comment by mkavulich** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
[RT] Repo location: /scratch1/BMC/gmtb/CCPP_regression_testing/NCAR_ufs-weather-model//run//1627414637/20240205165010/ufs-weather-model
[RT] Error: Test 001 cpld_control_p8_mixedmode_intel FAIL Tries: 2
[RT] Error: Test 002 cpld_control_gfsv17_intel FAIL Tries: 2
[RT] Error: Test 005 cpld_mpi_gfsv17_intel FAIL Tries: 2
[RT] Error: Test 006 cpld_debug_gfsv17_intel FAIL Tries: 2
[RT] Error: Test 007 cpld_control_p8_intel FAIL Tries: 2
[RT] Error: Test 009 cpld_control_qr_p8_intel FAIL Tries: 2
[RT] Error: Test 011 cpld_2threads_p8_intel FAIL Tries: 2
[RT] Error: Test 012 cpld_decomp_p8_intel FAIL Tries: 2
[RT] Error: Test 013 cpld_mpi_p8_intel FAIL Tries: 2
[RT] Error: Test 014 cpld_control_ciceC_p8_intel FAIL Tries: 2
[RT] Error: Test 015 cpld_control_c192_p8_intel FAIL Tries: 2
[RT] Error: Test 017 cpld_bmark_p8_intel FAIL Tries: 2
[RT] Error: Test 019 cpld_control_noaero_p8_intel FAIL Tries: 2
[RT] Error: Test 020 cpld_control_nowave_noaero_p8_intel FAIL Tries: 2
[RT] Error: Test 021 cpld_debug_p8_intel FAIL Tries: 2
[RT] Error: Test 022 cpld_debug_noaero_p8_intel FAIL Tries: 2
[RT] Error: Test 023 cpld_control_noaero_p8_agrid_intel FAIL Tries: 2
[RT] Error: Test 024 cpld_control_c48_intel FAIL Tries: 2
[RT] Error: Test 025 cpld_control_p8_faster_intel FAIL Tries: 2
[RT] Error: Test 026 cpld_control_pdlib_p8_intel FAIL Tries: 2
[RT] Error: Test 029 cpld_debug_pdlib_p8_intel FAIL Tries: 2
[RT] Error: Test 044 control_p8_intel FAIL Tries: 2
[RT] Error: Test 045 control_p8_ugwpv1_intel FAIL Tries: 2
[RT] Error: Test 047 control_qr_p8_intel FAIL Tries: 2
[RT] Error: Test 049 control_decomp_p8_intel FAIL Tries: 2
[RT] Error: Test 050 control_2threads_p8_intel FAIL Tries: 2
[RT] Error: Test 051 control_p8_lndp_intel FAIL Tries: 2
[RT] Error: Test 052 control_p8_rrtmgp_intel FAIL Tries: 2
[RT] Error: Test 053 control_p8_mynn_intel FAIL Tries: 2
[RT] Error: Test 054 merra2_thompson_intel FAIL Tries: 2
[RT] Error: Test 065 rap_control_intel FAIL Tries: 2
[RT] Error: Test 067 rap_decomp_intel FAIL Tries: 2
[RT] Error: Test 068 rap_2threads_intel FAIL Tries: 2
[RT] Error: Test 070 rap_sfcdiff_intel FAIL Tries: 2
[RT] Error: Test 071 rap_sfcdiff_decomp_intel FAIL Tries: 2
[RT] Error: Test 073 hrrr_control_intel FAIL Tries: 2
[RT] Error: Test 074 hrrr_control_qr_intel FAIL Tries: 2
[RT] Error: Test 075 hrrr_control_decomp_intel FAIL Tries: 2
[RT] Error: Test 076 hrrr_control_2threads_intel FAIL Tries: 2
[RT] Error: Test 079 rrfs_v1beta_intel FAIL Tries: 2
[RT] Error: Test 080 rrfs_v1nssl_intel FAIL Tries: 2
[RT] Error: Test 081 rrfs_v1nssl_nohailnoccn_intel FAIL Tries: 2
[RT] Error: Test 086 control_p8_faster_intel FAIL Tries: 2
[RT] Error: Test 096 control_debug_p8_intel FAIL Tries: 2
[RT] Error: Test 098 rap_control_debug_intel FAIL Tries: 2
[RT] Error: Test 099 hrrr_control_debug_intel FAIL Tries: 2
[RT] Error: Test 100 hrrr_gf_debug_intel FAIL Tries: 2
[RT] Error: Test 101 hrrr_c3_debug_intel FAIL Tries: 2
[RT] Error: Test 102 rap_unified_drag_suite_debug_intel FAIL Tries: 2
[RT] Error: Test 103 rap_diag_debug_intel FAIL Tries: 2
[RT] Error: Test 106 rap_lndp_debug_intel FAIL Tries: 2
[RT] Error: Test 107 rap_progcld_thompson_debug_intel FAIL Tries: 2
[RT] Error: Test 108 rap_noah_debug_intel FAIL Tries: 2
[RT] Error: Test 109 rap_sfcdiff_debug_intel FAIL Tries: 2
[RT] Error: Test 111 rrfs_v1beta_debug_intel FAIL Tries: 2
[RT] Error: Test 112 rap_clm_lake_debug_intel FAIL Tries: 2
[RT] Error: Test 113 rap_flake_debug_intel FAIL Tries: 2
[RT] Error: Test 116 rap_control_dyn32_phy32_intel FAIL Tries: 2
[RT] Error: Test 117 hrrr_control_dyn32_phy32_intel FAIL Tries: 2
[RT] Error: Test 118 hrrr_control_qr_dyn32_phy32_intel FAIL Tries: 2
[RT] Error: Test 119 rap_2threads_dyn32_phy32_intel FAIL Tries: 2
[RT] Error: Test 120 hrrr_control_2threads_dyn32_phy32_intel FAIL Tries: 2
[RT] Error: Test 121 hrrr_control_decomp_dyn32_phy32_intel FAIL Tries: 2
[RT] Error: Test 125 conus13km_control_intel FAIL Tries: 2
[RT] Error: Test 128 rap_control_dyn64_phy32_intel FAIL Tries: 2
[RT] Error: Test 129 rap_control_debug_dyn32_phy32_intel FAIL Tries: 2
[RT] Error: Test 130 hrrr_control_debug_dyn32_phy32_intel FAIL Tries: 2
[RT] Error: Test 131 conus13km_debug_intel FAIL Tries: 2
[RT] Error: Test 132 conus13km_debug_qr_intel FAIL Tries: 2
[RT] Error: Test 133 conus13km_debug_2threads_intel FAIL Tries: 2
[RT] Error: Test 134 conus13km_radar_tten_debug_intel FAIL Tries: 2
[RT] Error: Test 135 rap_control_dyn64_phy32_debug_intel FAIL Tries: 2
[RT] Error: Test 136 hafs_regional_atm_intel FAIL Tries: 2
[RT] Error: Test 137 hafs_regional_atm_thompson_gfdlsf_intel FAIL Tries: 2
[RT] Error: Test 138 hafs_regional_atm_ocn_intel FAIL Tries: 2
[RT] Error: Test 139 hafs_regional_atm_wav_intel FAIL Tries: 2
[RT] Error: Test 140 hafs_regional_atm_ocn_wav_intel FAIL Tries: 2
[RT] Error: Test 141 hafs_regional_1nest_atm_intel FAIL Tries: 2
[RT] Error: Test 142 hafs_regional_1nest_atm_qr_intel FAIL Tries: 2
[RT] Error: Test 143 hafs_regional_telescopic_2nests_atm_intel FAIL Tries: 2
[RT] Error: Test 144 hafs_global_1nest_atm_intel FAIL Tries: 2
[RT] Error: Test 145 hafs_global_1nest_atm_qr_intel FAIL Tries: 2
[RT] Error: Test 146 hafs_global_multiple_4nests_atm_intel FAIL Tries: 2
[RT] Error: Test 147 hafs_global_multiple_4nests_atm_qr_intel FAIL Tries: 2
[RT] Error: Test 148 hafs_regional_specified_moving_1nest_atm_intel FAIL Tries: 2
[RT] Error: Test 149 hafs_regional_storm_following_1nest_atm_intel FAIL Tries: 2
[RT] Error: Test 150 hafs_regional_storm_following_1nest_atm_qr_intel FAIL Tries: 2
[RT] Error: Test 151 hafs_regional_storm_following_1nest_atm_ocn_intel FAIL Tries: 2
[RT] Error: Test 153 hafs_regional_storm_following_1nest_atm_ocn_debug_intel FAIL Tries: 2
[RT] Error: Test 154 hafs_regional_storm_following_1nest_atm_ocn_wav_intel FAIL Tries: 2
[RT] Error: Test 155 hafs_regional_docn_intel FAIL Tries: 2
[RT] Error: Test 156 hafs_regional_docn_oisst_intel FAIL Tries: 2
[RT] Error: Test 175 control_p8_atmlnd_sbs_intel FAIL Tries: 2
[RT] Error: Test 176 atmwav_control_noaero_p8_intel FAIL Tries: 2
[RT] Error: Test 178 atmaero_control_p8_intel FAIL Tries: 2
[RT] Error: Test 179 atmaero_control_p8_rad_intel FAIL Tries: 2
[RT] Error: Test 180 atmaero_control_p8_rad_micro_intel FAIL Tries: 2
[RT] Error: Test 183 regional_atmaq_faster_intel FAIL Tries: 2
[RT] Error: Test 187 control_p8_gnu FAIL Tries: 2
[RT] Error: Test 188 control_p8_ugwpv1_gnu FAIL Tries: 2
[RT] Error: Test 190 rap_control_gnu FAIL Tries: 2
[RT] Error: Test 191 rap_decomp_gnu FAIL Tries: 2
[RT] Error: Test 192 rap_2threads_gnu FAIL Tries: 2
[RT] Error: Test 194 rap_sfcdiff_gnu FAIL Tries: 2
[RT] Error: Test 195 rap_sfcdiff_decomp_gnu FAIL Tries: 2
[RT] Error: Test 197 hrrr_control_gnu FAIL Tries: 2
[RT] Error: Test 198 hrrr_control_qr_gnu FAIL Tries: 2
[RT] Error: Test 199 hrrr_control_2threads_gnu FAIL Tries: 2
[RT] Error: Test 200 hrrr_control_decomp_gnu FAIL Tries: 2
[RT] Error: Test 203 rrfs_v1beta_gnu FAIL Tries: 2
[RT] Error: Test 206 rap_control_debug_gnu FAIL Tries: 2
[RT] Error: Test 207 hrrr_control_debug_gnu FAIL Tries: 2
[RT] Error: Test 208 hrrr_gf_debug_gnu FAIL Tries: 2
[RT] Error: Test 209 hrrr_c3_debug_gnu FAIL Tries: 2
[RT] Error: Test 210 rap_diag_debug_gnu FAIL Tries: 2
[RT] Error: Test 212 rap_progcld_thompson_debug_gnu FAIL Tries: 2
[RT] Error: Test 213 rrfs_v1beta_debug_gnu FAIL Tries: 2
[RT] Error: Test 216 control_debug_p8_gnu FAIL Tries: 2
[RT] Error: Test 217 rap_flake_debug_gnu FAIL Tries: 2
[RT] Error: Test 218 rap_clm_lake_debug_gnu FAIL Tries: 2
[RT] Error: Test 220 rap_control_dyn32_phy32_gnu FAIL Tries: 2
[RT] Error: Test 221 hrrr_control_dyn32_phy32_gnu FAIL Tries: 2
[RT] Error: Test 222 hrrr_control_qr_dyn32_phy32_gnu FAIL Tries: 2
[RT] Error: Test 223 rap_2threads_dyn32_phy32_gnu FAIL Tries: 2
[RT] Error: Test 224 hrrr_control_2threads_dyn32_phy32_gnu FAIL Tries: 2
[RT] Error: Test 225 hrrr_control_decomp_dyn32_phy32_gnu FAIL Tries: 2
[RT] Error: Test 229 conus13km_control_gnu FAIL Tries: 2
[RT] Error: Test 232 rap_control_dyn64_phy32_gnu FAIL Tries: 2
[RT] Error: Test 233 rap_control_debug_dyn32_phy32_gnu FAIL Tries: 2
[RT] Error: Test 234 hrrr_control_debug_dyn32_phy32_gnu FAIL Tries: 2
[RT] Error: Test 235 conus13km_debug_gnu FAIL Tries: 2
[RT] Error: Test 236 conus13km_debug_qr_gnu FAIL Tries: 2
[RT] Error: Test 237 conus13km_debug_2threads_gnu FAIL Tries: 2
[RT] Error: Test 238 conus13km_radar_tten_debug_gnu FAIL Tries: 2
[RT] Error: Test 239 rap_control_dyn64_phy32_debug_gnu FAIL Tries: 2
[RT] Error: Test 240 cpld_control_p8_gnu FAIL Tries: 2
[RT] Error: Test 241 cpld_control_nowave_noaero_p8_gnu FAIL Tries: 2
[RT] Error: Test 242 cpld_debug_p8_gnu FAIL Tries: 2
[RT] Error: Test 243 cpld_control_pdlib_p8_gnu FAIL Tries: 2
[RT] Error: Test 244 cpld_debug_pdlib_p8_gnu FAIL Tries: 2
[RT] Log file shows failures.
[RT] Please obtain logs from /scratch1/BMC/gmtb/CCPP_regression_testing/NCAR_ufs-weather-model//run//1627414637/20240205165010/ufs-weather-model

**Comment by mkavulich** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/CCPP_regression_testing/NCAR_ufs-weather-model//run//1627414637/20240205212016/ufs-weather-model
Please make changes and add the following label back: hera-intel-BL

**Review by mkavulich — APPROVED** [review]
Looks good once submodule is updated

**Pull request merged**
