### PR TITLE
UFS-dev PR#85

### PR DESCRIPTION
**Pull request by grantfirl**
Identical to https://github.com/ufs-community/ufs-weather-model/pull/1797

Also contains changes from https://github.com/ufs-community/ufs-weather-model/pull/1812

### CODE REVIEW

**Comment by grantfirl** [comment]
https://github.com/ufs-community/ufs-weather-model/pull/1812 changes the following RTs:

1:138:Test 001 cpld_control_p8_mixedmode_intel FAIL
2:209:Test 002 cpld_control_gfsv17_intel FAIL
3:281:Test 003 cpld_control_p8_intel FAIL
4:353:Test 005 cpld_control_qr_p8_intel FAIL
5:413:Test 007 cpld_2threads_p8_intel FAIL
6:473:Test 008 cpld_decomp_p8_intel FAIL
7:533:Test 009 cpld_mpi_p8_intel FAIL
8:605:Test 010 cpld_control_ciceC_p8_intel FAIL
9:665:Test 011 cpld_control_c192_p8_intel FAIL
10:720:Test 013 cpld_bmark_p8_intel FAIL
11:791:Test 015 cpld_control_noaero_p8_intel FAIL
12:860:Test 016 cpld_control_nowave_noaero_p8_intel FAIL
13:920:Test 017 cpld_debug_p8_intel FAIL
14:979:Test 018 cpld_debug_noaero_p8_intel FAIL
15:1105:Test 020 cpld_control_c48_intel FAIL
16:1107:Test 021 cpld_warmstart_c48_intel FAIL
17:1179:Test 023 cpld_control_p8_faster_intel FAIL
18:1250:Test 024 cpld_control_pdlib_p8_intel FAIL
19:1309:Test 027 cpld_debug_pdlib_p8_intel FAIL
24:7117:Test 234 cpld_control_p8_gnu FAIL
25:7186:Test 235 cpld_control_nowave_noaero_p8_gnu FAIL
26:7246:Test 236 cpld_debug_p8_gnu FAIL
27:7317:Test 237 cpld_control_pdlib_p8_gnu FAIL
28:7376:Test 238 cpld_debug_pdlib_p8_gnu FAIL
Four hafs tests fail because the special (fill) value in the mediator files is no longer being scaled by rtime prior to export by ATM

20:4203:Test 134 hafs_regional_atm_ocn_intel FAIL
21:4237:Test 136 hafs_regional_atm_ocn_wav_intel FAIL
22:4739:Test 151 hafs_regional_docn_intel FAIL
23:4754:Test 152 hafs_regional_docn_oisst_intel FAIL
For the hafs tests, all files are B4B except for

957:rt_134_hafs_regional_atm_ocn_intel.log:9: Comparing ufs.hafs.cpl.hi.2019-08-29-21600.nc ............ALT CHECK......NOT OK
958:rt_134_hafs_regional_atm_ocn_intel.log:10: Comparing ufs.hafs.cpl.r.2019-08-29-21600.nc ............ALT CHECK......NOT OK
959:rt_136_hafs_regional_atm_ocn_wav_intel.log:12: Comparing ufs.hafs.cpl.r.2019-08-29-21600.nc ............ALT CHECK......NOT OK
960:rt_151_hafs_regional_docn_intel.log:7: Comparing ufs.hafs.cpl.hi.2019-08-29-21600.nc ............ALT CHECK......NOT OK
961:rt_151_hafs_regional_docn_intel.log:8: Comparing ufs.hafs.cpl.r.2019-08-29-21600.nc ............ALT CHECK......NOT OK
962:rt_152_hafs_regional_docn_oisst_intel.log:7: Comparing ufs.hafs.cpl.hi.2019-08-29-21600.nc ............ALT CHECK......NOT OK
963:rt_152_hafs_regional_docn_oisst_intel.log:8: Comparing ufs.hafs.cpl.r.2019-08-29-21600.nc ............ALT CHECK......NOT OK

**Comment by grantfirl** [comment]
Also, there are new regression tests for 32-bit physics in RRFS for https://github.com/ufs-community/ufs-weather-model/pull/1797

**Comment by grantfirl** [comment]
Associated PRs:
https://github.com/NCAR/ufs-weather-model/pull/104
https://github.com/NCAR/fv3atm/pull/100
https://github.com/NCAR/ccpp-physics/pull/1029
https://github.com/NCAR/ccpp-scm/pull/399

**Review by mkavulich — APPROVED** [review]

**Comment by grantfirl** [comment]
A few Cheyenne tests failed due to a known HDF5 issue, so the log was not updated.

**Pull request merged**
