### PR TITLE
UFS-dev PR#14

### PR DESCRIPTION
**Pull request by grantfirl**
Identical to https://github.com/ufs-community/ufs-weather-model/pull/1460
Contains changes from #72 (that will be merged first)

Baseline change due to newly added RT only.

### CODE REVIEW

**Comment by dustinswales** [comment]
@grantfirl Read to test. Can you update the downstream submodules?

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1109974330/20221108163823/ufs-weather-model
[RT] Error: Test regional_3km_wofs 053 failed in check_result failed 
[RT] Error: Test regional_3km_wofs 053 failed in run_test failed 
Please make changes and add the following label back: cheyenne-intel-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1109974330/20221109000113/ufs-weather-model
[RT] Error: Test regional_3km_wofs 056 failed in check_result failed 
[RT] Error: Test regional_3km_wofs 056 failed in run_test failed 
Please make changes and add the following label back: hera-intel-RT

**Review by dustinswales — APPROVED** [review]
All tests look good.

**Comment by grantfirl** [comment]
> @grantfirl You are good to update the submodules and merge whenever you have time.

@dustinswales Please approve https://github.com/NCAR/fv3atm/pull/72 when you get a minute.

**Pull request merged**
