### PR TITLE
UFS-dev PR#57

### PR DESCRIPTION
**Pull request by grantfirl**
Identical to https://github.com/ufs-community/ufs-weather-model/pull/1677

needs `EP4` tag after merge

Contains changes from https://github.com/ufs-community/ufs-weather-model/pull/1692 (BL change) and https://github.com/ufs-community/ufs-weather-model/pull/1681 (no BL change)

### CODE REVIEW

**Comment by grantfirl** [comment]
From https://github.com/ufs-community/ufs-weather-model/pull/1692, expected failures are:

Cheyenne/GNU
Test cpld_control_p8 047 failed in check_result failed
Test cpld_control_p8 047 failed in run_test failed
Test cpld_debug_p8 049 failed in check_result failed
Test cpld_debug_p8 049 failed in run_test failed

Cheyenne/INTEL
Test cpld_control_p8_mixedmode 001 failed in check_result failed
Test cpld_control_p8_mixedmode 001 failed in run_test failed
Test cpld_control_gfsv17 002 failed in check_result failed
Test cpld_control_gfsv17 002 failed in run_test failed
Test cpld_control_p8 003 failed in check_result failed
Test cpld_control_p8 003 failed in run_test failed
Test cpld_control_qr_p8 005 failed in check_result failed
Test cpld_control_qr_p8 005 failed in run_test failed
Test cpld_2threads_p8 007 failed in check_result failed
Test cpld_2threads_p8 007 failed in run_test failed
Test cpld_decomp_p8 008 failed in check_result failed
Test cpld_decomp_p8 008 failed in run_test failed
Test cpld_mpi_p8 009 failed in check_result failed
Test cpld_mpi_p8 009 failed in run_test failed
Test cpld_control_ciceC_p8 010 failed in check_result failed
Test cpld_control_ciceC_p8 010 failed in run_test failed
Test cpld_control_c192_p8 011 failed in check_result failed
Test cpld_control_c192_p8 011 failed in run_test failed
Test cpld_control_noaero_p8 013 failed in check_result failed
Test cpld_control_noaero_p8 013 failed in run_test failed
Test cpld_debug_p8 015 failed in check_result failed
Test cpld_debug_p8 015 failed in run_test failed
Test cpld_debug_noaero_p8 016 failed in check_result failed
Test cpld_debug_noaero_p8 016 failed in run_test failed

**Comment by grantfirl** [comment]
cpld_control_gfsv17 is expected to fail from https://github.com/ufs-community/ufs-weather-model/pull/1677 changes alone

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1305461778/20230419090011/ufs-weather-model
[RT] Error: Test control_c48 001 failed in run_test failed 
[RT] Error: Test cpld_control_p8 048 failed in check_result failed 
[RT] Error: Test cpld_control_p8 048 failed in run_test failed 
[RT] Error: Test cpld_debug_p8 050 failed in check_result failed 
[RT] Error: Test cpld_debug_p8 050 failed in run_test failed 
Please make changes and add the following label back: cheyenne-gnu-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1305461778/20230419162609/ufs-weather-model
[RT] Error: Test cpld_control_p8_mixedmode 001 failed in check_result failed 
[RT] Error: Test cpld_control_p8_mixedmode 001 failed in run_test failed 
[RT] Error: Test cpld_control_gfsv17 002 failed in check_result failed 
[RT] Error: Test cpld_control_gfsv17 002 failed in run_test failed 
[RT] Error: Test cpld_control_p8 003 failed in check_result failed 
[RT] Error: Test cpld_control_p8 003 failed in run_test failed 
[RT] Error: Test cpld_control_qr_p8 005 failed in check_result failed 
[RT] Error: Test cpld_control_qr_p8 005 failed in run_test failed 
[RT] Error: Test cpld_2threads_p8 007 failed in check_result failed 
[RT] Error: Test cpld_2threads_p8 007 failed in run_test failed 
[RT] Error: Test cpld_decomp_p8 008 failed in check_result failed 
[RT] Error: Test cpld_decomp_p8 008 failed in run_test failed 
[RT] Error: Test cpld_mpi_p8 009 failed in check_result failed 
[RT] Error: Test cpld_mpi_p8 009 failed in run_test failed 
[RT] Error: Test cpld_control_ciceC_p8 010 failed in check_result failed 
[RT] Error: Test cpld_control_ciceC_p8 010 failed in run_test failed 
[RT] Error: Test cpld_control_c192_p8 011 failed in check_result failed 
[RT] Error: Test cpld_control_c192_p8 011 failed in run_test failed 
[RT] Error: Test cpld_bmark_p8 013 failed in check_result failed 
[RT] Error: Test cpld_bmark_p8 013 failed in run_test failed 
[RT] Error: Test cpld_control_noaero_p8 015 failed in check_result failed 
[RT] Error: Test cpld_control_noaero_p8 015 failed in run_test failed 
[RT] Error: Test cpld_debug_p8 017 failed in check_result failed 
[RT] Error: Test cpld_debug_p8 017 failed in run_test failed 
[RT] Error: Test cpld_debug_noaero_p8 018 failed in check_result failed 
[RT] Error: Test cpld_debug_noaero_p8 018 failed in run_test failed 
[RT] Error: Test cpld_control_p8_faster 023 failed in check_result failed 
[RT] Error: Test cpld_control_p8_faster 023 failed in run_test failed 
[RT] Error: Test hafs_regional_atm_wav 125 failed in check_result failed 
[RT] Error: Test hafs_regional_atm_wav 125 failed in run_test failed 
[RT] Error: Test hafs_regional_atm_ocn_wav 126 failed in check_result failed 
[RT] Error: Test hafs_regional_atm_ocn_wav 126 failed in run_test failed 
Please make changes and add the following label back: hera-intel-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1305461778/20230419140107/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1305461778/20230419144618/ufs-weather-model
Please make changes and add the following label back: cheyenne-gnu-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1305461778/20230419152102/ufs-weather-model
[BL] Error: Test hafs_regional_atm_wav 085 failed in run_test failed 
[BL] Error: Test hafs_regional_storm_following_1nest_atm_ocn_wav 096 failed in run_test failed 
[BL] Error: Test hafs_regional_datm_cdeps 099 failed in run_test failed 
[BL] Error: Test regional_atmaq 119 failed in run_test failed 
[BL] Error: Test regional_atmaq_faster 120 failed in run_test failed 
Please make changes and add the following label back: cheyenne-intel-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1305461778/20230419201511/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1305461778/20230419220149/ufs-weather-model
Please make changes and add the following label back: hera-gnu-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1305461778/20230419232846/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1305461778/20230420003745/ufs-weather-model
Please make changes and add the following label back: hera-intel-BL

**Comment by grantfirl** [comment]
Out of space on Cheyenne, and I still don't have permissions for clearing enough space for the auto RTs, so I ran a creation of new baselines for Cheyenne/intel manually and verified against them. The new baselines are in: /glade/scratch/grantf/FV3_RT/REGRESSION_TEST_INTEL

**Pull request merged**
