### PR TITLE
UFS-dev-PR#9

### PR DESCRIPTION
**Pull request by dustinswales**
Identical to [ufs-weather-model #1496](https://github.com/ufs-community/ufs-weather-model/pull/1496)

### CODE REVIEW

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: RT
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1140715763/20221130182641/ufs-weather-model
Please make changes and add the following label back: hera-gnu-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1140715763/20221130182940/ufs-weather-model
Please make changes and add the following label back: hera-intel-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1140715763/20221130112540/ufs-weather-model
[RT] Error: Test control_p8 006 failed in check_result failed 
[RT] Error: Test control_p8 006 failed in run_test failed 
[RT] Error: Test control_debug_p8 034 failed in check_result failed 
[RT] Error: Test control_debug_p8 034 failed in run_test failed 
[RT] Error: Test cpld_control_p8 049 failed in check_result failed 
[RT] Error: Test cpld_control_p8 049 failed in run_test failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 050 failed in check_result failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 050 failed in run_test failed 
[RT] Error: Test cpld_debug_p8 051 failed in check_result failed 
[RT] Error: Test cpld_debug_p8 051 failed in run_test failed 
Please make changes and add the following label back: cheyenne-gnu-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1140715763/20221130120532/ufs-weather-model
[RT] Error: Test cpld_control_p8 001 failed in check_result failed 
[RT] Error: Test cpld_control_p8 001 failed in run_test failed 
[RT] Error: Test cpld_2threads_p8 003 failed in check_result failed 
[RT] Error: Test cpld_2threads_p8 003 failed in run_test failed 
[RT] Error: Test cpld_esmfthreads_p8 004 failed in check_result failed 
[RT] Error: Test cpld_esmfthreads_p8 004 failed in run_test failed 
[RT] Error: Test cpld_decomp_p8 005 failed in check_result failed 
[RT] Error: Test cpld_decomp_p8 005 failed in run_test failed 
[RT] Error: Test cpld_mpi_p8 006 failed in check_result failed 
[RT] Error: Test cpld_mpi_p8 006 failed in run_test failed 
[RT] Error: Test cpld_control_ciceC_p8 007 failed in check_result failed 
[RT] Error: Test cpld_control_ciceC_p8 007 failed in run_test failed 
[RT] Error: Test cpld_control_c192_p8 008 failed in check_result failed 
[RT] Error: Test cpld_control_c192_p8 008 failed in run_test failed 
[RT] Error: Test cpld_control_noaero_p8 010 failed in check_result failed 
[RT] Error: Test cpld_control_noaero_p8 010 failed in run_test failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 011 failed in check_result failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 011 failed in run_test failed 
[RT] Error: Test cpld_debug_p8 012 failed in check_result failed 
[RT] Error: Test cpld_debug_p8 012 failed in run_test failed 
[RT] Error: Test cpld_debug_noaero_p8 013 failed in check_result failed 
[RT] Error: Test cpld_debug_noaero_p8 013 failed in run_test failed 
[RT] Error: Test cpld_control_noaero_p8_agrid 014 failed in check_result failed 
[RT] Error: Test cpld_control_noaero_p8_agrid 014 failed in run_test failed 
[RT] Error: Test cpld_control_c48 015 failed in check_result failed 
[RT] Error: Test cpld_control_c48 015 failed in run_test failed 
[RT] Error: Test cpld_warmstart_c48 016 failed in check_result failed 
[RT] Error: Test cpld_warmstart_c48 016 failed in run_test failed 
[RT] Error: Test control_p8 038 failed in check_result failed 
[RT] Error: Test control_p8 038 failed in run_test failed 
[RT] Error: Test control_p8_lndp 039 failed in check_result failed 
[RT] Error: Test control_p8_lndp 039 failed in run_test failed 
[RT] Error: Test control_decomp_p8 041 failed in check_result failed 
[RT] Error: Test control_decomp_p8 041 failed in run_test failed 
[RT] Error: Test control_2threads_p8 042 failed in check_result failed 
[RT] Error: Test control_2threads_p8 042 failed in run_test failed 
[RT] Error: Test control_p8_rrtmgp 043 failed in check_result failed 
[RT] Error: Test control_p8_rrtmgp 043 failed in run_test failed 
[RT] Error: Test merra2_thompson 044 failed in check_result failed 
[RT] Error: Test merra2_thompson 044 failed in run_test failed 
[RT] Error: Test rap_rrtmgp 055 failed in check_result failed 
[RT] Error: Test rap_rrtmgp 055 failed in run_test failed 
[RT] Error: Test control_debug_p8 091 failed in check_result failed 
[RT] Error: Test control_debug_p8 091 failed in run_test failed 
[RT] Error: Test rap_rrtmgp_debug 103 failed in check_result failed 
[RT] Error: Test rap_rrtmgp_debug 103 failed in run_test failed 
[RT] Error: Test hafs_regional_atm_thompson_gfdlsf 121 failed in check_result failed 
[RT] Error: Test hafs_regional_atm_thompson_gfdlsf 121 failed in run_test failed 
[RT] Error: Test control_p8_atmlnd_sbs 153 failed in check_result failed 
[RT] Error: Test control_p8_atmlnd_sbs 153 failed in run_test failed 
[RT] Error: Test atmaero_control_p8 155 failed in check_result failed 
[RT] Error: Test atmaero_control_p8 155 failed in run_test failed 
[RT] Error: Test atmaero_control_p8_rad 156 failed in check_result failed 
[RT] Error: Test atmaero_control_p8_rad 156 failed in run_test failed 
[RT] Error: Test atmaero_control_p8_rad_micro 157 failed in check_result failed 
[RT] Error: Test atmaero_control_p8_rad_micro 157 failed in run_test failed 
Please make changes and add the following label back: cheyenne-intel-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1140715763/20221130200433/ufs-weather-model
[RT] Error: Test cpld_control_p8 001 failed in check_result failed 
[RT] Error: Test cpld_control_p8 001 failed in run_test failed 
[RT] Error: Test cpld_2threads_p8 003 failed in check_result failed 
[RT] Error: Test cpld_2threads_p8 003 failed in run_test failed 
[RT] Error: Test cpld_esmfthreads_p8 004 failed in check_result failed 
[RT] Error: Test cpld_esmfthreads_p8 004 failed in run_test failed 
[RT] Error: Test cpld_decomp_p8 005 failed in check_result failed 
[RT] Error: Test cpld_decomp_p8 005 failed in run_test failed 
[RT] Error: Test cpld_mpi_p8 006 failed in check_result failed 
[RT] Error: Test cpld_mpi_p8 006 failed in run_test failed 
[RT] Error: Test cpld_control_ciceC_p8 007 failed in check_result failed 
[RT] Error: Test cpld_control_ciceC_p8 007 failed in run_test failed 
[RT] Error: Test cpld_control_c192_p8 008 failed in check_result failed 
[RT] Error: Test cpld_control_c192_p8 008 failed in run_test failed 
[RT] Error: Test cpld_bmark_p8 010 failed in check_result failed 
[RT] Error: Test cpld_bmark_p8 010 failed in run_test failed 
[RT] Error: Test cpld_bmark_esmfthreads_p8 012 failed in check_result failed 
[RT] Error: Test cpld_bmark_esmfthreads_p8 012 failed in run_test failed 
[RT] Error: Test cpld_control_noaero_p8 013 failed in check_result failed 
[RT] Error: Test cpld_control_noaero_p8 013 failed in run_test failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 014 failed in check_result failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 014 failed in run_test failed 
[RT] Error: Test cpld_debug_p8 015 failed in check_result failed 
[RT] Error: Test cpld_debug_p8 015 failed in run_test failed 
[RT] Error: Test cpld_debug_noaero_p8 016 failed in check_result failed 
[RT] Error: Test cpld_debug_noaero_p8 016 failed in run_test failed 
[RT] Error: Test cpld_control_noaero_p8_agrid 017 failed in check_result failed 
[RT] Error: Test cpld_control_noaero_p8_agrid 017 failed in run_test failed 
[RT] Error: Test cpld_control_c48 018 failed in check_result failed 
[RT] Error: Test cpld_control_c48 018 failed in run_test failed 
[RT] Error: Test cpld_warmstart_c48 019 failed in check_result failed 
[RT] Error: Test cpld_warmstart_c48 019 failed in run_test failed 
[RT] Error: Test control_p8 041 failed in check_result failed 
[RT] Error: Test control_p8 041 failed in run_test failed 
[RT] Error: Test control_p8_lndp 042 failed in check_result failed 
[RT] Error: Test control_p8_lndp 042 failed in run_test failed 
[RT] Error: Test control_decomp_p8 044 failed in check_result failed 
[RT] Error: Test control_decomp_p8 044 failed in run_test failed 
[RT] Error: Test control_2threads_p8 045 failed in check_result failed 
[RT] Error: Test control_2threads_p8 045 failed in run_test failed 
[RT] Error: Test control_p8_rrtmgp 046 failed in check_result failed 
[RT] Error: Test control_p8_rrtmgp 046 failed in run_test failed 
[RT] Error: Test merra2_thompson 047 failed in check_result failed 
[RT] Error: Test merra2_thompson 047 failed in run_test failed 
[RT] Error: Test rap_rrtmgp 058 failed in check_result failed 
[RT] Error: Test rap_rrtmgp 058 failed in run_test failed 
[RT] Error: Test control_debug_p8 094 failed in check_result failed 
[RT] Error: Test control_debug_p8 094 failed in run_test failed 
[RT] Error: Test rap_rrtmgp_debug 106 failed in check_result failed 
[RT] Error: Test rap_rrtmgp_debug 106 failed in run_test failed 
[RT] Error: Test hafs_regional_atm_thompson_gfdlsf 124 failed in check_result failed 
[RT] Error: Test hafs_regional_atm_thompson_gfdlsf 124 failed in run_test failed 
[RT] Error: Test control_p8_atmlnd_sbs 156 failed in check_result failed 
[RT] Error: Test control_p8_atmlnd_sbs 156 failed in run_test failed 
[RT] Error: Test atmaero_control_p8 158 failed in check_result failed 
[RT] Error: Test atmaero_control_p8 158 failed in run_test failed 
[RT] Error: Test atmaero_control_p8_rad 159 failed in check_result failed 
[RT] Error: Test atmaero_control_p8_rad 159 failed in run_test failed 
[RT] Error: Test atmaero_control_p8_rad_micro 160 failed in check_result failed 
[RT] Error: Test atmaero_control_p8_rad_micro 160 failed in run_test failed 
Please make changes and add the following label back: hera-intel-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1140715763/20221130165433/ufs-weather-model
Please make changes and add the following label back: cheyenne-gnu-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1140715763/20221130170437/ufs-weather-model
Please make changes and add the following label back: cheyenne-intel-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1140715763/20221201013618/ufs-weather-model
[BL] ERROR: Baseline location exists before creation:
/scratch1/BMC/gmtb/RT/NCAR/main-20221109/GNU
Please make changes and add the following label back: hera-gnu-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1140715763/20221201013902/ufs-weather-model
[BL] ERROR: Baseline location exists before creation:
/scratch1/BMC/gmtb/RT/NCAR/main-20221109/INTEL
Please make changes and add the following label back: hera-intel-BL

**Comment by grantfirl** [comment]
@dustinswales I think that this one should be next if we're following the ufs-dev order. Please update the submodules with the latest mains when you get a chance.

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1140715763/20221213144506/ufs-weather-model
[RT] Error: Test control_p8 006 failed in check_result failed 
[RT] Error: Test control_p8 006 failed in run_test failed 
[RT] Error: Test control_debug_p8 034 failed in check_result failed 
[RT] Error: Test control_debug_p8 034 failed in run_test failed 
[RT] Error: Test cpld_control_p8 049 failed in check_result failed 
[RT] Error: Test cpld_control_p8 049 failed in run_test failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 050 failed in check_result failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 050 failed in run_test failed 
[RT] Error: Test cpld_debug_p8 051 failed in check_result failed 
[RT] Error: Test cpld_debug_p8 051 failed in run_test failed 
Please make changes and add the following label back: cheyenne-gnu-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: RT
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1140715763/20221213214515/ufs-weather-model
[RT] Error: Test control_p8 006 failed in check_result failed 
[RT] Error: Test control_p8 006 failed in run_test failed 
[RT] Error: Test control_debug_p8 034 failed in check_result failed 
[RT] Error: Test control_debug_p8 034 failed in run_test failed 
[RT] Error: Test cpld_control_p8 049 failed in check_result failed 
[RT] Error: Test cpld_control_p8 049 failed in run_test failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 050 failed in check_result failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 050 failed in run_test failed 
[RT] Error: Test cpld_debug_p8 051 failed in check_result failed 
[RT] Error: Test cpld_debug_p8 051 failed in run_test failed 
Please make changes and add the following label back: hera-gnu-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1140715763/20221213150009/ufs-weather-model
[RT] Error: Test cpld_control_p8 001 failed in check_result failed 
[RT] Error: Test cpld_control_p8 001 failed in run_test failed 
[RT] Error: Test cpld_2threads_p8 003 failed in check_result failed 
[RT] Error: Test cpld_2threads_p8 003 failed in run_test failed 
[RT] Error: Test cpld_esmfthreads_p8 004 failed in check_result failed 
[RT] Error: Test cpld_esmfthreads_p8 004 failed in run_test failed 
[RT] Error: Test cpld_decomp_p8 005 failed in check_result failed 
[RT] Error: Test cpld_decomp_p8 005 failed in run_test failed 
[RT] Error: Test cpld_mpi_p8 006 failed in check_result failed 
[RT] Error: Test cpld_mpi_p8 006 failed in run_test failed 
[RT] Error: Test cpld_control_ciceC_p8 007 failed in check_result failed 
[RT] Error: Test cpld_control_ciceC_p8 007 failed in run_test failed 
[RT] Error: Test cpld_control_c192_p8 008 failed in check_result failed 
[RT] Error: Test cpld_control_c192_p8 008 failed in run_test failed 
[RT] Error: Test cpld_control_noaero_p8 010 failed in check_result failed 
[RT] Error: Test cpld_control_noaero_p8 010 failed in run_test failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 011 failed in check_result failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 011 failed in run_test failed 
[RT] Error: Test cpld_debug_p8 012 failed in check_result failed 
[RT] Error: Test cpld_debug_p8 012 failed in run_test failed 
[RT] Error: Test cpld_debug_noaero_p8 013 failed in check_result failed 
[RT] Error: Test cpld_debug_noaero_p8 013 failed in run_test failed 
[RT] Error: Test cpld_control_noaero_p8_agrid 014 failed in check_result failed 
[RT] Error: Test cpld_control_noaero_p8_agrid 014 failed in run_test failed 
[RT] Error: Test cpld_control_c48 015 failed in check_result failed 
[RT] Error: Test cpld_control_c48 015 failed in run_test failed 
[RT] Error: Test cpld_warmstart_c48 016 failed in check_result failed 
[RT] Error: Test cpld_warmstart_c48 016 failed in run_test failed 
[RT] Error: Test control_p8 038 failed in check_result failed 
[RT] Error: Test control_p8 038 failed in run_test failed 
[RT] Error: Test control_p8_lndp 039 failed in check_result failed 
[RT] Error: Test control_p8_lndp 039 failed in run_test failed 
[RT] Error: Test control_decomp_p8 041 failed in check_result failed 
[RT] Error: Test control_decomp_p8 041 failed in run_test failed 
[RT] Error: Test control_2threads_p8 042 failed in check_result failed 
[RT] Error: Test control_2threads_p8 042 failed in run_test failed 
[RT] Error: Test control_p8_rrtmgp 043 failed in check_result failed 
[RT] Error: Test control_p8_rrtmgp 043 failed in run_test failed 
[RT] Error: Test merra2_thompson 044 failed in check_result failed 
[RT] Error: Test merra2_thompson 044 failed in run_test failed 
[RT] Error: Test rap_rrtmgp 054 failed in check_result failed 
[RT] Error: Test rap_rrtmgp 054 failed in run_test failed 
[RT] Error: Test control_debug_p8 090 failed in check_result failed 
[RT] Error: Test control_debug_p8 090 failed in run_test failed 
[RT] Error: Test rap_rrtmgp_debug 102 failed in check_result failed 
[RT] Error: Test rap_rrtmgp_debug 102 failed in run_test failed 
[RT] Error: Test hafs_regional_atm_thompson_gfdlsf 120 failed in check_result failed 
[RT] Error: Test hafs_regional_atm_thompson_gfdlsf 120 failed in run_test failed 
[RT] Error: Test control_p8_atmlnd_sbs 152 failed in check_result failed 
[RT] Error: Test control_p8_atmlnd_sbs 152 failed in run_test failed 
[RT] Error: Test atmaero_control_p8 154 failed in check_result failed 
[RT] Error: Test atmaero_control_p8 154 failed in run_test failed 
[RT] Error: Test atmaero_control_p8_rad 155 failed in check_result failed 
[RT] Error: Test atmaero_control_p8_rad 155 failed in run_test failed 
[RT] Error: Test atmaero_control_p8_rad_micro 156 failed in check_result failed 
[RT] Error: Test atmaero_control_p8_rad_micro 156 failed in run_test failed 
Please make changes and add the following label back: cheyenne-intel-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1140715763/20221213220009/ufs-weather-model
[RT] Error: Test cpld_control_p8 001 failed in check_result failed 
[RT] Error: Test cpld_control_p8 001 failed in run_test failed 
[RT] Error: Test cpld_2threads_p8 003 failed in check_result failed 
[RT] Error: Test cpld_2threads_p8 003 failed in run_test failed 
[RT] Error: Test cpld_esmfthreads_p8 004 failed in check_result failed 
[RT] Error: Test cpld_esmfthreads_p8 004 failed in run_test failed 
[RT] Error: Test cpld_decomp_p8 005 failed in check_result failed 
[RT] Error: Test cpld_decomp_p8 005 failed in run_test failed 
[RT] Error: Test cpld_mpi_p8 006 failed in check_result failed 
[RT] Error: Test cpld_mpi_p8 006 failed in run_test failed 
[RT] Error: Test cpld_control_ciceC_p8 007 failed in check_result failed 
[RT] Error: Test cpld_control_ciceC_p8 007 failed in run_test failed 
[RT] Error: Test cpld_control_c192_p8 008 failed in check_result failed 
[RT] Error: Test cpld_control_c192_p8 008 failed in run_test failed 
[RT] Error: Test cpld_bmark_p8 010 failed in check_result failed 
[RT] Error: Test cpld_bmark_p8 010 failed in run_test failed 
[RT] Error: Test cpld_bmark_esmfthreads_p8 012 failed in check_result failed 
[RT] Error: Test cpld_bmark_esmfthreads_p8 012 failed in run_test failed 
[RT] Error: Test cpld_control_noaero_p8 013 failed in check_result failed 
[RT] Error: Test cpld_control_noaero_p8 013 failed in run_test failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 014 failed in check_result failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 014 failed in run_test failed 
[RT] Error: Test cpld_debug_p8 015 failed in check_result failed 
[RT] Error: Test cpld_debug_p8 015 failed in run_test failed 
[RT] Error: Test cpld_debug_noaero_p8 016 failed in check_result failed 
[RT] Error: Test cpld_debug_noaero_p8 016 failed in run_test failed 
[RT] Error: Test cpld_control_noaero_p8_agrid 017 failed in check_result failed 
[RT] Error: Test cpld_control_noaero_p8_agrid 017 failed in run_test failed 
[RT] Error: Test cpld_control_c48 018 failed in check_result failed 
[RT] Error: Test cpld_control_c48 018 failed in run_test failed 
[RT] Error: Test cpld_warmstart_c48 019 failed in check_result failed 
[RT] Error: Test cpld_warmstart_c48 019 failed in run_test failed 
[RT] Error: Test control_p8 041 failed in check_result failed 
[RT] Error: Test control_p8 041 failed in run_test failed 
[RT] Error: Test control_p8_lndp 042 failed in check_result failed 
[RT] Error: Test control_p8_lndp 042 failed in run_test failed 
[RT] Error: Test control_decomp_p8 044 failed in check_result failed 
[RT] Error: Test control_decomp_p8 044 failed in run_test failed 
[RT] Error: Test control_2threads_p8 045 failed in check_result failed 
[RT] Error: Test control_2threads_p8 045 failed in run_test failed 
[RT] Error: Test control_p8_rrtmgp 046 failed in check_result failed 
[RT] Error: Test control_p8_rrtmgp 046 failed in run_test failed 
[RT] Error: Test merra2_thompson 047 failed in check_result failed 
[RT] Error: Test merra2_thompson 047 failed in run_test failed 
[RT] Error: Test rap_rrtmgp 057 failed in check_result failed 
[RT] Error: Test rap_rrtmgp 057 failed in run_test failed 
[RT] Error: Test control_debug_p8 093 failed in check_result failed 
[RT] Error: Test control_debug_p8 093 failed in run_test failed 
[RT] Error: Test rap_rrtmgp_debug 105 failed in check_result failed 
[RT] Error: Test rap_rrtmgp_debug 105 failed in run_test failed 
[RT] Error: Test hafs_regional_atm_thompson_gfdlsf 123 failed in check_result failed 
[RT] Error: Test hafs_regional_atm_thompson_gfdlsf 123 failed in run_test failed 
[RT] Error: Test control_p8_atmlnd_sbs 155 failed in check_result failed 
[RT] Error: Test control_p8_atmlnd_sbs 155 failed in run_test failed 
[RT] Error: Test atmaero_control_p8 157 failed in check_result failed 
[RT] Error: Test atmaero_control_p8 157 failed in run_test failed 
[RT] Error: Test atmaero_control_p8_rad 158 failed in check_result failed 
[RT] Error: Test atmaero_control_p8_rad 158 failed in run_test failed 
[RT] Error: Test atmaero_control_p8_rad_micro 159 failed in check_result failed 
[RT] Error: Test atmaero_control_p8_rad_micro 159 failed in run_test failed 
Please make changes and add the following label back: hera-intel-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1140715763/20221213183010/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1140715763/20221213193615/ufs-weather-model
[RT] Error: Test regional_atmaq 157 failed in run_test failed 
Please make changes and add the following label back: cheyenne-intel-BL

**Comment by dustinswales** [comment]
@grantfirl This last test failed due to disc quota exceeded on Cheyenne. I cleared some space and we should be good to go.
After this runs I will revert the submodules, and WLCLK.

**Comment by dustinswales** [comment]
@grantfirl Once you approve I can merge.

**Review by grantfirl — APPROVED** [review]

**Pull request merged**
