### PR TITLE
Add HWRF NOAH LSM test

### PR DESCRIPTION
**Pull request by grantfirl**
add test that uses HWRF NOAH LSM; add it to rt.conf; change LSM physics namelist entry to use environment variable

### CODE REVIEW

**Comment by grantfirl** [comment]
Associated PRs:
https://github.com/NCAR/ufs-weather-model/pull/37
https://github.com/NCAR/fv3atm/pull/39
https://github.com/NCAR/ccpp-framework/pull/280
https://github.com/NCAR/ccpp-physics/pull/431

**Comment by grantfirl** [comment]
The following files need to be staged and readable at runtime:

[HWRF_NOAH_data.zip](https://github.com/NCAR/ufs-weather-model/files/4453739/HWRF_NOAH_data.zip)

**Comment by grantfirl** [comment]
Compiled the two new suites (HWRF pieces assembled up to this point and GFS_v15p2 with HWRF NOAH LSM) successfully on Hera/Intel.

**Comment by climbfuji** [comment]
> Compiled the two new suites (HWRF pieces assembled up to this point and GFS_v15p2 with HWRF NOAH LSM) successfully on Hera/Intel.

Ok, great. You can hold back testing on hera for the moment, since we will need to update your code anyway after saSAS went in and rerun all the tests.

**Comment by grantfirl** [comment]
Superceded by #47

**Pull request closed without merging**
