### PR TITLE
UFS-dev PR#54

### PR DESCRIPTION
**Pull request by grantfirl**
Identical to https://github.com/ufs-community/ufs-weather-model/pull/1658

### CODE REVIEW

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1298056327/20230412184506/ufs-weather-model
[RT] Error: Test rap_control 005 failed in check_result failed 
[RT] Error: Test rap_control 005 failed in run_test failed 
[RT] Error: Test rap_decomp 006 failed in check_result failed 
[RT] Error: Test rap_decomp 006 failed in run_test failed 
[RT] Error: Test rap_2threads 007 failed in check_result failed 
[RT] Error: Test rap_2threads 007 failed in run_test failed 
[RT] Error: Test rap_sfcdiff 009 failed in check_result failed 
[RT] Error: Test rap_sfcdiff 009 failed in run_test failed 
[RT] Error: Test rap_sfcdiff_decomp 010 failed in check_result failed 
[RT] Error: Test rap_sfcdiff_decomp 010 failed in run_test failed 
[RT] Error: Test hrrr_control 012 failed in check_result failed 
[RT] Error: Test hrrr_control 012 failed in run_test failed 
[RT] Error: Test hrrr_control_2threads 013 failed in check_result failed 
[RT] Error: Test hrrr_control_2threads 013 failed in run_test failed 
[RT] Error: Test hrrr_control_decomp 014 failed in check_result failed 
[RT] Error: Test hrrr_control_decomp 014 failed in run_test failed 
[RT] Error: Test rrfs_v1beta 016 failed in check_result failed 
[RT] Error: Test rrfs_v1beta 016 failed in run_test failed 
[RT] Error: Test rrfs_smoke_conus13km_hrrr_warm 017 failed in check_result failed 
[RT] Error: Test rrfs_smoke_conus13km_hrrr_warm 017 failed in run_test failed 
[RT] Error: Test rrfs_smoke_conus13km_hrrr_warm_2threads 018 failed in check_result failed 
[RT] Error: Test rrfs_smoke_conus13km_hrrr_warm_2threads 018 failed in run_test failed 
[RT] Error: Test rrfs_conus13km_hrrr_warm 019 failed in check_result failed 
[RT] Error: Test rrfs_conus13km_hrrr_warm 019 failed in run_test failed 
[RT] Error: Test rrfs_smoke_conus13km_radar_tten_warm 020 failed in check_result failed 
[RT] Error: Test rrfs_smoke_conus13km_radar_tten_warm 020 failed in run_test failed 
[RT] Error: Test regional_debug 022 failed in check_result failed 
[RT] Error: Test regional_debug 022 failed in run_test failed 
[RT] Error: Test rap_control_debug 023 failed in check_result failed 
[RT] Error: Test rap_control_debug 023 failed in run_test failed 
[RT] Error: Test hrrr_control_debug 024 failed in check_result failed 
[RT] Error: Test hrrr_control_debug 024 failed in run_test failed 
[RT] Error: Test rap_diag_debug 025 failed in check_result failed 
[RT] Error: Test rap_diag_debug 025 failed in run_test failed 
[RT] Error: Test rap_noah_sfcdiff_cires_ugwp_debug 026 failed in check_result failed 
[RT] Error: Test rap_noah_sfcdiff_cires_ugwp_debug 026 failed in run_test failed 
[RT] Error: Test rap_progcld_thompson_debug 027 failed in check_result failed 
[RT] Error: Test rap_progcld_thompson_debug 027 failed in run_test failed 
[RT] Error: Test rrfs_v1beta_debug 028 failed in check_result failed 
[RT] Error: Test rrfs_v1beta_debug 028 failed in run_test failed 
[RT] Error: Test rrfs_smoke_conus13km_hrrr_warm_debug 032 failed in check_result failed 
[RT] Error: Test rrfs_smoke_conus13km_hrrr_warm_debug 032 failed in run_test failed 
[RT] Error: Test rrfs_smoke_conus13km_hrrr_warm_debug_2threads 033 failed in check_result failed 
[RT] Error: Test rrfs_smoke_conus13km_hrrr_warm_debug_2threads 033 failed in run_test failed 
[RT] Error: Test rrfs_conus13km_hrrr_warm_debug 034 failed in check_result failed 
[RT] Error: Test rrfs_conus13km_hrrr_warm_debug 034 failed in run_test failed 
[RT] Error: Test rap_control_dyn32_phy32 036 failed in check_result failed 
[RT] Error: Test rap_control_dyn32_phy32 036 failed in run_test failed 
[RT] Error: Test hrrr_control_dyn32_phy32 037 failed in check_result failed 
[RT] Error: Test hrrr_control_dyn32_phy32 037 failed in run_test failed 
[RT] Error: Test rap_2threads_dyn32_phy32 038 failed in check_result failed 
[RT] Error: Test rap_2threads_dyn32_phy32 038 failed in run_test failed 
[RT] Error: Test hrrr_control_2threads_dyn32_phy32 039 failed in check_result failed 
[RT] Error: Test hrrr_control_2threads_dyn32_phy32 039 failed in run_test failed 
[RT] Error: Test hrrr_control_decomp_dyn32_phy32 040 failed in check_result failed 
[RT] Error: Test hrrr_control_decomp_dyn32_phy32 040 failed in run_test failed 
[RT] Error: Test rap_control_dyn64_phy32 043 failed in check_result failed 
[RT] Error: Test rap_control_dyn64_phy32 043 failed in run_test failed 
[RT] Error: Test rap_control_debug_dyn32_phy32 044 failed in check_result failed 
[RT] Error: Test rap_control_debug_dyn32_phy32 044 failed in run_test failed 
[RT] Error: Test hrrr_control_debug_dyn32_phy32 045 failed in check_result failed 
[RT] Error: Test hrrr_control_debug_dyn32_phy32 045 failed in run_test failed 
[RT] Error: Test rap_control_dyn64_phy32_debug 046 failed in check_result failed 
[RT] Error: Test rap_control_dyn64_phy32_debug 046 failed in run_test failed 
Please make changes and add the following label back: cheyenne-gnu-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1298056327/20230412192603/ufs-weather-model
[RT] Error: Test cpld_control_p8_mixedmode 001 failed in run_test failed 
[RT] Error: Test cpld_control_gfsv17 002 failed in run_test failed 
[RT] Error: Test cpld_control_p8 003 failed in run_test failed 
[RT] Error: Test cpld_2threads_p8 005 failed in run_test failed 
[RT] Error: Test cpld_decomp_p8 006 failed in run_test failed 
[RT] Error: Test cpld_mpi_p8 007 failed in run_test failed 
[RT] Error: Test cpld_control_ciceC_p8 008 failed in run_test failed 
[RT] Error: Test cpld_control_c192_p8 009 failed in run_test failed 
[RT] Error: Test cpld_control_noaero_p8 011 failed in run_test failed 
[RT] Error: Test cpld_control_nowave_noaero_p8 012 failed in run_test failed 
[RT] Error: Test cpld_control_noaero_p8_agrid 015 failed in run_test failed 
[RT] Error: Test cpld_control_c48 016 failed in run_test failed 
[RT] Error: Test control_c192 024 failed in run_test failed 
[RT] Error: Test control_c384 025 failed in run_test failed 
[RT] Error: Test control_c384gdas 026 failed in run_test failed 
[RT] Error: Test control_restart_p8 034 failed in run_test failed 
[RT] Error: Test control_p8_mynn 038 failed in run_test failed 
[RT] Error: Test merra2_thompson 039 failed in run_test failed 
[RT] Error: Test regional_control 040 failed in run_test failed 
[RT] Error: Test regional_decomp 042 failed in run_test failed 
[RT] Error: Test regional_2threads 043 failed in run_test failed 
[RT] Error: Test regional_noquilt 044 failed in run_test failed 
[RT] Error: Test regional_netcdf_parallel 045 failed in run_test failed 
[RT] Error: Test regional_2dwrtdecomp 046 failed in run_test failed 
[RT] Error: Test regional_wofs 047 failed in run_test failed 
[RT] Error: Test rap_control 048 failed in run_test failed 
[RT] Error: Test regional_spp_sppt_shum_skeb 049 failed in run_test failed 
[RT] Error: Test rap_decomp 050 failed in check_result failed 
[RT] Error: Test rap_decomp 050 failed in run_test failed 
[RT] Error: Test rap_2threads 051 failed in run_test failed 
[RT] Error: Test rap_sfcdiff 053 failed in run_test failed 
[RT] Error: Test rap_sfcdiff_decomp 054 failed in check_result failed 
[RT] Error: Test rap_sfcdiff_decomp 054 failed in run_test failed 
[RT] Error: Test hrrr_control 056 failed in run_test failed 
[RT] Error: Test hrrr_control_decomp 057 failed in run_test failed 
[RT] Error: Test hrrr_control_2threads 058 failed in run_test failed 
[RT] Error: Test rrfs_v1beta 060 failed in run_test failed 
[RT] Error: Test rrfs_v1nssl 061 failed in run_test failed 
[RT] Error: Test rrfs_v1nssl_nohailnoccn 062 failed in run_test failed 
[RT] Error: Test rrfs_smoke_conus13km_hrrr_warm 063 failed in check_result failed 
[RT] Error: Test rrfs_smoke_conus13km_hrrr_warm 063 failed in run_test failed 
[RT] Error: Test rrfs_smoke_conus13km_hrrr_warm_2threads 064 failed in run_test failed 
[RT] Error: Test rrfs_conus13km_hrrr_warm 065 failed in run_test failed 
[RT] Error: Test rrfs_smoke_conus13km_radar_tten_warm 066 failed in run_test failed 
[RT] Error: Test control_csawmg 067 failed in run_test failed 
[RT] Error: Test control_csawmgt 068 failed in run_test failed 
[RT] Error: Test control_ras 069 failed in run_test failed 
[RT] Error: Test control_wam 070 failed in run_test failed 
[RT] Error: Test control_wam_debug 099 failed in run_test failed 
[RT] Error: Test hafs_regional_docn 127 failed in run_test failed 
[RT] Error: Test hafs_regional_docn_oisst 128 failed in run_test failed 
[RT] Error: Test hafs_regional_datm_cdeps 129 failed in run_test failed 
[RT] Error: Test datm_cdeps_lnd_gswp3 145 failed in run_test failed 
[RT] Error: Test compile_008 failed in run_compile failed 
[RT] Error: Test compile_013 failed in run_compile failed 
[RT] Error: Test compile_014 failed in run_compile failed 
[RT] Error: Test compile_016 failed in run_compile failed 
[RT] Error: Test compile_017 failed in run_compile failed 
[RT] Error: Test compile_018 failed in run_compile failed 
[RT] Error: Test compile_019 failed in run_compile failed 
[RT] Error: Test compile_020 failed in run_compile failed 
[RT] Error: Test compile_021 failed in run_compile failed 
[RT] Error: Test compile_022 failed in run_compile failed 
[RT] Error: Test compile_024 failed in run_compile failed 
[RT] Error: Test compile_025 failed in run_compile failed 
[RT] Error: Test compile_026 failed in run_compile failed 
[RT] Error: Test compile_028 failed in run_compile failed 
[RT] Error: Test compile_029 failed in run_compile failed 
[RT] Error: Test compile_030 failed in run_compile failed 
[RT] Error: Test compile_031 failed in run_compile failed 
[RT] Error: Test compile_032 failed in run_compile failed 
[RT] Error: Test compile_033 failed in run_compile failed 
Please make changes and add the following label back: cheyenne-intel-RT

**Comment by grantfirl** [comment]
Expected test failures for Hera-Intel:
regional_control 042 failed in check_result
regional_decomp 044 failed in check_result
regional_2threads 045 failed in check_result
regional_noquilt 046 failed in check_result
regional_netcdf_parallel 047 failed in check_result
regional_2dwrtdecomp 048 failed in check_result
regional_wofs 049 failed in check_result
rap_control 050 failed in check_result
regional_spp_sppt_shum_skeb 051 failed in check_result
rap_decomp 052 failed in check_result
rap_2threads 053 failed in check_result
rap_sfcdiff 055 failed in check_result
rap_sfcdiff_decomp 056 failed in check_result
hrrr_control 058 failed in check_result
hrrr_control_decomp 059 failed in check_result
hrrr_control_2threads 060 failed in check_result
rrfs_v1beta 062 failed in check_result
rrfs_v1nssl 063 failed in check_result
rrfs_v1nssl_nohailnoccn 064 failed in check_result
rrfs_conus13km_hrrr_warm 065 failed in check_result
rrfs_smoke_conus13km_hrrr_warm 066 failed in check_result
rrfs_conus13km_radar_tten_warm 067 failed in check_result
rrfs_conus13km_hrrr_warm_2threads 068 failed in check_result
rrfs_conus13km_radar_tten_warm_2threads 069 failed in check_result
regional_control_faster 075 failed in check_result
rrfs_conus13km_hrrr_warm_debug 076 failed in check_result
rrfs_conus13km_radar_tten_warm_debug 077 failed in check_result
regional_debug 087 failed in check_result
rap_control_debug 088 failed in check_result
hrrr_control_debug 089 failed in check_result
rap_unified_drag_suite_debug 090 failed in check_result
rap_diag_debug 091 failed in check_result
rap_cires_ugwp_debug 092 failed in check_result
rap_unified_ugwp_debug 093 failed in check_result
rap_lndp_debug 094 failed in check_result
rap_flake_debug 095 failed in check_result
rap_progcld_thompson_debug 096 failed in check_result
rap_noah_debug 097 failed in check_result
rap_sfcdiff_debug 098 failed in check_result
rap_noah_sfcdiff_cires_ugwp_debug 099 failed in check_result
rrfs_v1beta_debug 100 failed in check_result
regional_spp_sppt_shum_skeb_dyn32_phy32 102 failed in check_result
rap_control_dyn32_phy32 103 failed in check_result
hrrr_control_dyn32_phy32 104 failed in check_result
rap_2threads_dyn32_phy32 105 failed in check_result
hrrr_control_2threads_dyn32_phy32 106 failed in check_result
hrrr_control_decomp_dyn32_phy32 107 failed in check_result
rap_control_dyn64_phy32 110 failed in check_result
rap_control_debug_dyn32_phy32 111 failed in check_result
hrrr_control_debug_dyn32_phy32 112 failed in check_result
rap_control_dyn64_phy32_debug 113 failed in check_result

Expected failures for Hera-Gnu:
rap_control 005 failed in check_result
rap_decomp 006 failed in check_result
rap_2threads 007 failed in check_result
rap_sfcdiff 009 failed in check_result
rap_sfcdiff_decomp 010 failed in check_result
hrrr_control 012 failed in check_result
hrrr_control_2threads 013 failed in check_result
hrrr_control_decomp 014 failed in check_result
rrfs_v1beta 016 failed in check_result
rrfs_conus13km_hrrr_warm 017 failed in check_result
rrfs_smoke_conus13km_hrrr_warm 018 failed in check_result
rrfs_conus13km_radar_tten_warm 019 failed in check_result
rrfs_conus13km_radar_tten_warm_2threads 020 failed in check_result
regional_debug 022 failed in check_result
rap_control_debug 023 failed in check_result
hrrr_control_debug 024 failed in check_result
rap_diag_debug 025 failed in check_result
rap_noah_sfcdiff_cires_ugwp_debug 026 failed in check_result
rap_progcld_thompson_debug 027 failed in check_result
rrfs_v1beta_debug 028 failed in check_result
rrfs_conus13km_hrrr_warm_debug 032 failed in check_result
rrfs_conus13km_radar_tten_warm_debug 033 failed in check_result
rap_control_dyn32_phy32 035 failed in check_result
hrrr_control_dyn32_phy32 036 failed in check_result
rap_2threads_dyn32_phy32 037 failed in check_result
hrrr_control_2threads_dyn32_phy32 038 failed in check_result
hrrr_control_decomp_dyn32_phy32 039 failed in check_result
rap_control_dyn64_phy32 042 failed in check_result
rap_control_debug_dyn32_phy32 043 failed in check_result
hrrr_control_debug_dyn32_phy32 044 failed in check_result
rap_control_dyn64_phy32_debug 045 failed in check_result

Also, any tests that use the smoke/dust code.

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1298056327/20230413084507/ufs-weather-model
[RT] Error: Test cpld_restart_p8 004 failed in run_test failed 
[RT] Error: Test cpld_restart_c192_p8 010 failed in run_test failed 
[RT] Error: Test control_p8_mynn 038 failed in check_result failed 
[RT] Error: Test control_p8_mynn 038 failed in run_test failed 
[RT] Error: Test regional_control 040 failed in run_test failed 
[RT] Error: Test regional_decomp 042 failed in run_test failed 
[RT] Error: Test regional_2threads 043 failed in run_test failed 
[RT] Error: Test regional_noquilt 044 failed in run_test failed 
[RT] Error: Test regional_netcdf_parallel 045 failed in run_test failed 
[RT] Error: Test regional_2dwrtdecomp 046 failed in run_test failed 
[RT] Error: Test regional_wofs 047 failed in run_test failed 
[RT] Error: Test rap_control 048 failed in run_test failed 
[RT] Error: Test regional_spp_sppt_shum_skeb 049 failed in run_test failed 
[RT] Error: Test rap_decomp 050 failed in run_test failed 
[RT] Error: Test rap_2threads 051 failed in run_test failed 
[RT] Error: Test rap_sfcdiff 053 failed in run_test failed 
[RT] Error: Test rap_sfcdiff_decomp 054 failed in run_test failed 
[RT] Error: Test hrrr_control 056 failed in run_test failed 
[RT] Error: Test hrrr_control_decomp 057 failed in run_test failed 
[RT] Error: Test hrrr_control_2threads 058 failed in run_test failed 
[RT] Error: Test rrfs_v1beta 060 failed in run_test failed 
[RT] Error: Test rrfs_v1nssl 061 failed in run_test failed 
[RT] Error: Test rrfs_v1nssl_nohailnoccn 062 failed in run_test failed 
[RT] Error: Test rrfs_smoke_conus13km_hrrr_warm 063 failed in run_test failed 
[RT] Error: Test rrfs_smoke_conus13km_hrrr_warm_2threads 064 failed in run_test failed 
[RT] Error: Test rrfs_conus13km_hrrr_warm 065 failed in run_test failed 
[RT] Error: Test rrfs_smoke_conus13km_radar_tten_warm 066 failed in run_test failed 
[RT] Error: Test control_csawmg 067 failed in run_test failed 
[RT] Error: Test control_csawmgt 068 failed in run_test failed 
[RT] Error: Test control_ras 069 failed in run_test failed 
[RT] Error: Test control_wam 070 failed in run_test failed 
[RT] Error: Test control_p8_faster 071 failed in run_test failed 
[RT] Error: Test regional_control_faster 072 failed in run_test failed 
[RT] Error: Test rrfs_smoke_conus13km_hrrr_warm_debug 073 failed in run_test failed 
[RT] Error: Test rrfs_smoke_conus13km_hrrr_warm_debug_2threads 074 failed in run_test failed 
[RT] Error: Test rrfs_conus13km_hrrr_warm_debug 075 failed in run_test failed 
[RT] Error: Test control_CubedSphereGrid_debug 076 failed in run_test failed 
[RT] Error: Test control_wrtGauss_netcdf_parallel_debug 077 failed in run_test failed 
[RT] Error: Test control_stochy_debug 078 failed in run_test failed 
[RT] Error: Test control_lndp_debug 079 failed in run_test failed 
[RT] Error: Test control_csawmg_debug 080 failed in run_test failed 
[RT] Error: Test control_csawmgt_debug 081 failed in run_test failed 
[RT] Error: Test control_ras_debug 082 failed in run_test failed 
[RT] Error: Test control_diag_debug 083 failed in run_test failed 
[RT] Error: Test control_debug_p8 084 failed in run_test failed 
[RT] Error: Test regional_debug 085 failed in run_test failed 
[RT] Error: Test rap_control_debug 086 failed in run_test failed 
[RT] Error: Test hrrr_control_debug 087 failed in run_test failed 
[RT] Error: Test rap_unified_drag_suite_debug 088 failed in run_test failed 
[RT] Error: Test rap_diag_debug 089 failed in run_test failed 
[RT] Error: Test rap_cires_ugwp_debug 090 failed in run_test failed 
[RT] Error: Test rap_unified_ugwp_debug 091 failed in run_test failed 
[RT] Error: Test rap_lndp_debug 092 failed in run_test failed 
[RT] Error: Test rap_flake_debug 093 failed in run_test failed 
[RT] Error: Test rap_progcld_thompson_debug 094 failed in run_test failed 
[RT] Error: Test rap_noah_debug 095 failed in run_test failed 
[RT] Error: Test rap_sfcdiff_debug 096 failed in run_test failed 
[RT] Error: Test rap_noah_sfcdiff_cires_ugwp_debug 097 failed in run_test failed 
[RT] Error: Test rrfs_v1beta_debug 098 failed in run_test failed 
[RT] Error: Test control_wam_debug 099 failed in run_test failed 
[RT] Error: Test regional_spp_sppt_shum_skeb_dyn32_phy32 100 failed in run_test failed 
[RT] Error: Test rap_control_dyn32_phy32 101 failed in run_test failed 
[RT] Error: Test hrrr_control_dyn32_phy32 102 failed in run_test failed 
[RT] Error: Test rap_2threads_dyn32_phy32 103 failed in run_test failed 
[RT] Error: Test hrrr_control_2threads_dyn32_phy32 104 failed in run_test failed 
[RT] Error: Test hrrr_control_decomp_dyn32_phy32 105 failed in run_test failed 
[RT] Error: Test rap_control_dyn64_phy32 108 failed in run_test failed 
[RT] Error: Test rap_control_debug_dyn32_phy32 109 failed in run_test failed 
[RT] Error: Test hrrr_control_debug_dyn32_phy32 110 failed in run_test failed 
[RT] Error: Test rap_control_dyn64_phy32_debug 111 failed in run_test failed 
[RT] Error: Test hafs_regional_storm_following_1nest_atm_ocn_debug 125 failed in run_test failed 
[RT] Error: Test datm_cdeps_control_cfsr 130 failed in run_test failed 
[RT] Error: Test datm_cdeps_control_gefs 132 failed in run_test failed 
[RT] Error: Test datm_cdeps_iau_gefs 133 failed in run_test failed 
[RT] Error: Test datm_cdeps_stochy_gefs 134 failed in run_test failed 
[RT] Error: Test datm_cdeps_ciceC_cfsr 135 failed in run_test failed 
[RT] Error: Test datm_cdeps_bulk_cfsr 136 failed in run_test failed 
[RT] Error: Test datm_cdeps_bulk_gefs 137 failed in run_test failed 
[RT] Error: Test datm_cdeps_mx025_cfsr 138 failed in run_test failed 
[RT] Error: Test datm_cdeps_mx025_gefs 139 failed in run_test failed 
[RT] Error: Test datm_cdeps_multiple_files_cfsr 140 failed in run_test failed 
[RT] Error: Test datm_cdeps_3072x1536_cfsr 141 failed in run_test failed 
[RT] Error: Test datm_cdeps_gfs 142 failed in run_test failed 
[RT] Error: Test datm_cdeps_debug_cfsr 143 failed in run_test failed 
[RT] Error: Test datm_cdeps_lnd_gswp3 145 failed in run_test failed 
[RT] Error: Test control_p8_atmlnd_sbs 147 failed in run_test failed 
[RT] Error: Test compile_020 failed in run_compile failed 
[RT] Error: Test compile_022 failed in run_compile failed 
[RT] Error: Test compile_023 failed in run_compile failed 
[RT] Error: Test compile_026 failed in run_compile failed 
[RT] Error: Test compile_029 failed in run_compile failed 
[RT] Error: Test compile_030 failed in run_compile failed 
[RT] Error: Test compile_031 failed in run_compile failed 
[RT] Error: Test compile_032 failed in run_compile failed 
[RT] Error: Test compile_033 failed in run_compile failed 
Please make changes and add the following label back: cheyenne-intel-RT

**Comment by dustinswales** [comment]
@grantfirl I just cleaned up the space on Cheyenne.

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1298056327/20230413183015/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1298056327/20230413195619/ufs-weather-model
Please make changes and add the following label back: hera-gnu-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1298056327/20230413144506/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1298056327/20230413151437/ufs-weather-model
Please make changes and add the following label back: cheyenne-gnu-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1298056327/20230413205645/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1298056327/20230413222149/ufs-weather-model
Please make changes and add the following label back: hera-intel-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1298056327/20230413155118/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1298056327/20230413170749/ufs-weather-model
Please make changes and add the following label back: cheyenne-intel-BL

**Comment by grantfirl** [comment]
@dustinswales Please approve when you get a chance. This should be ready to merge.

**Review by dustinswales — APPROVED** [review]

**Pull request merged**
