### PR TITLE
UFS-dev PR#139

### PR DESCRIPTION
**Pull request by grantfirl**
Identical to https://github.com/ufs-community/ufs-weather-model/pull/2044 (BL change expected -- see below for which tests change)

Also contains:
https://github.com/ufs-community/ufs-weather-model/pull/1784 (no BL change)
https://github.com/ufs-community/ufs-weather-model/pull/2021 (no BL change)
https://github.com/ufs-community/ufs-weather-model/pull/1979 (BL change and new input) - cpld_control_c48_intel 
https://github.com/ufs-community/ufs-weather-model/pull/2010 (BL change -- see below)
https://github.com/ufs-community/ufs-weather-model/pull/2009 (BL change) - cpld_s2sa_p8
https://github.com/ufs-community/ufs-weather-model/pull/1836 (no BL change)
https://github.com/ufs-community/ufs-weather-model/pull/2041 (no BL change)

### CODE REVIEW

**Comment by grantfirl** [comment]
Tests expected to change for 2044:

COMPILE | rrfs | intel | -DAPP=ATM -DCCPP_SUITES=FV3_RAP,FV3_RAP_sfcdiff,FV3_HRRR,FV3_RRFS_v1beta,FV3_RRFS_v1nssl -D32BIT=ON | | fv3 |
RUN | hrrr_control                                      | - noaacloud                | baseline |
RUN | hrrr_control_decomp                               | - noaacloud                |          |
RUN | hrrr_control_2threads                             | - noaacloud                |          |
RUN | hrrr_control_restart                              | - noaacloud                |          | hrrr_control
COMPILE | atm_debug_dyn32 | intel | -DAPP=ATM -DDEBUG=ON -D32BIT=ON -DCCPP_SUITES=FV3_HRRR,FV3_GFS_v16,FV3_GFS_v16_csawmg,FV3_GFS_v16_ras,FV3_GFS_v17_p8,FV3_GFS_v15_thompson_mynn_lam3km,FV3_RAP,FV3_RAP_unified_ugwp,FV3_RAP_cires_ugwp,FV3_RAP_flake,FV3_RAP_clm_lake,FV3_RAP_noah,FV3_RAP_sfcdiff,FV3_RAP_noah_sfcdiff_cires_ugwp,FV3_RRFS_v1beta,FV3_HRRR_c3,FV3_HRRR_gf,FV3_global_nest_v1 | - noaacloud  | fv3 |
RUN | hrrr_control_debug                                | - noaacloud                  | baseline |
RUN | hrrr_gf_debug                                     | - noaacloud                  | baseline |
RUN | hrrr_c3_debug                                     | - noaacloud                  | baseline |
RUN | rap_clm_lake_debug                                | - noaacloud                  | baseline |
COMPILE | rrfs_dyn32_phy32 | intel | -DAPP=ATM -DCCPP_SUITES=FV3_RAP,FV3_HRRR -D32BIT=ON -DCCPP_32BIT=ON |  - noaacloud  | fv3 |
RUN | hrrr_control_dyn32_phy32                          | - noaacloud                  | baseline |
RUN | hrrr_control_2threads_dyn32_phy32                 | - derecho noaacloud          |          |
RUN | hrrr_control_decomp_dyn32_phy32                   | - noaacloud                  |          |
RUN | hrrr_control_restart_dyn32_phy32                  | - noaacloud                  |          | hrrr_control_dyn32_phy32
COMPILE | rrfs_dyn32_phy32_debug | intel | -DAPP=ATM -DCCPP_SUITES=FV3_RAP,FV3_HRRR,FV3_HRRR_gf -D32BIT=ON -DCCPP_32BIT=ON -DDEBUG=ON | - noaacloud  | fv3 |
RUN | hrrr_control_debug_dyn32_phy32                    |  - noaacloud                 | baseline |
COMPILE | rrfs | gnu | -DAPP=ATM -DCCPP_SUITES=FV3_RAP,FV3_RAP_sfcdiff,FV3_HRRR,FV3_RRFS_v1beta -D32BIT=ON | + hera hercules | fv3 |
RUN | hrrr_control                                      | + hera hercules            | baseline |
RUN | hrrr_control_noqr                                 | + hera hercules            |          |
RUN | hrrr_control_2threads                             | + hera hercules            |          |
RUN | hrrr_control_decomp                               | + hera hercules            |          |
RUN | hrrr_control_restart                              | + hera hercules            |          | hrrr_control
RUN | hrrr_control_restart_noqr                         | + hera hercules            |          | hrrr_control_noqr
COMPILE | atm_dyn32_debug | gnu | -DAPP=ATM -D32BIT=ON -DDEBUG=ON | + hera hercules | fv3 |
RUN | hrrr_control_debug                                | + hera hercules            | baseline |
RUN | hrrr_gf_debug                                     | + hera hercules            | baseline |
RUN | hrrr_c3_debug                                     | + hera hercules            | baseline |
RUN | rap_clm_lake_debug                                | + hera hercules            | baseline |
COMPILE | rrfs_dyn32_phy32 | gnu | -DAPP=ATM -DCCPP_SUITES=FV3_RAP,FV3_HRRR -D32BIT=ON -DCCPP_32BIT=ON | + hera hercules | fv3 |
RUN | hrrr_control_dyn32_phy32                          | + hera hercules            | baseline |
RUN | hrrr_control_2threads_dyn32_phy32                 | + hera hercules            |          |
RUN | hrrr_control_decomp_dyn32_phy32                   | + hera hercules            |          |
RUN | hrrr_control_restart_dyn32_phy32                  | + hera hercules            |          | hrrr_control_dyn32_phy32
COMPILE | atm_dyn32_phy32_debug | gnu | -DAPP=ATM -D32BIT=ON -DCCPP_32BIT=ON -DDEBUG=ON | + hera hercules | fv3 |
RUN | hrrr_control_debug_dyn32_phy32                    | + hera hercules            | baseline |

**Comment by grantfirl** [comment]
RT failures expected for 2010:

7831:FAILED TESTS:
7832:147 hafs_regional_docn_intel failed in check_result
7833:hafs_regional_docn_intel 147 failed in run_test
7834:148 hafs_regional_docn_oisst_intel failed in check_result
7835:hafs_regional_docn_oisst_intel 148 failed in run_test
7836:149 hafs_regional_datm_cdeps_intel failed in check_result
7837:hafs_regional_datm_cdeps_intel 149 failed in run_test

**Review by mkavulich — APPROVED** [review]
That's a long list of files changed! I gave it a quick glance and nothing seemed awry, but I did *not* scrutinize every test file change.

**Comment by grantfirl** [comment]
Yes, it's a surprising number of file changes. Several of the preceding PRs (non-CCPP ones) changed 50+ files each. Some of it is related to machine support changes and there was one that "cleaned up" the test files, of which there are on the order of ~100.

**Pull request merged**
