### PR TITLE
UFS-dev PR#18

### PR DESCRIPTION
**Pull request by grantfirl**
Identical to https://github.com/ufs-community/ufs-weather-model/pull/1480

### CODE REVIEW

**Comment by grantfirl** [comment]
Contains changes from https://github.com/NCAR/ufs-weather-model/pull/79 until that is merged

**Comment by grantfirl** [comment]
Requires new baselines due to new RT: see https://github.com/ufs-community/ufs-weather-model/pull/1480

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1172581620/20221220213010/ufs-weather-model
[BL] ERROR: Baseline location exists before creation:
/scratch1/BMC/gmtb/RT/NCAR/main-20221219/INTEL
Please make changes and add the following label back: hera-intel-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: RT
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1172581620/20221220143010/ufs-weather-model
[RT] Error: Test cpld_control_gfsv17 001 failed in check_result failed 
[RT] Error: Test cpld_control_gfsv17 001 failed in run_test failed 
[RT] Error: Test cpld_control_noaero_p8 011 failed in check_result failed 
[RT] Error: Test cpld_control_noaero_p8 011 failed in run_test failed 
[RT] Error: Test cpld_debug_noaero_p8 014 failed in check_result failed 
[RT] Error: Test cpld_debug_noaero_p8 014 failed in run_test failed 
Please make changes and add the following label back: cheyenne-intel-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: RT
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1172581620/20221220211513/ufs-weather-model
[RT] Error: Test cpld_control_gfsv17 001 failed in check_result failed 
[RT] Error: Test cpld_control_gfsv17 001 failed in run_test failed 
[RT] Error: Test cpld_control_noaero_p8 013 failed in check_result failed 
[RT] Error: Test cpld_control_noaero_p8 013 failed in run_test failed 
[RT] Error: Test cpld_debug_noaero_p8 016 failed in check_result failed 
[RT] Error: Test cpld_debug_noaero_p8 016 failed in run_test failed 
Please make changes and add the following label back: hera-intel-RT

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1172581620/20221220161507/ufs-weather-model
[BL] ERROR: Baseline location exists before creation:
/glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/NCAR/main-20221219/GNU
Please make changes and add the following label back: cheyenne-gnu-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1172581620/20221220161623/ufs-weather-model
[BL] ERROR: Baseline location exists before creation:
/glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/NCAR/main-20221219/INTEL
Please make changes and add the following label back: cheyenne-intel-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1172581620/20221220231517/ufs-weather-model
[BL] ERROR: Baseline location exists before creation:
/scratch1/BMC/gmtb/RT/NCAR/main-20221219/GNU
Please make changes and add the following label back: hera-gnu-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1172581620/20221220231755/ufs-weather-model
[BL] ERROR: Baseline location exists before creation:
/scratch1/BMC/gmtb/RT/NCAR/main-20221219/INTEL
Please make changes and add the following label back: hera-intel-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1172581620/20221220163010/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1172581620/20221220165942/ufs-weather-model
[RT] Error: Test rap_decomp 006 failed in run_test failed 
[RT] Error: Test rap_restart 008 failed in run_test failed 
[RT] Error: Test rap_sfcdiff 009 failed in run_test failed 
[RT] Error: Test rap_sfcdiff_decomp 010 failed in run_test failed 
[RT] Error: Test hrrr_control_2threads 013 failed in run_test failed 
[RT] Error: Test hrrr_control_decomp 014 failed in run_test failed 
[RT] Error: Test hrrr_control_restart 015 failed in run_test failed 
[RT] Error: Test rrfs_v1beta 016 failed in run_test failed 
[RT] Error: Test regional_debug 022 failed in run_test failed 
[RT] Error: Test rap_diag_debug 025 failed in run_test failed 
[RT] Error: Test control_debug_p8 031 failed in run_test failed 
[RT] Error: Test rrfs_conus13km_radar_tten_warm_debug 033 failed in run_test failed 
[RT] Error: Test rap_control_dyn32_phy32 035 failed in run_test failed 
[RT] Error: Test rap_2threads_dyn32_phy32 037 failed in run_test failed 
[RT] Error: Test rap_control_dyn64_phy32_debug 045 failed in run_test failed 
[RT] Error: Test cpld_control_p8 046 failed in run_test failed 
[RT] Error: Test compile_006 failed in run_compile failed 
Please make changes and add the following label back: cheyenne-gnu-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1172581620/20221220164507/ufs-weather-model
[BL] Error: Test cpld_control_c192_p8 004 failed in run_test failed 
[BL] Error: Test rrfs_conus13km_hrrr_warm_debug 047 failed in run_test failed 
[BL] Error: Test rrfs_conus13km_radar_tten_warm_debug 048 failed in run_test failed 
[BL] Error: Test control_CubedSphereGrid_debug 049 failed in run_test failed 
[BL] Error: Test control_wrtGauss_netcdf_parallel_debug 050 failed in run_test failed 
[BL] Error: Test control_csawmg_debug 053 failed in run_test failed 
[BL] Error: Test control_csawmgt_debug 054 failed in run_test failed 
[BL] Error: Test control_ras_debug 055 failed in run_test failed 
[BL] Error: Test control_diag_debug 056 failed in run_test failed 
[BL] Error: Test control_debug_p8 057 failed in run_test failed 
[BL] Error: Test regional_debug 058 failed in run_test failed 
[BL] Error: Test rap_control_debug 059 failed in run_test failed 
[BL] Error: Test hrrr_control_debug 060 failed in run_test failed 
[BL] Error: Test rap_diag_debug 061 failed in run_test failed 
[BL] Error: Test rap_cires_ugwp_debug 062 failed in run_test failed 
[BL] Error: Test rap_lndp_debug 063 failed in run_test failed 
[BL] Error: Test rap_flake_debug 064 failed in run_test failed 
[BL] Error: Test rap_progcld_thompson_debug 065 failed in run_test failed 
[BL] Error: Test rap_noah_debug 066 failed in run_test failed 
[BL] Error: Test rap_rrtmgp_debug 067 failed in run_test failed 
[BL] Error: Test rap_sfcdiff_debug 068 failed in run_test failed 
[BL] Error: Test rap_noah_sfcdiff_cires_ugwp_debug 069 failed in run_test failed 
[BL] Error: Test rrfs_v1beta_debug 070 failed in run_test failed 
[BL] Error: Test hafs_regional_atm 079 failed in run_test failed 
[BL] Error: Test hafs_regional_atm_thompson_gfdlsf 080 failed in run_test failed 
[BL] Error: Test hafs_regional_atm_ocn 081 failed in run_test failed 
[BL] Error: Test hafs_regional_atm_wav 082 failed in run_test failed 
[BL] Error: Test hafs_regional_atm_ocn_wav 083 failed in run_test failed 
[BL] Error: Test hafs_regional_1nest_atm 084 failed in run_test failed 
[BL] Error: Test hafs_regional_telescopic_2nests_atm 085 failed in run_test failed 
[BL] Error: Test hafs_global_1nest_atm 086 failed in run_test failed 
[BL] Error: Test hafs_global_multiple_4nests_atm 087 failed in run_test failed 
[BL] Error: Test hafs_regional_specified_moving_1nest_atm 088 failed in run_test failed 
[BL] Error: Test hafs_regional_storm_following_1nest_atm_ocn 090 failed in run_test failed 
[BL] Error: Test hafs_regional_storm_following_1nest_atm_ocn_wav 091 failed in run_test failed 
[BL] Error: Test hafs_global_storm_following_1nest_atm 092 failed in run_test failed 
[BL] Error: Test hafs_regional_docn 093 failed in run_test failed 
[BL] Error: Test hafs_regional_docn_oisst 094 failed in run_test failed 
[BL] Error: Test hafs_regional_datm_cdeps 095 failed in run_test failed 
[BL] Error: Test datm_cdeps_mx025_cfsr 103 failed in run_test failed 
[BL] Error: Test datm_cdeps_mx025_gefs 104 failed in run_test failed 
[BL] Error: Test regional_atmaq_debug 115 failed in run_test failed 
[BL] Error: Test compile_022 failed in run_compile failed 
[BL] Error: Test compile_023 failed in run_compile failed 
[BL] Error: Test compile_024 failed in run_compile failed 
[BL] Error: Test compile_025 failed in run_compile failed 
Please make changes and add the following label back: cheyenne-intel-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: gnu
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1172581620/20221220233011/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1172581620/20221221012742/ufs-weather-model
Please make changes and add the following label back: hera-gnu-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1172581620/20221220234509/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1172581620/20221221013850/ufs-weather-model
[RT] Error: Test control_2dwrtdecomp 021 failed in check_result failed 
[RT] Error: Test control_2dwrtdecomp 021 failed in run_test failed 
[RT] Error: Test control_fhzero 022 failed in check_result failed 
[RT] Error: Test control_fhzero 022 failed in run_test failed 
[RT] Error: Test control_2threads_debug 078 failed in check_result failed 
[RT] Error: Test control_2threads_debug 078 failed in run_test failed 
Please make changes and add the following label back: hera-intel-BL

**Comment by grantfirl** [comment]
@dustinswales We are out of space on Cheyenne again. Could you remove the rt_* data in /glade/scratch/dswales/FV3_RT and delete the created baselines in /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/NCAR/main-20221220/* please? Should we also consider deleting some of the old baseline data if it is counting against the same quota?

**Comment by dustinswales** [comment]
@grantfirl Yes I will clean up some space on Cheyenne now.
Removing some old baselines will definitely help. How many should we keep? (I think 3 would suffice, just off the top of my head)

**Comment by grantfirl** [comment]
> @grantfirl Yes I will clean up some space on Cheyenne now. Removing some old baselines will definitely help. How many should we keep? (I think 3 would suffice, just off the top of my head)

Sure, 3 sounds fine. I'm going to need to apply the changes in https://github.com/ufs-community/ufs-weather-model/commit/7e98ecf225422615675f724e16ef6a87fe27b5a5 (which is ahead of the current PR) in order for the hera/intel RTs to pass.

**Comment by grantfirl** [comment]
@dustinswales Could you also remove /scratch1/BMC/gmtb/RT/NCAR/main-20221220/INTEL so that we can rerun hera-intel-BL please?

**Comment by dustinswales** [comment]
> > @grantfirl Yes I will clean up some space on Cheyenne now. Removing some old baselines will definitely help. How many should we keep? (I think 3 would suffice, just off the top of my head)
> 
> Sure, 3 sounds fine. I'm going to need to apply the changes in [ufs-community@7e98ecf](https://github.com/ufs-community/ufs-weather-model/commit/7e98ecf225422615675f724e16ef6a87fe27b5a5) (which is ahead of the current PR) in order for the hera/intel RTs to pass.

I cleared up a bunch of space, apply tags at will!

> /scratch1/BMC/gmtb/RT/NCAR/main-20221220/INTEL

done

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: gnu
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1172581620/20221221160008/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1172581620/20221221182456/ufs-weather-model
Please make changes and add the following label back: cheyenne-gnu-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: hera
Compiler: intel
Job: BL
[BL] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1172581620/20221221230017/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /scratch1/BMC/gmtb/RT/auto_RT/Pull_Requests/1172581620/20221222010058/ufs-weather-model
Please make changes and add the following label back: hera-intel-BL

**Comment by dustinswales** [comment]
***Automated RT Failure Notification***
Machine: cheyenne
Compiler: intel
Job: BL
[BL] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1172581620/20221221161507/ufs-weather-model
[BL] Baseline creation and move successful
[RT] Repo location: /glade/scratch/epicufsrt/GMTB/ufs-weather-model/RT/auto_RT/Pull_Requests/1172581620/20221221190148/ufs-weather-model
Please make changes and add the following label back: cheyenne-intel-BL

**Comment by grantfirl** [comment]
I think that this is ready to merge once this and https://github.com/NCAR/fv3atm/pull/78 are approved.

**Review by dustinswales — APPROVED** [review]

**Pull request merged**
